"""Seed script for Multilingual static UI text entries across all 23 Indian languages."""

from app.database import SessionLocal
from app.models import Multilingual

STATIC_UI_TRANSLATIONS = [
    {
        "key": "nav_dashboard",
        "english": "Dashboard",
        "hindi": "डैशबोर्ड",
        "telugu": "డాష్‌బోర్డ్",
        "tamil": "டாஷ்போர்டு",
        "kannada": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "malayalam": "ഡാഷ്‌ബോർഡ്",
        "marathi": "डॅशबोर्ड",
        "gujarati": "ડેશબોર્ડ",
        "bengali": "ড্যাশবোর্ড",
        "punjabi": "ਡੈਸ਼ਬੋਰਡ",
        "odia": "ଡ୍ୟାସବୋର୍ଡ",
        "assamese": "ড্যাশব’ৰ্ড",
        "urdu": "ڈیش بورڈ",
        "maithili": "डैशबोर्ड",
        "manipuri": "ড্যাশবোর্দ",
        "santali": "ᱰᱮᱥᱵᱳᱨᱰ",
        "bodo": "डेसबर्ड",
        "dogri": "डैशबोर्ड",
        "kashmiri": "ڈیش بورڈ",
        "konkani": "डॅशबोर्ड",
        "nepali": "ड्यासबोर्ड",
        "sanskrit": "पट्टिकामुखम्",
        "sindhi": "ڊيش بورڊ"
    },
    {
        "key": "nav_weather",
        "english": "Weather",
        "hindi": "मौसम",
        "telugu": "వాతావరణం",
        "tamil": "வானிலை",
        "kannada": "ಹವಾಮಾನ",
        "malayalam": "കാലാവസ്ഥ",
        "marathi": "हवामान",
        "gujarati": "હવામાન",
        "bengali": "আবহাওয়া",
        "punjabi": "ਮੌਸਮ",
        "odia": "ପାଣିପାଗ",
        "assamese": "বতৰ",
        "urdu": "موسم",
        "maithili": "मौसम",
        "manipuri": "נוংશા-নুংশিত",
        "santali": "ᱥᱮᱨᱢᱟ ᱫᱟ cross",
        "bodo": "बोथोर",
        "dogri": "मौसम",
        "kashmiri": "موسم",
        "konkani": "हवामान",
        "nepali": "मौसम",
        "sanskrit": "ऋतुमानम्",
        "sindhi": "موسم"
    },
    {
        "key": "nav_soil_analysis",
        "english": "Soil Analysis",
        "hindi": "मृदा विश्लेषण",
        "telugu": "నేల విశ్లేషణ",
        "tamil": "மண் பகுப்பாய்வு",
        "kannada": "ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ",
        "malayalam": "മണ്ണ് വിശകലനം",
        "marathi": "माती विश्लेषण",
        "gujarati": "જમીન વિશ્લેષણ",
        "bengali": "মাটি বিশ্লেষণ",
        "punjabi": "ਮਿੱਟੀ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ",
        "odia": "ମାଟି ବିଶ୍ଳେଷଣ",
        "assamese": "মাটি বিশ্লেষণ",
        "urdu": "مٹی کا تجزیہ",
        "maithili": "माटि विश्लेषण",
        "manipuri": "লৈবাক ঙাকশেন",
        "santali": "ᱦᱟᱥᱟ ᱵᱤᱪᱟᱹᱨ",
        "bodo": "हाबांसा नायबिजिरनाय",
        "dogri": "मिट्‍टी दा विश्लेषण",
        "kashmiri": "زمیٖن تجزِیہہ",
        "konkani": "मातयेची तपासणी",
        "nepali": "माटो विश्लेषण",
        "sanskrit": "मृत्तिका विश्लेषणम्",
        "sindhi": "مٽي جو تجزيو"
    },
    {
        "key": "nav_profile",
        "english": "Profile",
        "hindi": "प्रोफ़ाइल",
        "telugu": "ప్రొఫైల్",
        "tamil": "சுயவிவரம்",
        "kannada": "ಪ್ರೊಫೈಲ್",
        "malayalam": "പ്രൊഫൈൽ",
        "marathi": "प्रोफाईल",
        "gujarati": "પ્રોફાઇલ",
        "bengali": "প্রোফাইল",
        "punjabi": "ਪ੍ਰੋਫਾਈਲ",
        "odia": "ପ୍ରୋଫାଇଲ୍",
        "assamese": "প্ৰফাইল",
        "urdu": "پروفائل",
        "maithili": "प्रोफ़ाइल",
        "manipuri": "প্রোফাইল",
        "santali": "ᱯᱨᱳᱯᱷᱟᱭᱤᱞ",
        "bodo": "प्रोफाइल",
        "dogri": "प्रोफाइल",
        "kashmiri": "پروفائل",
        "konkani": "प्रोफाईल",
        "nepali": "प्रोफाइल",
        "sanskrit": "विवरणम्",
        "sindhi": "پروفائل"
    },
    {
        "key": "btn_login",
        "english": "Login",
        "hindi": "लॉग इन करें",
        "telugu": "లాగిన్ చేయండి",
        "tamil": "உள்நுழையவும்",
        "kannada": "ಲಾಗಿನ್ ಮಾಡಿ",
        "malayalam": "ലോഗിൻ ചെയ്യുക",
        "marathi": "लॉगिन करा",
        "gujarati": "લૉગિન કરો",
        "bengali": "লগইন করুন",
        "punjabi": "ਲੌਗਇਨ ਕਰੋ",
        "odia": "ଲଗଇନ୍ କରନ୍ତୁ",
        "assamese": "লগইন কৰক",
        "urdu": "لاگ ان کریں",
        "maithili": "लॉग इन करू",
        "manipuri": "লোগইন তৌবীয়ু",
        "santali": "ᱞᱚᱜᱤᱱ",
        "bodo": "ल'गइन खालाम",
        "dogri": "लॉग इन करो",
        "kashmiri": "لاگ اِن کرو",
        "konkani": "लॉगिन करा",
        "nepali": "लगइन गर्नुहोस्",
        "sanskrit": "प्रवेशं करोतु",
        "sindhi": "لاگ ان ڪريو"
    },
    {
        "key": "btn_logout",
        "english": "Logout",
        "hindi": "लॉग आउट करें",
        "telugu": "లాగ్ అవుట్ చేయండి",
        "tamil": "வெளியேறவும்",
        "kannada": "ಲಾಗ್ ಔಟ್ ಮಾಡಿ",
        "malayalam": "ലോഗ് ഔട്ട് ചെയ്യുക",
        "marathi": "लॉग आउट करा",
        "gujarati": "લૉગ આઉટ કરો",
        "bengali": "লগআউট করুন",
        "punjabi": "ਲੌਗ ਆਉਟ ਕਰੋ",
        "odia": "ଲଗଆଉଟ୍ କରନ୍ତୁ",
        "assamese": "লগআউট কৰক",
        "urdu": "لاگ آؤٹ کریں",
        "maithili": "लॉग आउट करू",
        "manipuri": "লোগআউট তৌবীয়ু",
        "santali": "ᱞᱚᱜᱽ ᱟᱣᱩᱴ",
        "bodo": "ल'गआउट खालाम",
        "dogri": "लॉग आउट करो",
        "kashmiri": "لاگ آؤٹ کرو",
        "konkani": "लॉग आउट करा",
        "nepali": "लगआउट गर्नुहोस्",
        "sanskrit": "निर्गमनं करोतु",
        "sindhi": "لاگ آئوٽ ڪريو"
    },
    {
        "key": "lbl_submit",
        "english": "Submit",
        "hindi": "जमा करें",
        "telugu": "సమర్పించు",
        "tamil": "சமர்ப்பிக்கவும்",
        "kannada": "ಸಲ್ಲಿಸಿ",
        "malayalam": "സമർപ്പിക്കുക",
        "marathi": "सबमिट करा",
        "gujarati": "સબમિટ કરો",
        "bengali": "জমা দিন",
        "punjabi": "ਜਮ੍ਹਾਂ ਕਰੋ",
        "odia": "ଦାଖଲ କରନ୍ତୁ",
        "assamese": "জমা দিয়ক",
        "urdu": "جمع کریں",
        "maithili": "जमा करू",
        "manipuri": "সবমিট তৌবীয়ু",
        "santali": "ᱥᱟᱵᱽᱢᱤᱴ",
        "bodo": "सबमिट खालाम",
        "dogri": "जमा करो",
        "kashmiri": "جمع کرو",
        "konkani": "सबमिट करा",
        "nepali": "बुझाउनुहोस्",
        "sanskrit": "प्रेषयतु",
        "sindhi": "جمع ڪريو"
    },
    {
        "key": "lbl_cancel",
        "english": "Cancel",
        "hindi": "रद्द करें",
        "telugu": "రద్దు చేయండి",
        "tamil": "ரத்து செய்யுபவும்",
        "kannada": "ರದ್ದುಗೊಳಿಸಿ",
        "malayalam": "റദ്ദാക്കുക",
        "marathi": "रद्द करा",
        "gujarati": "રદ કરો",
        "bengali": "বাতিল করুন",
        "punjabi": "ਰੱਦ ਕਰੋ",
        "odia": "ବାତିଲ୍ କରନ୍ତୁ",
        "assamese": "বাতিল কৰক",
        "urdu": "منسوخ کریں",
        "maithili": "रद्द करू",
        "manipuri": "કેન્સેલ তৌবীয়ু",
        "santali": "ᱠᱮᱱᱥᱚᱞ",
        "bodo": "केन्सेल खालाम",
        "dogri": "रद्द करो",
        "kashmiri": "منسوخ کرو",
        "konkani": "रद्द करा",
        "nepali": "रद्ध गर्नुहोस्",
        "sanskrit": "निरस्यतु",
        "sindhi": "منسوخ ڪريو"
    },
    {
        "key": "lbl_search_location",
        "english": "Search Location",
        "hindi": "स्थान खोजें",
        "telugu": "స్థానాన్ని శోధించండి",
        "tamil": "இடத்தைத் தேடுங்கள்",
        "kannada": "ಸ್ಥಳ ಹುಡುಕಿ",
        "malayalam": "സ്ഥലം തിരയുക",
        "marathi": "स्थान शोधा",
        "gujarati": "સ્થાન શોધો",
        "bengali": "স্থান খুঁজুন",
        "punjabi": "ਸਥਾਨ ਲੱਭੋ",
        "odia": "ସ୍ଥାନ ଖୋଜନ୍ତୁ",
        "assamese": "স্থান বিচাৰক",
        "urdu": "مقام تلاش کریں",
        "maithili": "स्थान खोजू",
        "manipuri": "লৈফম থীবীয়ু",
        "santali": "ᱴᱷᱟᱶ ᱯᱟᱸᱡᱟ",
        "bodo": "जायगा नागिर",
        "dogri": "स्थान लभ्भो",
        "kashmiri": "جائے لاڈِو",
        "konkani": "सुवात सोधात",
        "nepali": "स्थान खोज्नुहोस्",
        "sanskrit": "स्थानं अन्विषयतु",
        "sindhi": "جڳهه ڳوليو"
    },
    {
        "key": "lbl_5day_forecast",
        "english": "5-Day Forecast",
        "hindi": "5-दिवसीय पूर्वानुमान",
        "telugu": "5-రోజుల వాతావరణ అంచనా",
        "tamil": "5 நாள் வானிலை முன்னறிவிப்பு",
        "kannada": "5-ದಿನದ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
        "malayalam": "5 ദിവസത്തെ കാലാവസ്ഥാ പ്രവചനം",
        "marathi": "५ दिवसांचा हवामान अंदाज",
        "gujarati": "5-દિવસનો હવામાન અંદાજ",
        "bengali": "৫-দিনের আবহাওয়া পূর্বাভাস",
        "punjabi": "5-ਦਿਨਾਂ ਦਾ ਮੌਸਮ ਪੂਰਵ-ਅਨੁਮਾਨ",
        "odia": "୫-ଦିନର ପାଣିପାଗ ପୂର୍ବାନୁମାନ",
        "assamese": "৫-দিনীয়া বতাহ-পানীৰ পূৰ্বাভাস",
        "urdu": "5 روزہ موسم کی پیشگوئی",
        "maithili": "५-दिवसीय मौसम पूर्वानुमान",
        "manipuri": "নুমিৎ ५ নিংগী נוংશા-নুংশিত পরিং",
        "santali": "᱕ ᱢᱟᱦᱟᱸ cross ᱟᱸᱫᱟᱡᱽ",
        "bodo": "5 साननि बोथोर रादाब",
        "dogri": "5-दिनें दा पूर्वानुमान",
        "kashmiri": "۵ دۄہَن ہُنٛد موسمُک احوال",
        "konkani": "५ दिसांचो हवामान अंदाज",
        "nepali": "५-दिने मौसम पूर्वानुमान",
        "sanskrit": "पञ्चदिवसीयऋतुमानभविष्यवाणी",
        "sindhi": "5 ڊينھن جي موسم جي اڳڪٿي"
    },
]

def seed_multilingual():
    db = SessionLocal()
    try:
        for item in STATIC_UI_TRANSLATIONS:
            entry = db.query(Multilingual).filter(Multilingual.key == item["key"]).first()
            if not entry:
                db.add(Multilingual(**item))
            else:
                for k, v in item.items():
                    if k != "key" and hasattr(entry, k):
                        setattr(entry, k, v)
        db.commit()
        print("[OK] Multilingual static UI text entries successfully seeded across all 23 Indian languages!")
    except Exception as exc:
        db.rollback()
        print(f"[X] Failed to seed multilingual table: {exc}")
    finally:
        db.close()

if __name__ == "__main__":
    seed_multilingual()
