/**
 * Script to add second batch of missing critical keys to all language sections in adminTranslations.ts
 * Keys: markAllRead, notifications, unread, read, allCaughtUp, noNotifications, markAsRead,
 * close, viewDetails, allNotificationsMarkedRead, reports, signOut, aiFarmingPlatform,
 * crop, fertilizer, weather, history, community, chatbot, about, profile, settings,
 * disease, ytd2026, activeUsersToday
 */
import { readFileSync, writeFileSync } from 'fs';

const filePath = './AI-Based-Soil-Health-Assessment-System-for-Nutrient-Deficiency-Detection-and-Crop-Recom_Jun_2026-frontend-team-1/src/translations/adminTranslations.ts';
let content = readFileSync(filePath, 'utf8');

// First, add the English keys to the en section (before "cancel" line we just added)
// Find the noFeedbackMatches in English section
const enNoFeedback = content.indexOf('    "noFeedbackMatches": "No feedback matches your search."');
const enLineEnd = content.indexOf('\n', enNoFeedback);

const enNewKeys = [
  '    "markAllRead": "Mark all read",',
  '    "notifications": "Notifications",',
  '    "unread": "Unread",',
  '    "read": "Read",',
  '    "all": "All",',
  '    "allCaughtUp": "All caught up",',
  '    "noNotifications": "No notifications",',
  '    "markAsRead": "Mark as read",',
  '    "close": "Close",',
  '    "viewDetails": "View Details",',
  '    "allNotificationsMarkedRead": "All notifications marked as read",',
  '    "reports": "Reports",',
  '    "signOut": "Sign Out",',
  '    "aiFarmingPlatform": "AI Farming Platform",',
  '    "crop": "Crop Recommendation",',
  '    "fertilizer": "Fertilizer Recommendation",',
  '    "weather": "Weather",',
  '    "history": "Prediction History",',
  '    "community": "Farmer Community",',
  '    "chatbot": "AI Chatbot",',
  '    "about": "About AgroAI",',
  '    "profile": "Profile",',
  '    "settings": "Settings",',
  '    "disease": "Disease Detection",',
  '    "dashboard": "Dashboard",',
].join('\n');

content = content.slice(0, enLineEnd + 1) + enNewKeys + '\n' + content.slice(enLineEnd + 1);
console.log('Added English keys.');

// Translations for each language - second batch
const additions2 = {
  hi: {
    markAllRead: "सभी पढ़े हुए चिह्नित करें",
    notifications: "सूचनाएं",
    unread: "अपठित",
    read: "पढ़ा",
    all: "सभी",
    allCaughtUp: "सब पकड़ा गया",
    noNotifications: "कोई सूचना नहीं",
    markAsRead: "पढ़ा हुआ चिह्नित करें",
    close: "बंद करें",
    viewDetails: "विवरण देखें",
    allNotificationsMarkedRead: "सभी सूचनाएं पढ़ी हुई चिह्नित हैं",
    reports: "रिपोर्ट",
    signOut: "साइन आउट",
    aiFarmingPlatform: "एआई कृषि प्लेटफ़ॉर्म",
    crop: "फसल सिफारिश",
    fertilizer: "उर्वरक सिफारिश",
    weather: "मौसम",
    history: "भविष्यवाणी इतिहास",
    community: "किसान समुदाय",
    chatbot: "एआई चैटबॉट",
    about: "एग्रोएआई के बारे में",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    disease: "रोग पहचान",
    dashboard: "डैशबोर्ड",
  },
  te: {
    markAllRead: "అన్నీ చదివినట్లు గుర్తించు",
    notifications: "నోటిఫికేషన్లు",
    unread: "చదవనివి",
    read: "చదివినవి",
    all: "అన్నీ",
    allCaughtUp: "అన్నీ పట్టుకున్నారు",
    noNotifications: "నోటిఫికేషన్లు లేవు",
    markAsRead: "చదివినట్లు గుర్తించు",
    close: "మూసివేయి",
    viewDetails: "వివరాలు చూడు",
    allNotificationsMarkedRead: "అన్ని నోటిఫికేషన్లు చదివినట్లు గుర్తించబడ్డాయి",
    reports: "నివేదికలు",
    signOut: "సైన్ అవుట్",
    aiFarmingPlatform: "AI వ్యవసాయ వేదిక",
    crop: "పంట సిఫారసు",
    fertilizer: "ఎరువుల సిఫారసు",
    weather: "వాతావరణం",
    history: "అంచనా చరిత్ర",
    community: "రైతు సమాజం",
    chatbot: "AI చాట్‌బాట్",
    about: "AgroAI గురించి",
    profile: "ప్రొఫైల్",
    settings: "సెట్టింగులు",
    disease: "వ్యాధి గుర్తింపు",
    dashboard: "డాష్‌బోర్డ్",
  },
  ta: {
    markAllRead: "அனைத்தையும் படித்தது என குறி",
    notifications: "அறிவிப்புகள்",
    unread: "படிக்காதது",
    read: "படித்தது",
    all: "அனைத்தும்",
    allCaughtUp: "அனைத்தும் பார்க்கப்பட்டது",
    noNotifications: "அறிவிப்புகள் இல்லை",
    markAsRead: "படித்ததாக குறி",
    close: "மூடு",
    viewDetails: "விவரங்களைக் காண்க",
    allNotificationsMarkedRead: "அனைத்து அறிவிப்புகளும் படிக்கப்பட்டதாக குறிக்கப்பட்டன",
    reports: "அறிக்கைகள்",
    signOut: "வெளியேறு",
    aiFarmingPlatform: "AI விவசாய தளம்",
    crop: "பயிர் பரிந்துரை",
    fertilizer: "உரம் பரிந்துரை",
    weather: "வானிலை",
    history: "கணிப்பு வரலாறு",
    community: "விவசாயி சமூகம்",
    chatbot: "AI சாட்பாட்",
    about: "AgroAI பற்றி",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    disease: "நோய் கண்டறிதல்",
    dashboard: "டாஷ்போர்டு",
  },
  kn: {
    markAllRead: "ಎಲ್ಲವನ್ನು ಓದಿದಂತೆ ಗುರುತಿಸಿ",
    notifications: "ಅಧಿಸೂಚನೆಗಳು",
    unread: "ಓದಲಾಗದ",
    read: "ಓದಿದ",
    all: "ಎಲ್ಲಾ",
    allCaughtUp: "ಎಲ್ಲಾ ಓದಲಾಗಿದೆ",
    noNotifications: "ಯಾವುದೇ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
    markAsRead: "ಓದಿದಂತೆ ಗುರುತಿಸಿ",
    close: "ಮುಚ್ಚಿ",
    viewDetails: "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    allNotificationsMarkedRead: "ಎಲ್ಲಾ ಅಧಿಸೂಚನೆಗಳನ್ನು ಓದಿದಂತೆ ಗುರುತಿಸಲಾಗಿದೆ",
    reports: "ವರದಿಗಳು",
    signOut: "ಸೈನ್ ಔಟ್",
    aiFarmingPlatform: "AI ಕೃಷಿ ವೇದಿಕೆ",
    crop: "ಬೆಳೆ ಶಿಫಾರಸು",
    fertilizer: "ಗೊಬ್ಬರ ಶಿಫಾರಸು",
    weather: "ಹವಾಮಾನ",
    history: "ಭವಿಷ್ಯವಾಣಿ ಇತಿಹಾಸ",
    community: "ರೈತ ಸಮುದಾಯ",
    chatbot: "AI ಚಾಟ್‌ಬಾಟ್",
    about: "AgroAI ಬಗ್ಗೆ",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    disease: "ರೋಗ ಪತ್ತೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
  },
  ml: {
    markAllRead: "എല്ലാം വായിച്ചതായി അടയാളപ്പെടുത്തുക",
    notifications: "അറിയിപ്പുകൾ",
    unread: "വായിക്കാത്ത",
    read: "വായിച്ചത്",
    all: "എല്ലാം",
    allCaughtUp: "എല്ലാം പൂർത്തിയായി",
    noNotifications: "അറിയിപ്പുകൾ ഒന്നുമില്ല",
    markAsRead: "വായിച്ചതായി അടയാളപ്പെടുത്തുക",
    close: "അടയ്ക്കുക",
    viewDetails: "വിശദാംശങ്ങൾ കാണുക",
    allNotificationsMarkedRead: "എല്ലാ അറിയിപ്പുകളും വായിച്ചതായി അടയാളപ്പെടുത്തി",
    reports: "റിപ്പോർട്ടുകൾ",
    signOut: "സൈൻ ഔട്ട്",
    aiFarmingPlatform: "AI കാർഷിക പ്ലാറ്റ്‌ഫോം",
    crop: "വിള ശിപാർശ",
    fertilizer: "വളം ശിപാർശ",
    weather: "കാലാവസ്ഥ",
    history: "പ്രവചന ചരിത്രം",
    community: "കർഷക സമൂഹം",
    chatbot: "AI ചാറ്റ്ബോട്ട്",
    about: "AgroAI-നെ കുറിച്ച്",
    profile: "പ്രൊഫൈൽ",
    settings: "ക്രമീകരണങ്ങൾ",
    disease: "രോഗ കണ്ടെത്തൽ",
    dashboard: "ഡാഷ്‌ബോർഡ്",
  },
  mr: {
    markAllRead: "सर्व वाचले म्हणून चिन्हांकित करा",
    notifications: "सूचना",
    unread: "न वाचलेल्या",
    read: "वाचलेल्या",
    all: "सर्व",
    allCaughtUp: "सर्व पाहिले",
    noNotifications: "कोणत्याही सूचना नाहीत",
    markAsRead: "वाचले म्हणून चिन्हांकित करा",
    close: "बंद करा",
    viewDetails: "तपशील पहा",
    allNotificationsMarkedRead: "सर्व सूचना वाचल्या म्हणून चिन्हांकित केल्या आहेत",
    reports: "अहवाल",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI शेती प्लॅटफॉर्म",
    crop: "पीक शिफारस",
    fertilizer: "खत शिफारस",
    weather: "हवामान",
    history: "अंदाज इतिहास",
    community: "शेतकरी समुदाय",
    chatbot: "AI चॅटबॉट",
    about: "AgroAI बद्दल",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    disease: "रोग शोध",
    dashboard: "डॅशबोर्ड",
  },
  gu: {
    markAllRead: "બધું વાંચ્યું તરીકે ચિહ્નિત કરો",
    notifications: "સૂચનાઓ",
    unread: "ન વાંચ્યું",
    read: "વાંચ્યું",
    all: "બધા",
    allCaughtUp: "બધું પકડ્યું",
    noNotifications: "કોઈ સૂચનાઓ નહીં",
    markAsRead: "વાંચ્યા તરીકે ચિહ્નિત કરો",
    close: "બંધ કરો",
    viewDetails: "વિગતો જુઓ",
    allNotificationsMarkedRead: "બધી સૂચનાઓ વાંચ્યા તરીકે ચિહ્નિત",
    reports: "અહેવાલો",
    signOut: "સાઈન આઉટ",
    aiFarmingPlatform: "AI ખેડૂત પ્લેટફોર્મ",
    crop: "પાક ભલામણ",
    fertilizer: "ખાતર ભલામણ",
    weather: "હવામાન",
    history: "આગાહીનો ઇતિહાસ",
    community: "ખેડૂત સમુદાય",
    chatbot: "AI ચૅટબૉટ",
    about: "AgroAI વિશે",
    profile: "પ્રોફાઇલ",
    settings: "સેટિંગ્સ",
    disease: "રોગ શોધ",
    dashboard: "ડૅશબૉર્ડ",
  },
  bn: {
    markAllRead: "সব পড়া হিসেবে চিহ্নিত করুন",
    notifications: "বিজ্ঞপ্তি",
    unread: "অপঠিত",
    read: "পড়া",
    all: "সব",
    allCaughtUp: "সব ধরা হয়েছে",
    noNotifications: "কোনো বিজ্ঞপ্তি নেই",
    markAsRead: "পড়া হিসেবে চিহ্নিত করুন",
    close: "বন্ধ করুন",
    viewDetails: "বিস্তারিত দেখুন",
    allNotificationsMarkedRead: "সব বিজ্ঞপ্তি পড়া হিসেবে চিহ্নিত",
    reports: "প্রতিবেদন",
    signOut: "সাইন আউট",
    aiFarmingPlatform: "AI কৃষি প্ল্যাটফর্ম",
    crop: "ফসল সুপারিশ",
    fertilizer: "সার সুপারিশ",
    weather: "আবহাওয়া",
    history: "পূর্বাভাস ইতিহাস",
    community: "কৃষক সম্প্রদায়",
    chatbot: "AI চ্যাটবট",
    about: "AgroAI সম্পর্কে",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    disease: "রোগ সনাক্তকরণ",
    dashboard: "ড্যাশবোর্ড",
  },
  pa: {
    markAllRead: "ਸਭ ਪੜ੍ਹੇ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ ਕਰੋ",
    notifications: "ਸੂਚਨਾਵਾਂ",
    unread: "ਅਣਪੜ੍ਹੀਆਂ",
    read: "ਪੜ੍ਹੀਆਂ",
    all: "ਸਭ",
    allCaughtUp: "ਸਭ ਫੜ ਲਿਆ",
    noNotifications: "ਕੋਈ ਸੂਚਨਾਵਾਂ ਨਹੀਂ",
    markAsRead: "ਪੜ੍ਹੀ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",
    viewDetails: "ਵੇਰਵੇ ਦੇਖੋ",
    allNotificationsMarkedRead: "ਸਾਰੀਆਂ ਸੂਚਨਾਵਾਂ ਪੜ੍ਹੀਆਂ ਵਜੋਂ ਚਿੰਨ੍ਹਿਤ",
    reports: "ਰਿਪੋਰਟਾਂ",
    signOut: "ਸਾਈਨ ਆਉਟ",
    aiFarmingPlatform: "AI ਖੇਤੀਬਾੜੀ ਪਲੇਟਫਾਰਮ",
    crop: "ਫਸਲ ਸਿਫਾਰਸ਼",
    fertilizer: "ਖਾਦ ਸਿਫਾਰਸ਼",
    weather: "ਮੌਸਮ",
    history: "ਭਵਿੱਖਬਾਣੀ ਇਤਿਹਾਸ",
    community: "ਕਿਸਾਨ ਭਾਈਚਾਰਾ",
    chatbot: "AI ਚੈਟਬੋਟ",
    about: "AgroAI ਬਾਰੇ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    settings: "ਸੈਟਿੰਗਾਂ",
    disease: "ਬਿਮਾਰੀ ਖੋਜ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
  },
  or: {
    markAllRead: "ସମସ୍ତ ପଢ଼ା ଭାବରେ ଚିହ୍ନିତ କରନ୍ତୁ",
    notifications: "ବିଜ୍ଞପ୍ତି",
    unread: "ଅପଠିତ",
    read: "ପଢ଼ା",
    all: "ସମସ୍ତ",
    allCaughtUp: "ସବୁ ଦେଖିଲୁ",
    noNotifications: "କୌଣସି ବିଜ୍ଞପ୍ତି ନାହିଁ",
    markAsRead: "ପଢ଼ା ଭାବରେ ଚିହ୍ନିତ କରନ୍ତୁ",
    close: "ବନ୍ଦ କରନ୍ତୁ",
    viewDetails: "ବିବରଣ ଦେଖନ୍ତୁ",
    allNotificationsMarkedRead: "ସମସ୍ତ ବିଜ୍ଞପ୍ତି ପଢ଼ା ଭାବରେ ଚିହ୍ନିତ",
    reports: "ରିପୋର୍ଟ",
    signOut: "ସାଇନ ଆଉଟ",
    aiFarmingPlatform: "AI କୃଷି ପ୍ଲାଟଫର୍ମ",
    crop: "ଫସଲ ସୁପାରିଶ",
    fertilizer: "ସାର ସୁପାରିଶ",
    weather: "ପ୍ରାଣ",
    history: "ପୂର୍ବାନୁମାନ ଇତିହାସ",
    community: "କୃଷକ ସମ୍ପ୍ରଦାୟ",
    chatbot: "AI ଚ୍ୟାଟବଟ",
    about: "AgroAI ବିଷୟରେ",
    profile: "ପ୍ରୋଫାଇଲ",
    settings: "ସଂସ୍ଥାନ",
    disease: "ରୋଗ ଚିହ୍ନଟ",
    dashboard: "ଡ୍ୟାଶ୍‌ବୋର୍ଡ",
  },
  as: {
    markAllRead: "সকলো পঢ়া বুলি চিহ্নিত কৰক",
    notifications: "জাননী",
    unread: "অপঢ়া",
    read: "পঢ়া",
    all: "সকলো",
    allCaughtUp: "সকলো চোৱা হৈছে",
    noNotifications: "কোনো জাননী নাই",
    markAsRead: "পঢ়া হিচাপে চিহ্নিত কৰক",
    close: "বন্ধ কৰক",
    viewDetails: "বিৱৰণ চাওক",
    allNotificationsMarkedRead: "সকলো জাননী পঢ়া হিচাপে চিহ্নিত",
    reports: "প্ৰতিবেদন",
    signOut: "চাইন আউট",
    aiFarmingPlatform: "AI কৃষি প্লেটফৰ্ম",
    crop: "শস্য পৰামৰ্শ",
    fertilizer: "সাৰ পৰামৰ্শ",
    weather: "বতৰ",
    history: "পূৰ্বানুমান ইতিহাস",
    community: "কৃষক সম্প্ৰদায়",
    chatbot: "AI চেটবট",
    about: "AgroAI বিষয়ে",
    profile: "প্ৰফাইল",
    settings: "ছেটিংছ",
    disease: "ৰোগ চিনাক্তকৰণ",
    dashboard: "ডেশ্বৰ্ড",
  },
  ur: {
    markAllRead: "سب کو پڑھا ہوا نشان زد کریں",
    notifications: "اطلاعات",
    unread: "نہ پڑھا",
    read: "پڑھا",
    all: "سب",
    allCaughtUp: "سب دیکھ لیا",
    noNotifications: "کوئی اطلاعات نہیں",
    markAsRead: "پڑھا ہوا نشان زد کریں",
    close: "بند کریں",
    viewDetails: "تفصیلات دیکھیں",
    allNotificationsMarkedRead: "تمام اطلاعات کو پڑھا ہوا نشان زد کیا گیا",
    reports: "رپورٹیں",
    signOut: "سائن آؤٹ",
    aiFarmingPlatform: "AI زراعت پلیٹ فارم",
    crop: "فصل کی سفارش",
    fertilizer: "کھاد کی سفارش",
    weather: "موسم",
    history: "پیش گوئی کی تاریخ",
    community: "کسان برادری",
    chatbot: "AI چیٹ بوٹ",
    about: "AgroAI کے بارے میں",
    profile: "پروفائل",
    settings: "ترتیبات",
    disease: "بیماری کی تشخیص",
    dashboard: "ڈیش بورڈ",
  },
  mai: {
    markAllRead: "सभ पढ़ल चिह्नित करू",
    notifications: "सूचना",
    unread: "नहि पढ़ल",
    read: "पढ़ल",
    all: "सभ",
    allCaughtUp: "सभ देखल",
    noNotifications: "कोनो सूचना नहि",
    markAsRead: "पढ़ल चिह्नित करू",
    close: "बंद करू",
    viewDetails: "विवरण देखू",
    allNotificationsMarkedRead: "सभ सूचना पढ़ल चिह्नित",
    reports: "रिपोर्ट",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI कृषि मंच",
    crop: "फसल सलाह",
    fertilizer: "उर्वरक सलाह",
    weather: "मौसम",
    history: "भविष्यवाणी इतिहास",
    community: "किसान समुदाय",
    chatbot: "AI चैटबॉट",
    about: "AgroAI के बारेमें",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    disease: "रोग पहचान",
    dashboard: "डैशबोर्ड",
  },
  mni: {
    markAllRead: "মরুপশিং লোইশিনবিযু",
    notifications: "নোটিফিকেশনশিং",
    unread: "লোইশিনখিদ্রবা",
    read: "লোইশিনবা",
    all: "মরম্মিংবা",
    allCaughtUp: "মরুপশিং ফোংলে",
    noNotifications: "নোটিফিকেশন লৈতে",
    markAsRead: "লোইশিনবা মার্ক তৌবিযু",
    close: "থাংবিযু",
    viewDetails: "মরুওই ফোংলু",
    allNotificationsMarkedRead: "নোটিফিকেশনশিং মরমসিং মার্ক তৌবিযু",
    reports: "রিপোর্টশিং",
    signOut: "সাইন আউট",
    aiFarmingPlatform: "AI লৌমি প্লেটফোর্ম",
    crop: "উমং শিজিন্নবা",
    fertilizer: "ফার্টিলাইজর শিজিন্নবা",
    weather: "শগোলশিং",
    history: "হিস্ট্রি",
    community: "লৌমিশিংগী মরুপ",
    chatbot: "AI চেটবট",
    about: "AgroAI মতাংদা",
    profile: "প্রোফাইল",
    settings: "সেটিংশিং",
    disease: "নোংথাং থৌরাং",
    dashboard: "ডাশ্‌বোর্ড",
  },
  sat: {
    markAllRead: "ᱦᱤᱡᱩᱜ ᱯᱟᱲᱦᱟᱣ ᱞᱮᱠᱟᱱ ᱫᱟᱜ ᱢᱮᱱ",
    notifications: "ᱥᱩᱪᱱᱟ",
    unread: "ᱵᱟᱹᱧᱩᱜ ᱵᱟ",
    read: "ᱵᱟᱹᱧᱩᱜ",
    all: "ᱦᱤᱡᱩᱜ",
    allCaughtUp: "ᱦᱤᱡᱩᱜ ᱜᱟᱜ",
    noNotifications: "ᱠᱚᱱ ᱥᱩᱪᱱᱟ ᱵᱟᱹᱧᱩᱜ ᱵᱟ",
    markAsRead: "ᱵᱟᱹᱧᱩᱜ ᱞᱮᱠᱟᱱ ᱢᱮᱱ",
    close: "ᱵᱚᱸᱫ ᱢᱮᱱ",
    viewDetails: "ᱵᱤᱵᱷᱟᱹᱨ ᱫᱮᱠᱷᱟᱣ",
    allNotificationsMarkedRead: "ᱦᱤᱡᱩᱜ ᱥᱩᱪᱱᱟ ᱵᱟᱹᱧᱩᱜ",
    reports: "ᱨᱤᱯᱚᱨᱴ",
    signOut: "ᱥᱟᱭᱤᱱ ᱟᱣᱴ",
    aiFarmingPlatform: "AI ᱭᱤᱛᱩ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ",
    crop: "ᱵᱟᱭᱥᱤ ᱥᱤᱯᱷᱟᱨᱤᱥ",
    fertilizer: "ᱰᱷᱟᱹᱠᱤ ᱥᱤᱯᱷᱟᱨᱤᱥ",
    weather: "ᱳᱫᱳᱵᱚ",
    history: "ᱯᱽᱨᱤᱫᱤᱠᱥᱚᱱ ᱤᱛᱤᱦᱟᱥ",
    community: "ᱦᱚᱲᱟᱜ ᱢᱟᱨᱥᱟᱜ",
    chatbot: "AI ᱪᱮᱴᱵᱚᱴ",
    about: "AgroAI ᱡᱚᱠᱷᱚᱱ",
    profile: "ᱯᱽᱨᱚᱯᱷᱟᱭᱤᱞ",
    settings: "ᱥᱮᱴᱤᱝ",
    disease: "ᱵᱤᱢᱟᱨ ᱫᱟᱜ",
    dashboard: "ᱰᱮᱥᱵᱚᱨᱰ",
  },
  brx: {
    markAllRead: "राव नंगाव पोरसा मानाव",
    notifications: "जुवांनि",
    unread: "नंगाव मानो",
    read: "नंगाव",
    all: "राव",
    allCaughtUp: "राव जादों",
    noNotifications: "जुवांनि मोनो",
    markAsRead: "नंगाव मानो मानाव",
    close: "बंद कर",
    viewDetails: "विवरण एब",
    allNotificationsMarkedRead: "राव जुवांनि नंगाव",
    reports: "रिपोर्टनि",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI जिउ प्लेटफर्म",
    crop: "हायफोर सुबुंथाय",
    fertilizer: "फर्टिलाइजर सुबुंथाय",
    weather: "बाथौ",
    history: "इतिहास",
    community: "हायफोर मरुप",
    chatbot: "AI चेटबट",
    about: "AgroAI थाखो",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    disease: "बिरमा",
    dashboard: "डेशबोर्ड",
  },
  doi: {
    markAllRead: "सारे पढ़े चिह्नित करो",
    notifications: "सूचनाएं",
    unread: "नेईं पढ़ी",
    read: "पढ़ी",
    all: "सारे",
    allCaughtUp: "सारे देखे",
    noNotifications: "कोई सूचना नेईं",
    markAsRead: "पढ़ी चिह्नित करो",
    close: "बंद करो",
    viewDetails: "विवरण देखो",
    allNotificationsMarkedRead: "सारी सूचनाएं पढ़ी चिह्नित",
    reports: "रिपोर्टें",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI खेती मंच",
    crop: "फसल सलाह",
    fertilizer: "खाद सलाह",
    weather: "मौसम",
    history: "भविष्यवाणी इतिहास",
    community: "किसान समुदाय",
    chatbot: "AI चैटबोट",
    about: "AgroAI बारे",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    disease: "बिमारी पहचान",
    dashboard: "डैशबोर्ड",
  },
  ks: {
    markAllRead: "سارِتھ پَرُن لَگان",
    notifications: "اِطلاعات",
    unread: "نہ پَرُن",
    read: "پَرُن",
    all: "سارِتھ",
    allCaughtUp: "سارِتھ دیٖتھ بٲو",
    noNotifications: "کوئی اِطلاع ناہ",
    markAsRead: "پَرُن لَگان",
    close: "بَند کریو",
    viewDetails: "تَفصِیل دیٖتھ",
    allNotificationsMarkedRead: "سارِتھ اِطلاعات پَرُن لَگان",
    reports: "رِپورٹَن",
    signOut: "سائِن آؤٹ",
    aiFarmingPlatform: "AI زَمِیٖندار پلیٹ فارم",
    crop: "کِھتَئی سِفارِش",
    fertilizer: "کھاد سِفارِش",
    weather: "مَوسَم",
    history: "تاریٖخ",
    community: "کسانَن برادَرِی",
    chatbot: "AI چیٹ بٲٹ",
    about: "AgroAI بابَت",
    profile: "پروفائِل",
    settings: "سیٖٹِنگ",
    disease: "بیماری",
    dashboard: "ڈیش بورڈ",
  },
  kok: {
    markAllRead: "सगळें वाचल्यात म्हणून नोंद करचें",
    notifications: "सुचोवण्यो",
    unread: "नवाचल्यात",
    read: "वाचल्यात",
    all: "सगळें",
    allCaughtUp: "सगळें दिसता",
    noNotifications: "कसल्यो सुचोवण्यो ना",
    markAsRead: "वाचल्यात म्हणून नोंद करचें",
    close: "बंद करचें",
    viewDetails: "विवरण पळयचें",
    allNotificationsMarkedRead: "सगळ्यो सुचोवण्यो वाचल्यात",
    reports: "अहवाल",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI शेत प्लेटफोर्म",
    crop: "पीक सलाह",
    fertilizer: "खत सलाह",
    weather: "हवा",
    history: "इतिहास",
    community: "शेतकरी समाज",
    chatbot: "AI चॅटबोट",
    about: "AgroAI विशीं",
    profile: "प्रोफाइल",
    settings: "सेटिंग",
    disease: "रोग शोध",
    dashboard: "डॅशबोर्ड",
  },
  ne: {
    markAllRead: "सबै पढिएको चिह्नित गर्नुहोस्",
    notifications: "सूचनाहरू",
    unread: "नपढिएको",
    read: "पढिएको",
    all: "सबै",
    allCaughtUp: "सबै हेरिसकियो",
    noNotifications: "कुनै सूचना छैन",
    markAsRead: "पढिएको चिह्नित गर्नुहोस्",
    close: "बन्द गर्नुहोस्",
    viewDetails: "विवरण हेर्नुहोस्",
    allNotificationsMarkedRead: "सबै सूचना पढिएको चिह्नित",
    reports: "प्रतिवेदनहरू",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI कृषि मञ्च",
    crop: "बाली सिफारिश",
    fertilizer: "मल सिफारिश",
    weather: "मौसम",
    history: "भविष्यवाणी इतिहास",
    community: "किसान समुदाय",
    chatbot: "AI च्याटबोट",
    about: "AgroAI बारे",
    profile: "प्रोफाइल",
    settings: "सेटिङ",
    disease: "रोग पत्ता लगाउने",
    dashboard: "ड्यासबोर्ड",
  },
  sa: {
    markAllRead: "सर्वं पठितं चिह्नयतु",
    notifications: "सूचनाः",
    unread: "अपठितम्",
    read: "पठितम्",
    all: "सर्वम्",
    allCaughtUp: "सर्वं दृष्टम्",
    noNotifications: "कापि सूचना नास्ति",
    markAsRead: "पठितं चिह्नयतु",
    close: "मुदयतु",
    viewDetails: "विस्तारं पश्यतु",
    allNotificationsMarkedRead: "सर्वाः सूचनाः पठिताः",
    reports: "प्रतिवेदनानि",
    signOut: "साइन आउट",
    aiFarmingPlatform: "AI कृषि वेदिका",
    crop: "कृषि अनुशंसा",
    fertilizer: "उर्वरक अनुशंसा",
    weather: "वायुमण्डलम्",
    history: "इतिहासः",
    community: "कृषक समुदायः",
    chatbot: "AI चाटबॉट",
    about: "AgroAI विषये",
    profile: "परिचयः",
    settings: "व्यवस्थाः",
    disease: "रोग-निर्धारणम्",
    dashboard: "डाशबोर्डम्",
  },
  sd: {
    markAllRead: "سڀ پڙهيل نشان ڪريو",
    notifications: "اطلاع",
    unread: "نه پڙهيل",
    read: "پڙهيل",
    all: "سڀ",
    allCaughtUp: "سڀ ڏٺل",
    noNotifications: "ڪا به اطلاع ناهي",
    markAsRead: "پڙهيل نشان ڪريو",
    close: "بند ڪريو",
    viewDetails: "تفصيل ڏسو",
    allNotificationsMarkedRead: "سڀ اطلاعات پڙهيل نشان ٿيل",
    reports: "رپورٽون",
    signOut: "سائن آئوٽ",
    aiFarmingPlatform: "AI زراعت پليٽ فارم",
    crop: "فصل سفارش",
    fertilizer: "کاد سفارش",
    weather: "موسم",
    history: "اڳڪٿائي تاريخ",
    community: "ڪسان سماج",
    chatbot: "AI چيٽ بوٽ",
    about: "AgroAI بابت",
    profile: "پروفائيل",
    settings: "سيٽنگون",
    disease: "بيماري جي پرک",
    dashboard: "ڊيش بورڊ",
  },
};

// For each language, insert new keys after the batch we just added (after the platform line)
for (const [lang, keys] of Object.entries(additions2)) {
  // Find the "platform" key we added in the previous batch for this language
  const platformKey = `    "platform": `;
  const langMarker = `  "${lang}": {`;

  const langStart = content.indexOf(langMarker);
  if (langStart === -1) {
    console.log(`WARNING: Language section '${lang}' not found!`);
    continue;
  }

  // Find the platform key line within this language section
  const platformIdx = content.indexOf(platformKey, langStart);
  if (platformIdx === -1) {
    console.log(`WARNING: Could not find 'platform' key in '${lang}' section!`);
    continue;
  }

  // Find the end of the platform line
  const lineEnd = content.indexOf('\n', platformIdx);
  if (lineEnd === -1) continue;

  // Build insert string
  const insertLines = Object.entries(keys).map(([key, val]) => {
    const escaped = val.replace(/"/g, '\\"');
    return `    "${key}": "${escaped}",`;
  }).join('\n');

  // Insert after the platform line
  content = content.slice(0, lineEnd + 1) + insertLines + '\n' + content.slice(lineEnd + 1);
  console.log(`Added ${Object.keys(keys).length} keys to '${lang}' section (batch 2)`);
}

writeFileSync(filePath, content, 'utf8');
console.log('\nDone! adminTranslations.ts updated with batch 2 keys.');
