/**
 * Script to add missing critical admin keys to all language sections in adminTranslations.ts
 * Keys being added: cancel, confirm, email, role, name, search, deleteUser, deleteUserConfirm,
 * createUser, createNewUserAccount, addNewUser, totalPredictions, actions, joined, question,
 * activeUsersToday, noPredictionsMadeYet, chatbotMonitoring, incidents, soil, nutrientAlert,
 * allSupportedLanguages, languagesUsed, predictionTrends, analytics, security, custom, platform
 */
import { readFileSync, writeFileSync } from 'fs';

const filePath = './AI-Based-Soil-Health-Assessment-System-for-Nutrient-Deficiency-Detection-and-Crop-Recom_Jun_2026-frontend-team-1/src/translations/adminTranslations.ts';
let content = readFileSync(filePath, 'utf8');

// Translations for each language
const additions = {
  hi: {
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    email: "ईमेल",
    role: "भूमिका",
    name: "नाम",
    search: "खोजें",
    deleteUser: "उपयोगकर्ता हटाएं",
    deleteUserConfirm: "क्या आप वाकई स्थायी रूप से हटाना चाहते हैं",
    createUser: "उपयोगकर्ता बनाएं",
    createNewUserAccount: "नया उपयोगकर्ता खाता बनाएं",
    addNewUser: "नया उपयोगकर्ता जोड़ें",
    totalPredictions: "कुल भविष्यवाणियाँ",
    actions: "कार्यवाही",
    joined: "शामिल हुए",
    question: "प्रश्न",
    activeUsersToday: "आज के सक्रिय उपयोगकर्ता",
    noPredictionsMadeYet: "अभी तक कोई भविष्यवाणी नहीं की गई",
    chatbotMonitoring: "चैटबॉट निगरानी",
    incidents: "घटनाएं",
    soil: "मृदा वर्गीकरण",
    nutrientAlert: "पोषक तत्व अलर्ट",
    allSupportedLanguages: "सभी समर्थित भाषाएं",
    languagesUsed: "उपयोग की गई भाषाएं",
    predictionTrends: "भविष्यवाणी रुझान",
    analytics: "विश्लेषण और अंतर्दृष्टि",
    security: "सुरक्षा",
    custom: "कस्टम",
    platform: "मंच",
  },
  te: {
    cancel: "రద్దు చేయండి",
    confirm: "నిర్ధారించండి",
    email: "ఇమెయిల్",
    role: "పాత్ర",
    name: "పేరు",
    search: "వెతకండి",
    deleteUser: "వినియోగదారుని తొలగించండి",
    deleteUserConfirm: "మీరు శాశ్వతంగా తొలగించాలనుకుంటున్నారా",
    createUser: "వినియోగదారుని సృష్టించండి",
    createNewUserAccount: "కొత్త వినియోగదారు ఖాతా సృష్టించండి",
    addNewUser: "కొత్త వినియోగదారుని జోడించండి",
    totalPredictions: "మొత్తం అంచనాలు",
    actions: "చర్యలు",
    joined: "చేరారు",
    question: "ప్రశ్న",
    activeUsersToday: "నేటి క్రియాశీల వినియోగదారులు",
    noPredictionsMadeYet: "ఇంకా ఎటువంటి అంచనాలు చేయబడలేదు",
    chatbotMonitoring: "చాట్‌బాట్ పర్యవేక్షణ",
    incidents: "సంఘటనలు",
    soil: "మట్టి వర్గీకరణ",
    nutrientAlert: "పోషక హెచ్చరికలు",
    allSupportedLanguages: "అన్ని మద్దతు ఉన్న భాషలు",
    languagesUsed: "ఉపయోగించిన భాషలు",
    predictionTrends: "అంచనా పోకడలు",
    analytics: "విశ్లేషణలు & అంతర్దృష్టులు",
    security: "భద్రత",
    custom: "అనుకూల",
    platform: "వేదిక",
  },
  ta: {
    cancel: "ரத்து செய்",
    confirm: "உறுதிப்படுத்து",
    email: "மின்னஞ்சல்",
    role: "பாத்திரம்",
    name: "பெயர்",
    search: "தேடு",
    deleteUser: "பயனரை நீக்கு",
    deleteUserConfirm: "நிரந்தரமாக நீக்க விரும்புகிறீர்களா",
    createUser: "பயனரை உருவாக்கு",
    createNewUserAccount: "புதிய பயனர் கணக்கை உருவாக்கு",
    addNewUser: "புதிய பயனரை சேர்",
    totalPredictions: "மொத்த கணிப்புகள்",
    actions: "செயல்கள்",
    joined: "சேர்ந்தார்",
    question: "கேள்வி",
    activeUsersToday: "இன்றைய செயலில் உள்ள பயனர்கள்",
    noPredictionsMadeYet: "இன்னும் எந்த கணிப்பும் செய்யப்படவில்லை",
    chatbotMonitoring: "சாட்பாட் கண்காணிப்பு",
    incidents: "சம்பவங்கள்",
    soil: "மண் வகைப்பாடு",
    nutrientAlert: "ஊட்டச்சத்து எச்சரிக்கைகள்",
    allSupportedLanguages: "அனைத்து ஆதரிக்கப்படும் மொழிகள்",
    languagesUsed: "பயன்படுத்தப்பட்ட மொழிகள்",
    predictionTrends: "கணிப்பு போக்குகள்",
    analytics: "பகுப்பாய்வு & நுண்ணறிவுகள்",
    security: "பாதுகாப்பு",
    custom: "தனிப்பயன்",
    platform: "தளம்",
  },
  kn: {
    cancel: "ರದ್ದು ಮಾಡಿ",
    confirm: "ದೃಢೀಕರಿಸಿ",
    email: "ಇಮೇಲ್",
    role: "ಪಾತ್ರ",
    name: "ಹೆಸರು",
    search: "ಹುಡುಕಿ",
    deleteUser: "ಬಳಕೆದಾರರನ್ನು ಅಳಿಸಿ",
    deleteUserConfirm: "ನೀವು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲು ಬಯಸುತ್ತೀರಾ",
    createUser: "ಬಳಕೆದಾರರನ್ನು ರಚಿಸಿ",
    createNewUserAccount: "ಹೊಸ ಬಳಕೆದಾರ ಖಾತೆ ರಚಿಸಿ",
    addNewUser: "ಹೊಸ ಬಳಕೆದಾರರನ್ನು ಸೇರಿಸಿ",
    totalPredictions: "ಒಟ್ಟು ಭವಿಷ್ಯವಾಣಿಗಳು",
    actions: "ಕ್ರಿಯೆಗಳು",
    joined: "ಸೇರಿದರು",
    question: "ಪ್ರಶ್ನೆ",
    activeUsersToday: "ಇಂದಿನ ಸಕ್ರಿಯ ಬಳಕೆದಾರರು",
    noPredictionsMadeYet: "ಇನ್ನೂ ಯಾವುದೇ ಭವಿಷ್ಯವಾಣಿ ಮಾಡಿಲ್ಲ",
    chatbotMonitoring: "ಚಾಟ್‌ಬಾಟ್ ಮೇಲ್ವಿಚಾರಣೆ",
    incidents: "ಘಟನೆಗಳು",
    soil: "ಮಣ್ಣು ವರ್ಗೀಕರಣ",
    nutrientAlert: "ಪೋಷಕಾಂಶ ಎಚ್ಚರಿಕೆಗಳು",
    allSupportedLanguages: "ಎಲ್ಲಾ ಬೆಂಬಲಿತ ಭಾಷೆಗಳು",
    languagesUsed: "ಬಳಸಿದ ಭಾಷೆಗಳು",
    predictionTrends: "ಭವಿಷ್ಯವಾಣಿ ಪ್ರವೃತ್ತಿಗಳು",
    analytics: "ವಿಶ್ಲೇಷಣೆ & ಒಳನೋಟಗಳು",
    security: "ಭದ್ರತೆ",
    custom: "ಕಸ್ಟಮ್",
    platform: "ವೇದಿಕೆ",
  },
  ml: {
    cancel: "റദ്ദാക്കുക",
    confirm: "സ്ഥിരീകരിക്കുക",
    email: "ഇമെയിൽ",
    role: "പങ്ക്",
    name: "പേര്",
    search: "തിരയുക",
    deleteUser: "ഉപയോക്താവിനെ ഇല്ലാതാക്കുക",
    deleteUserConfirm: "ശാശ്വതമായി ഇല്ലാതാക്കണോ",
    createUser: "ഉപയോക്താവ് സൃഷ്ടിക്കുക",
    createNewUserAccount: "പുതിയ ഉപയോക്തൃ അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    addNewUser: "പുതിയ ഉപയോക്താവ് ചേർക്കുക",
    totalPredictions: "ആകെ പ്രവചനങ്ങൾ",
    actions: "പ്രവർത്തനങ്ങൾ",
    joined: "ചേർന്നു",
    question: "ചോദ്യം",
    activeUsersToday: "ഇന്ന് സജീവ ഉപയോക്താക്കൾ",
    noPredictionsMadeYet: "ഇതുവരെ പ്രവചനങ്ങൾ നടത്തിയിട്ടില്ല",
    chatbotMonitoring: "ചാറ്റ്ബോട്ട് നിരീക്ഷണം",
    incidents: "സംഭവങ്ങൾ",
    soil: "മണ്ണ് വർഗ്ഗീകരണം",
    nutrientAlert: "പോഷക അലേർട്ടുകൾ",
    allSupportedLanguages: "പിന്തുണയ്ക്കുന്ന എല്ലാ ഭാഷകളും",
    languagesUsed: "ഉപയോഗിച്ച ഭാഷകൾ",
    predictionTrends: "പ്രവചന പ്രവണതകൾ",
    analytics: "വിശകലനം & ഉൾക്കാഴ്ചകൾ",
    security: "സുരക്ഷ",
    custom: "ഇഷ്ടാനുസൃതം",
    platform: "പ്ലാറ്റ്‌ഫോം",
  },
  mr: {
    cancel: "रद्द करा",
    confirm: "पुष्टी करा",
    email: "ईमेल",
    role: "भूमिका",
    name: "नाव",
    search: "शोधा",
    deleteUser: "वापरकर्ता हटवा",
    deleteUserConfirm: "तुम्हाला कायमचे हटवायचे आहे का",
    createUser: "वापरकर्ता तयार करा",
    createNewUserAccount: "नवीन वापरकर्ता खाते तयार करा",
    addNewUser: "नवीन वापरकर्ता जोडा",
    totalPredictions: "एकूण भविष्यवाण्या",
    actions: "क्रिया",
    joined: "सामील झाले",
    question: "प्रश्न",
    activeUsersToday: "आजचे सक्रिय वापरकर्ते",
    noPredictionsMadeYet: "अद्याप कोणत्याही भविष्यवाण्या केल्या नाहीत",
    chatbotMonitoring: "चॅटबॉट निरीक्षण",
    incidents: "घटना",
    soil: "माती वर्गीकरण",
    nutrientAlert: "पोषक तत्व इशारे",
    allSupportedLanguages: "सर्व समर्थित भाषा",
    languagesUsed: "वापरलेल्या भाषा",
    predictionTrends: "भविष्यवाणी कल",
    analytics: "विश्लेषण आणि अंतर्दृष्टी",
    security: "सुरक्षा",
    custom: "सानुकूल",
    platform: "व्यासपीठ",
  },
  gu: {
    cancel: "રદ કરો",
    confirm: "પુષ્ટિ કરો",
    email: "ઇમેઇલ",
    role: "ભૂમિકા",
    name: "નામ",
    search: "શોધો",
    deleteUser: "વપરાશકર્તા કાઢી નાખો",
    deleteUserConfirm: "શું તમે કાયમ માટે કાઢી નાખવા માગો છો",
    createUser: "વપરાશકર્તા બનાવો",
    createNewUserAccount: "નવું વ pporashkarta akhatu banavo",
    addNewUser: "નવો વપરાશકર્તા ઉમેરો",
    totalPredictions: "કુલ આગાહી",
    actions: "ક્રિયાઓ",
    joined: "જોડાયા",
    question: "પ્રશ્ન",
    activeUsersToday: "આજના સક્રિય વpporashkarta",
    noPredictionsMadeYet: "હજી સુધી કોઈ આગાહી કરવામાં આવી નથી",
    chatbotMonitoring: "ચેટબૉટ નિરીક્ષણ",
    incidents: "ઘટનાઓ",
    soil: "માટી વર્ગીકરણ",
    nutrientAlert: "પોષક ચેતવણીઓ",
    allSupportedLanguages: "બધી સમર્થિત ભાષાઓ",
    languagesUsed: "ઉpparayog karela bhasha",
    predictionTrends: "આગાહી વapravrutti",
    analytics: "વipashleshan ane antardrushti",
    security: "સuraksha",
    custom: "kastam",
    platform: "vedhika",
  },
  bn: {
    cancel: "বাতিল করুন",
    confirm: "নিশ্চিত করুন",
    email: "ইমেল",
    role: "ভূমিকা",
    name: "নাম",
    search: "অনুসন্ধান",
    deleteUser: "ব্যবহারকারী মুছুন",
    deleteUserConfirm: "আপনি কি স্থায়ীভাবে মুছতে চান",
    createUser: "ব্যবহারকারী তৈরি করুন",
    createNewUserAccount: "নতুন ব্যবহারকারী অ্যাকাউন্ট তৈরি করুন",
    addNewUser: "নতুন ব্যবহারকারী যোগ করুন",
    totalPredictions: "মোট পূর্বাভাস",
    actions: "কর্ম",
    joined: "যোগ দিয়েছেন",
    question: "প্রশ্ন",
    activeUsersToday: "আজকের সক্রিয় ব্যবহারকারী",
    noPredictionsMadeYet: "এখনো কোনো পূর্বাভাস তৈরি হয়নি",
    chatbotMonitoring: "চ্যাটবট পর্যবেক্ষণ",
    incidents: "ঘটনা",
    soil: "মাটি শ্রেণীবিভাগ",
    nutrientAlert: "পুষ্টি সতর্কতা",
    allSupportedLanguages: "সমস্ত সমর্থিত ভাষা",
    languagesUsed: "ব্যবহৃত ভাষা",
    predictionTrends: "পূর্বাভাস প্রবণতা",
    analytics: "বিশ্লেষণ ও অন্তর্দৃষ্টি",
    security: "নিরাপত্তা",
    custom: "কাস্টম",
    platform: "প্ল্যাটফর্ম",
  },
  pa: {
    cancel: "ਰੱਦ ਕਰੋ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    email: "ਈਮੇਲ",
    role: "ਭੂਮਿਕਾ",
    name: "ਨਾਮ",
    search: "ਖੋਜੋ",
    deleteUser: "ਉਪਭੋਗਤਾ ਮਿਟਾਓ",
    deleteUserConfirm: "ਕੀ ਤੁਸੀਂ ਸਥਾਈ ਤੌਰ 'ਤੇ ਮਿਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ",
    createUser: "ਉਪਭੋਗਤਾ ਬਣਾਓ",
    createNewUserAccount: "ਨਵਾਂ ਉਪਭੋਗਤਾ ਖਾਤਾ ਬਣਾਓ",
    addNewUser: "ਨਵਾਂ ਉਪਭੋਗਤਾ ਜੋੜੋ",
    totalPredictions: "ਕੁੱਲ ਭਵਿੱਖਬਾਣੀਆਂ",
    actions: "ਕਾਰਵਾਈਆਂ",
    joined: "ਸ਼ਾਮਲ ਹੋਏ",
    question: "ਸਵਾਲ",
    activeUsersToday: "ਅੱਜ ਦੇ ਸਰਗਰਮ ਉਪਭੋਗਤਾ",
    noPredictionsMadeYet: "ਅਜੇ ਕੋਈ ਭਵਿੱਖਬਾਣੀ ਨਹੀਂ ਕੀਤੀ ਗਈ",
    chatbotMonitoring: "ਚੈਟਬੋਟ ਨਿਗਰਾਨੀ",
    incidents: "ਘਟਨਾਵਾਂ",
    soil: "ਮਿੱਟੀ ਵਰਗੀਕਰਨ",
    nutrientAlert: "ਪੋਸ਼ਣ ਚੇਤਾਵਨੀਆਂ",
    allSupportedLanguages: "ਸਾਰੀਆਂ ਸਮਰਥਿਤ ਭਾਸ਼ਾਵਾਂ",
    languagesUsed: "ਵਰਤੀਆਂ ਗਈਆਂ ਭਾਸ਼ਾਵਾਂ",
    predictionTrends: "ਭਵਿੱਖਬਾਣੀ ਰੁਝਾਨ",
    analytics: "ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਜਾਣਕਾਰੀ",
    security: "ਸੁਰੱਖਿਆ",
    custom: "ਕਸਟਮ",
    platform: "ਪਲੇਟਫਾਰਮ",
  },
  or: {
    cancel: "ବାତିଲ କରନ୍ତୁ",
    confirm: "ନିଶ୍ଚିତ କରନ୍ତୁ",
    email: "ଇମେଲ",
    role: "ଭୂମିକା",
    name: "ନାମ",
    search: "ଖୋଜନ୍ତୁ",
    deleteUser: "ଉପଭୋକ୍ତା ଡିଲିଟ କରନ୍ତୁ",
    deleteUserConfirm: "ଆପଣ ସ୍ଥାୟୀ ଭାବେ ଡିଲିଟ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି",
    createUser: "ଉପଭୋକ୍ତା ସୃଷ୍ଟି କରନ୍ତୁ",
    createNewUserAccount: "ନୂଆ ଉପଭୋକ୍ତା ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ",
    addNewUser: "ନୂଆ ଉପଭୋକ୍ତା ଯୋଡ଼ନ୍ତୁ",
    totalPredictions: "ମୋଟ ପୂର୍ବାନୁମାନ",
    actions: "କ୍ରିୟା",
    joined: "ଯୋଗ ଦେଇଛନ୍ତି",
    question: "ପ୍ରଶ୍ନ",
    activeUsersToday: "ଆଜିର ସକ୍ରିୟ ଉପଭୋକ୍ତା",
    noPredictionsMadeYet: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପୂର୍ବାନୁମାନ ହୋଇନାହିଁ",
    chatbotMonitoring: "ଚ୍ୟାଟବଟ ଅନୁଶୀଳନ",
    incidents: "ଘଟଣା",
    soil: "ମାଟି ବର୍ଗୀକରଣ",
    nutrientAlert: "ପୋଷଣ ସତର୍କତା",
    allSupportedLanguages: "ସମସ୍ତ ସମର୍ଥିତ ଭାଷା",
    languagesUsed: "ବ୍ୟବହୃତ ଭାଷା",
    predictionTrends: "ପୂର୍ବାନୁମାନ ଧାରା",
    analytics: "ବିଶ୍ଳେଷଣ ଓ ଅନ୍ତର୍ଦୃଷ୍ଟି",
    security: "ସୁରକ୍ଷା",
    custom: "ଅନୁକୂଳ",
    platform: "ପ୍ଲାଟଫର୍ମ",
  },
  as: {
    cancel: "বাতিল কৰক",
    confirm: "নিশ্চিত কৰক",
    email: "ইমেইল",
    role: "ভূমিকা",
    name: "নাম",
    search: "বিচাৰক",
    deleteUser: "ব্যৱহাৰকাৰী মচক",
    deleteUserConfirm: "আপুনি স্থায়ীভাৱে মচিব বিচাৰিছে নেকি",
    createUser: "ব্যৱহাৰকাৰী সৃষ্টি কৰক",
    createNewUserAccount: "নতুন ব্যৱহাৰকাৰী একাউণ্ট সৃষ্টি কৰক",
    addNewUser: "নতুন ব্যৱহাৰকাৰী যোগ কৰক",
    totalPredictions: "মুঠ পূৰ্বানুমান",
    actions: "কাৰ্য",
    joined: "যোগ দিলে",
    question: "প্ৰশ্ন",
    activeUsersToday: "আজিৰ সক্ৰিয় ব্যৱহাৰকাৰী",
    noPredictionsMadeYet: "এতিয়াও কোনো পূৰ্বানুমান কৰা হোৱা নাই",
    chatbotMonitoring: "চেটবট পৰিবীক্ষণ",
    incidents: "ঘটনা",
    soil: "মাটি শ্ৰেণীবিভাজন",
    nutrientAlert: "পুষ্টি সতৰ্কবাৰ্তা",
    allSupportedLanguages: "সকলো সমৰ্থিত ভাষা",
    languagesUsed: "ব্যৱহৃত ভাষা",
    predictionTrends: "পূৰ্বানুমানৰ ধাৰা",
    analytics: "বিশ্লেষণ আৰু অন্তৰ্দৃষ্টি",
    security: "সুৰক্ষা",
    custom: "কাষ্টম",
    platform: "প্লেটফৰ্ম",
  },
  ur: {
    cancel: "منسوخ کریں",
    confirm: "تصدیق کریں",
    email: "ای میل",
    role: "کردار",
    name: "نام",
    search: "تلاش کریں",
    deleteUser: "صارف حذف کریں",
    deleteUserConfirm: "کیا آپ مستقل طور پر حذف کرنا چاہتے ہیں",
    createUser: "صارف بنائیں",
    createNewUserAccount: "نیا صارف اکاؤنٹ بنائیں",
    addNewUser: "نیا صارف شامل کریں",
    totalPredictions: "کل پیش گوئیاں",
    actions: "اقدامات",
    joined: "شامل ہوئے",
    question: "سوال",
    activeUsersToday: "آج کے فعال صارفین",
    noPredictionsMadeYet: "ابھی تک کوئی پیش گوئی نہیں کی گئی",
    chatbotMonitoring: "چیٹ بوٹ نگرانی",
    incidents: "واقعات",
    soil: "مٹی کی درجہ بندی",
    nutrientAlert: "غذائی اجزاء کے انتباہات",
    allSupportedLanguages: "تمام معاون زبانیں",
    languagesUsed: "استعمال شدہ زبانیں",
    predictionTrends: "پیش گوئی کے رجحانات",
    analytics: "تجزیات اور بصیرت",
    security: "سیکیورٹی",
    custom: "کسٹم",
    platform: "پلیٹ فارم",
  },
  mai: {
    cancel: "रद्द करू",
    confirm: "पुष्टि करू",
    email: "ईमेल",
    role: "भूमिका",
    name: "नाम",
    search: "खोजू",
    deleteUser: "उपयोगकर्ता हटाबू",
    deleteUserConfirm: "की अहाँ स्थायी रूप सँ हटाय चाहैत छी",
    createUser: "उपयोगकर्ता बनाबू",
    createNewUserAccount: "नव उपयोगकर्ता खाता बनाबू",
    addNewUser: "नव उपयोगकर्ता जोड़ू",
    totalPredictions: "कुल भविष्यवाणी",
    actions: "कार्रवाई",
    joined: "सम्मिलित भेलाह",
    question: "प्रश्न",
    activeUsersToday: "आइक सक्रिय उपयोगकर्ता",
    noPredictionsMadeYet: "आइ धरि कोनो भविष्यवाणी नहि कयल गेल",
    chatbotMonitoring: "चैटबॉट निगरानी",
    incidents: "घटना",
    soil: "माटि वर्गीकरण",
    nutrientAlert: "पोषक तत्व चेतावनी",
    allSupportedLanguages: "सभ समर्थित भाषा",
    languagesUsed: "प्रयुक्त भाषा",
    predictionTrends: "भविष्यवाणी रुझान",
    analytics: "विश्लेषण आ अंतर्दृष्टि",
    security: "सुरक्षा",
    custom: "कस्टम",
    platform: "मंच",
  },
  mni: {
    cancel: "থाংবা লৌনবিরু",
    confirm: "থৌনা তৌবিযু",
    email: "ইমেইল",
    role: "মরুপ",
    name: "মিং",
    search: "থীনবা",
    deleteUser: "ইউজর শাফবিরু",
    deleteUserConfirm: "নৌপাক্না শাফবিগদবা লৌরিনো",
    createUser: "ইউজর তৌবিযু",
    createNewUserAccount: "নতুন ইউজর একাউন্ট তৌবিযু",
    addNewUser: "নতুন ইউজর চংলগবিযু",
    totalPredictions: "ফোংদোক্লিবা তোতাল",
    actions: "তৌনবা",
    joined: "চংলগাই",
    question: "হোৎনবা",
    activeUsersToday: "নুমিত্তা হন্না হেক্চরোইবা ইউজরশিং",
    noPredictionsMadeYet: "অদোমগি লৈখিদ্রবা তোতাল ফোংদোক্লে",
    chatbotMonitoring: "চেটবট মনিটরিং",
    incidents: "ওইবশিং",
    soil: "লম ক্লাসিফিকেশন",
    nutrientAlert: "নিউট্রিয়েন্ট এলর্ট",
    allSupportedLanguages: "সাপোর্ত তৌবা লৈবাকপোকশিং মরুপশিং",
    languagesUsed: "শীজিন্নবা লৈবাকপোকশিং",
    predictionTrends: "ফোংদোক্লিবা ট্রেন্দশিং",
    analytics: "এনালিটিক্স অমসুং ইনসাইটশিং",
    security: "সিকিউরিটি",
    custom: "কস্টম",
    platform: "প্লেটফোর্ম",
  },
  sat: {
    cancel: "ᱨᱚᱫᱽ ᱢᱮᱱ",
    confirm: "ᱵᱷᱨᱚᱥᱟ ᱢᱮᱱ",
    email: "ᱤᱢᱮᱞ",
    role: "ᱢᱤᱫ",
    name: "ᱯᱤᱨᱛᱟᱹ",
    search: "ᱧᱮᱞ ᱢᱮᱱ",
    deleteUser: "ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱫᱩᱲ ᱢᱮᱱ",
    deleteUserConfirm: "ᱱᱤᱛᱚᱜ ᱫᱩᱲ ᱢᱮᱱᱟ",
    createUser: "ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱛᱮᱦᱮᱱ ᱢᱮᱱ",
    createNewUserAccount: "ᱱᱟᱡᱚᱢ ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱠᱷᱟᱹᱛᱟ",
    addNewUser: "ᱱᱟᱡᱚᱢ ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ ᱡᱚᱲ ᱢᱮᱱ",
    totalPredictions: "ᱦᱤᱡᱩᱜ ᱯᱽᱨᱤᱫᱤᱠᱥᱚᱱ",
    actions: "ᱠᱟᱹᱢᱤ",
    joined: "ᱡᱚᱲ ᱟᱠᱟᱱ",
    question: "ᱚᱴᱟᱝ",
    activeUsersToday: "ᱟᱲᱟᱢ ᱵᱮᱵᱷᱟᱨᱤᱭᱟᱹ",
    noPredictionsMadeYet: "ᱯᱽᱨᱤᱫᱤᱠᱥᱚᱱ ᱦᱤᱡᱩᱜ ᱵᱟᱹᱧᱩᱜ ᱵᱟ",
    chatbotMonitoring: "ᱪᱮᱴᱵᱚᱴ ᱢᱩᱱᱤᱴᱚᱨᱤᱝ",
    incidents: "ᱨᱮᱫ ᱮᱛᱚᱜ",
    soil: "ᱡᱚᱢ ᱠᱞᱟᱥᱤᱯᱷᱤᱠᱮᱥᱚᱱ",
    nutrientAlert: "ᱯᱩᱥᱴᱤ ᱩᱰᱳᱜ",
    allSupportedLanguages: "ᱦᱤᱡᱩᱜ ᱥᱟᱯᱚᱨᱴᱮᱫ ᱯᱷᱟᱥᱟ",
    languagesUsed: "ᱵᱮᱵᱷᱟᱨ ᱟᱠᱟᱱ ᱯᱷᱟᱥᱟ",
    predictionTrends: "ᱯᱽᱨᱤᱫᱤᱠᱥᱚᱱ ᱛᱽᱨᱮᱱᱫ",
    analytics: "ᱟᱱᱟᱞᱤᱴᱤᱠᱥ",
    security: "ᱥᱤᱠᱤᱭᱩᱨᱤᱴᱤ",
    custom: "ᱠᱟᱥᱴᱚᱢ",
    platform: "ᱯᱞᱮᱴᱯᱷᱚᱨᱢ",
  },
  brx: {
    cancel: "रद्द दा",
    confirm: "थिरसिन",
    email: "इमेल",
    role: "जिउ",
    name: "मुं",
    search: "फिस",
    deleteUser: "बिबां डिलिट कर",
    deleteUserConfirm: "निगोन डिलिट खालाम बाय",
    createUser: "बिबां थाव",
    createNewUserAccount: "नुवां बिबां एकाउन्ट",
    addNewUser: "नुवां बिबां दाव",
    totalPredictions: "राव प्रिडिक्सन",
    actions: "खोमा",
    joined: "गोनां जादों",
    question: "थुं",
    activeUsersToday: "मदाय अखाबाय बिबां",
    noPredictionsMadeYet: "जाय प्रिडिक्सन मोनो",
    chatbotMonitoring: "चेटबट मनिटर",
    incidents: "गैया",
    soil: "मावखुं क्लासिफि",
    nutrientAlert: "पोशक अलर्ट",
    allSupportedLanguages: "राव भास",
    languagesUsed: "बिगोन भास",
    predictionTrends: "प्रिडिक्सन ट्रेन्द",
    analytics: "एनालिटिक्स",
    security: "सिकिउरिटि",
    custom: "कस्टम",
    platform: "प्लेटफर्म",
  },
  doi: {
    cancel: "रद्द कर",
    confirm: "पक्का कर",
    email: "ईमेल",
    role: "भूमिका",
    name: "नां",
    search: "लबो",
    deleteUser: "बरतनौआ मिटाओ",
    deleteUserConfirm: "क्या तुस हमेशा लेई मिटाना चांदे ओ",
    createUser: "बरतनौआ बनाओ",
    createNewUserAccount: "नवां बरतनौआ खाता बनाओ",
    addNewUser: "नवां बरतनौआ जोड़ो",
    totalPredictions: "कुल भविष्यवाणी",
    actions: "कार्रवाई",
    joined: "सम्मिलित होए",
    question: "सवाल",
    activeUsersToday: "अज्ज दे सक्रिय बरतनौआ",
    noPredictionsMadeYet: "अजे तक्क कोई भविष्यवाणी नेईं कीती गेई",
    chatbotMonitoring: "चैटबोट निगरानी",
    incidents: "घटनाएं",
    soil: "मिट्टी वर्गीकरण",
    nutrientAlert: "पोषक चेतावनी",
    allSupportedLanguages: "सारे समर्थित बोलियां",
    languagesUsed: "बरती गेई बोलियां",
    predictionTrends: "भविष्यवाणी रुझान",
    analytics: "विश्लेषण ते अंतर्दृष्टि",
    security: "सुरक्षा",
    custom: "कस्टम",
    platform: "मंच",
  },
  ks: {
    cancel: "منسوٗخ کریو",
    confirm: "یقیٖن کریو",
    email: "اِیمیل",
    role: "کِردار",
    name: "ناو",
    search: "لَلُن",
    deleteUser: "یوٗزَر مِٹاوو",
    deleteUserConfirm: "کیا اَپ مَستقِل مِٹاونا چاہانِواے",
    createUser: "یوٗزَر بناوو",
    createNewUserAccount: "نَو یوٗزَر اکاؤنٹ بناوو",
    addNewUser: "نَو یوٗزَر شامِل کریو",
    totalPredictions: "کُل پیش گوئی",
    actions: "اِقدامات",
    joined: "شامِل بٲوو",
    question: "سوال",
    activeUsersToday: "آج کیتھِ فَعال یوٗزَر",
    noPredictionsMadeYet: "اَبی تٔک کوئی پیش گوئی نہ بٲوی",
    chatbotMonitoring: "چیٹ بٲٹ نِگرانی",
    incidents: "واقِعات",
    soil: "مَٹی درجہ بَندی",
    nutrientAlert: "غِذائی اَنتبَاہ",
    allSupportedLanguages: "سارِتھ زَبانَن",
    languagesUsed: "اِستِعمال کَرمُت زَبانَن",
    predictionTrends: "پیش گوئی رُجحانات",
    analytics: "تَجزِیاتی",
    security: "سیکِیورِٹی",
    custom: "کَسٹَم",
    platform: "پلیٹ فارم",
  },
  kok: {
    cancel: "रद्द करचें",
    confirm: "खात्री करचें",
    email: "ईमेल",
    role: "भुमिका",
    name: "नांव",
    search: "सोदचें",
    deleteUser: "उपयोगकर्तो काडचो",
    deleteUserConfirm: "तुमकां कायमचें काडूंक जाय काय",
    createUser: "उपयोगकर्तो तयार करचो",
    createNewUserAccount: "नवो उपयोगकर्तो खातो तयार करचो",
    addNewUser: "नवो उपयोगकर्तो घालचो",
    totalPredictions: "एकूण अंदाज",
    actions: "क्रिया",
    joined: "जोडले",
    question: "प्रश्न",
    activeUsersToday: "आयज सक्रिय उपयोगकर्ते",
    noPredictionsMadeYet: "अजून कसलेच अंदाज केले नाहीत",
    chatbotMonitoring: "चॅटबोट देखरेख",
    incidents: "घडणुको",
    soil: "माती वर्गीकरण",
    nutrientAlert: "पोषण ताकीद",
    allSupportedLanguages: "सगळ्यो समर्थित भाशो",
    languagesUsed: "वापरिल्लो भाशो",
    predictionTrends: "अंदाज प्रवाह",
    analytics: "विश्लेषण आनी अंतर्दृष्टी",
    security: "सुरक्षा",
    custom: "कस्टम",
    platform: "व्यासपीठ",
  },
  ne: {
    cancel: "रद्द गर्नुहोस्",
    confirm: "पुष्टि गर्नुहोस्",
    email: "इमेल",
    role: "भूमिका",
    name: "नाम",
    search: "खोज्नुहोस्",
    deleteUser: "प्रयोगकर्ता मेटाउनुहोस्",
    deleteUserConfirm: "के तपाईं स्थायी रूपमा मेटाउन चाहनुहुन्छ",
    createUser: "प्रयोगकर्ता बनाउनुहोस्",
    createNewUserAccount: "नयाँ प्रयोगकर्ता खाता बनाउनुहोस्",
    addNewUser: "नयाँ प्रयोगकर्ता थप्नुहोस्",
    totalPredictions: "कुल भविष्यवाणीहरू",
    actions: "कार्यहरू",
    joined: "सामेल भए",
    question: "प्रश्न",
    activeUsersToday: "आजका सक्रिय प्रयोगकर्ता",
    noPredictionsMadeYet: "अझै कुनै भविष्यवाणी गरिएको छैन",
    chatbotMonitoring: "च्याटबोट अनुगमन",
    incidents: "घटनाहरू",
    soil: "माटो वर्गीकरण",
    nutrientAlert: "पोषक तत्व चेतावनी",
    allSupportedLanguages: "सबै समर्थित भाषाहरू",
    languagesUsed: "प्रयोग गरिएका भाषाहरू",
    predictionTrends: "भविष्यवाणी प्रवृत्ति",
    analytics: "विश्लेषण र अन्तर्दृष्टि",
    security: "सुरक्षा",
    custom: "कस्टम",
    platform: "मञ्च",
  },
  sa: {
    cancel: "निरस्तं करोतु",
    confirm: "पुष्टिं करोतु",
    email: "विद्युत्-पत्रम्",
    role: "पात्रम्",
    name: "नाम",
    search: "अन्विष्यतु",
    deleteUser: "उपयोक्तारं नाशयतु",
    deleteUserConfirm: "किं भवान् स्थायिरूपेण नाशयितुम् इच्छति",
    createUser: "उपयोक्तारं निर्मातु",
    createNewUserAccount: "नवम् उपयोक्तृ-खातं निर्मातु",
    addNewUser: "नवम् उपयोक्तारं योजयतु",
    totalPredictions: "सर्वे पूर्वानुमानाः",
    actions: "क्रियाः",
    joined: "सम्मिलितः जातः",
    question: "प्रश्नः",
    activeUsersToday: "अद्यतनाः सक्रियाः उपयोक्तारः",
    noPredictionsMadeYet: "अद्यापि न कोऽपि पूर्वानुमानः कृतः",
    chatbotMonitoring: "चाटबॉट अनुवीक्षणम्",
    incidents: "घटनाः",
    soil: "भूमिः वर्गीकरणम्",
    nutrientAlert: "पोषक-चेतावनी",
    allSupportedLanguages: "सर्वाः समर्थिताः भाषाः",
    languagesUsed: "प्रयुक्ताः भाषाः",
    predictionTrends: "पूर्वानुमान-प्रवृत्तयः",
    analytics: "विश्लेषणम् अन्तर्दृष्टिः च",
    security: "सुरक्षा",
    custom: "अनुकूलम्",
    platform: "वेदिका",
  },
  sd: {
    cancel: "رد ڪريو",
    confirm: "تصديق ڪريو",
    email: "اي ميل",
    role: "ڪردار",
    name: "نالو",
    search: "ڳوليو",
    deleteUser: "استعمالڪار ختم ڪريو",
    deleteUserConfirm: "ڇا توهان هميشه لاءِ ختم ڪرڻ چاهيو ٿا",
    createUser: "استعمالڪار ٺاهيو",
    createNewUserAccount: "نئون استعمالڪار کاتو ٺاهيو",
    addNewUser: "نئون استعمالڪار شامل ڪريو",
    totalPredictions: "ڪل اڳڪٿائيون",
    actions: "عمل",
    joined: "شامل ٿيو",
    question: "سوال",
    activeUsersToday: "اڄ جا فعال استعمالڪار",
    noPredictionsMadeYet: "اڃا تائين ڪا به اڳڪٿائي نه ڪئي وئي",
    chatbotMonitoring: "چيٽ بوٽ نگراني",
    incidents: "واقعا",
    soil: "مٽي جي درجابندي",
    nutrientAlert: "غذائي اطلاع",
    allSupportedLanguages: "سڀ سپورٽ ٿيل ٻوليون",
    languagesUsed: "استعمال ٿيل ٻوليون",
    predictionTrends: "اڳڪٿائي جا رجحان",
    analytics: "تجزيو ۽ بصيرت",
    security: "سيڪيورٽي",
    custom: "ڪسٽم",
    platform: "پليٽ فارم",
  },
};

// For each language, insert new keys before the closing `},` of that language section
for (const [lang, keys] of Object.entries(additions)) {
  // Find the language section ending - pattern: noFeedbackMatches key followed by closing },
  const langSectionEnd = `    "noFeedbackMatches": `;
  const langMarker = `  "${lang}": {`;

  // Find start of this language section
  const langStart = content.indexOf(langMarker);
  if (langStart === -1) {
    console.log(`WARNING: Language section '${lang}' not found!`);
    continue;
  }

  // Find the noFeedbackMatches line within this language section
  const searchFrom = langStart;
  const noFeedbackIdx = content.indexOf(langSectionEnd, searchFrom);
  if (noFeedbackIdx === -1) {
    console.log(`WARNING: Could not find noFeedbackMatches in '${lang}' section!`);
    continue;
  }

  // Find the end of the noFeedbackMatches line
  const lineEnd = content.indexOf('\n', noFeedbackIdx);
  if (lineEnd === -1) {
    console.log(`WARNING: Could not find line end in '${lang}' section!`);
    continue;
  }

  // Build insert string
  const insertLines = Object.entries(keys).map(([key, val]) => {
    // Escape double quotes in value
    const escaped = val.replace(/"/g, '\\"');
    return `    "${key}": "${escaped}",`;
  }).join('\n');

  // Insert after the noFeedbackMatches line
  content = content.slice(0, lineEnd + 1) + insertLines + '\n' + content.slice(lineEnd + 1);
  console.log(`Added ${Object.keys(keys).length} keys to '${lang}' section`);
}

writeFileSync(filePath, content, 'utf8');
console.log('\nDone! adminTranslations.ts updated.');
