"""add user profile fields

Revision ID: 1d660cc6b2c0
Revises: 6edee386f98f
Create Date: 2026-07-31 18:43:32.820023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d660cc6b2c0'
down_revision: Union[str, Sequence[str], None] = '6edee386f98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='farmer', nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('region', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_users_region'), 'users', ['region'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_region'), table_name='users')
    op.drop_column('users', 'region')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
