export const LANGUAGE_MAP: Record<string, string> = {
  english: 'en',
  en: 'en',
  'en-in': 'en',
  hindi: 'hi',
  hi: 'hi',
  'hi-in': 'hi',
  'हिंदी': 'hi',
  telugu: 'te',
  te: 'te',
  'te-in': 'te',
  'తెలుగు': 'te',
  tamil: 'ta',
  ta: 'ta',
  'ta-in': 'ta',
  'தமிழ்': 'ta',
  kannada: 'kn',
  kn: 'kn',
  'kn-in': 'kn',
  'ಕನ್ನಡ': 'kn',
  malayalam: 'ml',
  ml: 'ml',
  'ml-in': 'ml',
  'മലയാളം': 'ml',
  marathi: 'mr',
  mr: 'mr',
  'mr-in': 'mr',
  'मराठी': 'mr',
  bengali: 'bn',
  bn: 'bn',
  'bn-in': 'bn',
  'বাংলা': 'bn',
  gujarati: 'gu',
  gu: 'gu',
  'gu-in': 'gu',
  'ગુજરાતી': 'gu',
  punjabi: 'pa',
  pa: 'pa',
  'pa-in': 'pa',
  'ਪੰਜਾਬੀ': 'pa',
  odia: 'or',
  or: 'or',
  'or-in': 'or',
  'ଓଡ଼ିଆ': 'or',
  assamese: 'as',
  as: 'as',
  'as-in': 'as',
  'অসমীয়া': 'as',
  urdu: 'ur',
  ur: 'ur',
  'ur-in': 'ur',
  'اردو': 'ur',
  maithili: 'mai',
  mai: 'mai',
  'mai-in': 'mai',
  manipuri: 'mni',
  mni: 'mni',
  'mni-in': 'mni',
  santali: 'sat',
  sat: 'sat',
  'sat-in': 'sat',
  bodo: 'brx',
  brx: 'brx',
  'brx-in': 'brx',
  dogri: 'doi',
  doi: 'doi',
  'doi-in': 'doi',
  kashmiri: 'ks',
  ks: 'ks',
  'ks-in': 'ks',
  konkani: 'kok',
  kok: 'kok',
  'kok-in': 'kok',
  nepali: 'ne',
  ne: 'ne',
  'ne-in': 'ne',
  sanskrit: 'sa',
  sa: 'sa',
  'sa-in': 'sa',
  sindhi: 'sd',
  sd: 'sd',
  'sd-in': 'sd',
}

export function normalizeLanguageCode(lang: string | undefined | null): string {
  if (!lang || typeof lang !== 'string') return 'en'
  const clean = lang.trim().toLowerCase()
  if (LANGUAGE_MAP[clean]) {
    return LANGUAGE_MAP[clean]
  }
  const firstPart = clean.split(/[-_\s]/)[0]
  if (LANGUAGE_MAP[firstPart]) {
    return LANGUAGE_MAP[firstPart]
  }
  return 'en'
}
