/**
 * PDF Report Generator matching the exact 4-page AgroAI Agronomic Advisory layout.
 */


export interface ReportData {
  reportId?: string
  userName?: string
  generatedOn?: string
  soilType?: string
  confidence?: number
  soilImage?: string
  probabilities?: Record<string, number>
  soilHealthScore?: number
  soilHealthStatus?: string
  location?: string
  temperature?: string
  humidity?: string
  rainfall?: string
  windSpeed?: string
  weatherCondition?: string
  N?: number
  P?: number
  K?: number
  ph?: number
  oc?: number
  ec?: number
  nValue?: string
  pValue?: string
  kValue?: string
  phValue?: string
  ocValue?: string
  ecValue?: string
  topCrop?: string
  topCropScore?: number
  recommendations?: any
  crops?: Array<{ rank: string; name: string; score: number; match: string; insight: string }>
  fertilizers?: Array<{ category: string; product: string; dosage: string; method: string }>
  advisoryNotes?: string[]
}

const PDF_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    "Report ID": "Report ID",
    "Prepared For": "Prepared For",
    "Generated On": "Generated On",
    "EXECUTIVE AGRONOMIC SUMMARY": "EXECUTIVE AGRONOMIC SUMMARY",
    "Soil Classified": "Soil Classified",
    "Soil Health": "Soil Health",
    "Top Recommended Crop": "Top Recommended Crop",
    "Field Location": "Field Location",
    "Nutrient Alert": "Nutrient Alert",
    "Immediate Action": "Immediate Action",
    "Soil Classification — AI Analysis Result": "Soil Classification — AI Analysis Result",
    "Predicted Soil Class": "Predicted Soil Class",
    "Soil Fertility": "Soil Fertility",
    "Characteristics": "Characteristics",
    "Soil Classification Probability Distribution:": "Soil Classification Probability Distribution:",
    "Alluvial Soil": "Alluvial Soil",
    "Loamy Soil": "Loamy Soil",
    "Silt Soil": "Silt Soil",
    "Sandy Soil": "Sandy Soil",
    "Red Soil": "Red Soil",
    "Black Soil": "Black Soil",
    "Clay Soil": "Clay Soil",
    "Unknown Soil": "Unknown Soil",
    "Valued Farmer": "Valued Farmer",
    "Optimal": "Optimal",
    "Moderate": "Moderate",
    "Low": "Low",
    "Low (Deficient)": "Low (Deficient)",
    "Optimal (Adequate)": "Optimal (Adequate)",
    "Parameter": "Parameter",
    "Measured Value": "Measured Value",
    "Unit": "Unit",
    "Agronomic Status": "Agronomic Status",
    "Soil pH": "Soil pH",
    "Nitrogen (N)": "Nitrogen (N)",
    "Phosphorus (P)": "Phosphorus (P)",
    "Potassium (K)": "Potassium (K)",
    "Organic Carbon (OC)": "Organic Carbon (OC)",
    "Electrical Conductivity (EC)": "Electrical Conductivity (EC)",
    "Weather & Meteorological Context": "Weather & Meteorological Context",
    "Observed Weather": "Observed Weather",
    "Temperature": "Temperature",
    "Humidity": "Humidity",
    "Rainfall": "Rainfall",
    "Wind Speed": "Wind Speed",
    "Condition": "Condition",
    "Agronomic Implications": "Agronomic Implications",
    "Hyperlocal weather matches expected growing conditions. No immediate alerts.": "Hyperlocal weather matches expected growing conditions. No immediate alerts.",
    "Crop Suitability & Yield Optimization": "Crop Suitability & Yield Optimization",
    "Rank": "Rank",
    "Crop Name": "Crop Name",
    "Match Score": "Match Score",
    "Suitability Index": "Suitability Index",
    "Agronomic Insight": "Agronomic Insight",
    "Fertilizer Advisory & Nutrient Management": "Fertilizer Advisory & Nutrient Management",
    "Nutrient Target": "Nutrient Target",
    "Recommended Fertilizer Product": "Recommended Fertilizer Product",
    "Optimal Dosage": "Optimal Dosage",
    "Application Method": "Application Method",
    "General Agronomic Advisory Notes": "General Agronomic Advisory Notes",
    "Disclaimer": "Disclaimer: This report is generated by AgroAI for advisory purposes only. Always consult a certified agronomist.",
    "Report ready": "Report ready",
    "Basal Application Note": "Apply MOP (50 kg/acre) and DAP (40 kg/acre) as basal dose before sowing.",
    "Phosphorus, Potassium": "Phosphorus, Potassium",
    "Infertile / Moderate": "Infertile / Moderate",
    "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.": "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.",
    "Cotton": "Cotton",
    "Soybean": "Soybean",
    "Maize": "Maize",
    "Groundnut": "Groundnut",
    "Jowar": "Jowar",
    "Wheat": "Wheat",
    "Sugarcane": "Sugarcane",
    "Excellent Match": "Excellent Match",
    "Very Good Match": "Very Good Match",
    "Good Match": "Good Match",
    "Moderate Match": "Moderate Match",
    "Suitable Match": "Suitable Match",
    "Urea": "Urea",
    "DAP": "DAP",
    "MOP": "MOP",
    "Potassium Supplement": "Potassium Supplement",
    "MOP (Muriate of Potash)": "MOP (Muriate of Potash)",
    "Phosphorus Supplement": "Phosphorus Supplement",
    "DAP (Di-ammonium Phosphate)": "DAP (Di-ammonium Phosphate)",
    "Nitrogen Supplement": "Nitrogen Supplement",
    "Urea (46% N)": "Urea (46% N)",
    "Organic Manure": "Organic Manure",
    "Farm Yard Manure (FYM) / Compost": "Farm Yard Manure (FYM) / Compost",
    "Basal — at sowing": "Basal — at sowing",
    "Top dressing — 2 split doses": "Top dressing — 2 split doses",
    "Incorporate 15 days before sowing": "Incorporate 15 days before sowing"
  },
  hi: {
    "Report ID": "रिपोर्ट आईडी",
    "Prepared For": "तैयार किया गया",
    "Generated On": "उत्पन्न तिथि",
    "EXECUTIVE AGRONOMIC SUMMARY": "कार्यकारी कृषि सारांश",
    "Soil Classified": "मिट्टी का वर्गीकरण",
    "Soil Health": "मिट्टी का स्वास्थ्य",
    "Top Recommended Crop": "शीर्ष अनुशंसित फसल",
    "Field Location": "खेत का स्थान",
    "Nutrient Alert": "पोषक तत्व चेतावनी",
    "Immediate Action": "तत्काल कार्रवाई",
    "Soil Classification — AI Analysis Result": "मिट्टी वर्गीकरण — एआई विश्लेषण परिणाम",
    "Predicted Soil Class": "पूर्वानुमानित मिट्टी वर्ग",
    "Soil Fertility": "मिट्टी की उर्वरता",
    "Characteristics": "विशेषताएं",
    "Soil Classification Probability Distribution:": "मिट्टी वर्गीकरण संभाव्यता वितरण:",
    "Alluvial Soil": "जलोढ़ मिट्टी",
    "Loamy Soil": "दोमट मिट्टी",
    "Silt Soil": "गाद मिट्टी",
    "Sandy Soil": "रेतीली मिट्टी",
    "Red Soil": "लाल मिट्टी",
    "Black Soil": "काली मिट्टी",
    "Clay Soil": "चिकनी मिट्टी",
    "Unknown Soil": "अज्ञात मिट्टी",
    "Valued Farmer": "प्रिय किसान",
    "Optimal": "इष्टतम",
    "Moderate": "मध्यम",
    "Low": "कम",
    "Low (Deficient)": "कम (कमी)",
    "Optimal (Adequate)": "इष्टतम (पर्याप्त)",
    "Parameter": "पैरामीटर",
    "Measured Value": "मापा गया मूल्य",
    "Unit": "इकाई",
    "Agronomic Status": "कृषि स्थिति",
    "Soil pH": "मिट्टी का पीएच",
    "Nitrogen (N)": "नाइट्रोजन (N)",
    "Phosphorus (P)": "फास्फोरस (P)",
    "Potassium (K)": "पोटेशियम (K)",
    "Organic Carbon (OC)": "ऑर्गेनिक कार्बन (OC)",
    "Electrical Conductivity (EC)": "विद्युत चालकता (EC)",
    "Weather & Meteorological Context": "मौसम और मौसम संबंधी संदर्भ",
    "Observed Weather": "देखा गया मौसम",
    "Temperature": "तापमान",
    "Humidity": "आर्द्रता",
    "Rainfall": "वर्षा",
    "Wind Speed": "हवा की गति",
    "Condition": "स्थिति",
    "Agronomic Implications": "कृषि प्रभाव",
    "Hyperlocal weather matches expected growing conditions. No immediate alerts.": "हाइपरलोकल मौसम अपेक्षित बढ़ती परिस्थितियों से मेल खाता है। कोई तत्काल अलर्ट नहीं।",
    "Crop Suitability & Yield Optimization": "फसल उपयुक्तता और उपज अनुकूलन",
    "Rank": "रैंक",
    "Crop Name": "फसल का नाम",
    "Match Score": "मैच स्कोर",
    "Suitability Index": "उपयुक्तता सूचकांक",
    "Agronomic Insight": "कृषि अंतर्दृष्टि",
    "Fertilizer Advisory & Nutrient Management": "उर्वरक सलाह और पोषक तत्व प्रबंधन",
    "Nutrient Target": "पोषक तत्व लक्ष्य",
    "Recommended Fertilizer Product": "अनुशंसित उर्वरक उत्पाद",
    "Optimal Dosage": "इष्टतम खुराक",
    "Application Method": "आवेदन की विधि",
    "General Agronomic Advisory Notes": "सामान्य कृषि सलाहकार नोट्स",
    "Disclaimer": "अस्वीकरण: यह रिपोर्ट केवल सलाहकार उद्देश्यों के लिए एग्रोएआई द्वारा उत्पन्न की गई है। हमेशा एक प्रमाणित कृषिविद् से परामर्श लें।",
    "Report ready": "रिपोर्ट तैयार है",
    "Basal Application Note": "बुवाई से पहले बेसल खुराक के रूप में एमओपी (50 किग्रा/एकड़) और डीएपी (40 किग्रा/एकड़) लागू करें।",
    "Phosphorus, Potassium": "फास्फोरस, पोटेशियम",
    "Infertile / Moderate": "अनुर्वर / मध्यम",
    "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.": "चिकनी मिट्टी की संरचना, उच्च नमी प्रतिधारण, आदर्श उद्धरण-विनिमय — गहरी जड़ वाली नकदी फसलों के लिए उपयुक्त है।",
    "Cotton": "कपास",
    "Soybean": "सोयाबीन",
    "Maize": "मक्का",
    "Groundnut": "मूंगफली",
    "Jowar": "ज्वार",
    "Wheat": "गेहूं",
    "Sugarcane": "गन्ना",
    "Excellent Match": "उत्कृष्ट मैच",
    "Very Good Match": "बहुत अच्छा मैच",
    "Good Match": "अच्छा मैच",
    "Moderate Match": "मध्यम मैच",
    "Suitable Match": "उपयुक्त मैच",
    "Urea": "यूरिया",
    "DAP": "डीएपी",
    "MOP": "एमओपी",
    "Potassium Supplement": "पोटेशियम अनुपूरक",
    "MOP (Muriate of Potash)": "एमओपी (पोटेशियम म्यूरिएट)",
    "Phosphorus Supplement": "फास्फोरस अनुपूरक",
    "DAP (Di-ammonium Phosphate)": "डीएपी (डायमिनियम फॉस्फेट)",
    "Nitrogen Supplement": "नाइट्रोजन अनुपूरक",
    "Urea (46% N)": "यूरिया (46% एन)",
    "Organic Manure": "जैविक खाद",
    "Farm Yard Manure (FYM) / Compost": "खेत की खाद / कम्पोस्ट",
    "Basal — at sowing": "बुवाई के समय बेसल",
    "Top dressing — 2 split doses": "टॉप ड्रेसिंग — 2 विभाजित खुराक",
    "Incorporate 15 days before sowing": "बुवाई से 15 दिन पहले शामिल करें"
  },
  te: {
    "Report ID": "నివేదిక ఐడి",
    "Prepared For": "కొరకు తయారుచేయబడింది",
    "Generated On": "ఉత్పత్తి చేసిన తేదీ",
    "EXECUTIVE AGRONOMIC SUMMARY": "ఎగ్జిక్యూటివ్ అగ్రోనమిక్ సారాంశం",
    "Soil Classified": "వర్గీకరించబడిన నేల",
    "Soil Health": "నేల ఆరోగ్యం",
    "Top Recommended Crop": "అత్యంత సిఫార్సు చేయబడిన పంట",
    "Field Location": "పొలం స్థానం",
    "Nutrient Alert": "పోషక హెచ్చరిక",
    "Immediate Action": "తక్షణ చర్య",
    "Soil Classification — AI Analysis Result": "నేల వర్గీకరణ — AI విశ్లేషణ ఫలితం",
    "Predicted Soil Class": "అంచనా వేసిన నేల రకం",
    "Soil Fertility": "నేల సారవంతం",
    "Characteristics": "లక్షణాలు",
    "Soil Classification Probability Distribution:": "నేల వర్గీకరణ సంభావ్యత పంపిణీ:",
    "Alluvial Soil": "ఒండ్రు నేల",
    "Loamy Soil": "దుమ్ము నేల",
    "Silt Soil": "సిల్ట్ నేల",
    "Sandy Soil": "ఇసుక నేల",
    "Red Soil": "ఎర్ర నేల",
    "Black Soil": "నల్ల నేల",
    "Clay Soil": "నల్ల రేగడి నేల",
    "Unknown Soil": "తెలియని నేల",
    "Valued Farmer": "ప్రియమైన రైతు",
    "Optimal": "అనుకూలమైనది",
    "Moderate": "మధ్యస్థంగా ఉంది",
    "Low": "తక్కువగా ఉంది",
    "Low (Deficient)": "తక్కువ (లోపం)",
    "Optimal (Adequate)": "అనుకూలం (సరిపోతుంది)",
    "Parameter": "పరామితి",
    "Measured Value": "కొలిచిన విలువ",
    "Unit": "ప్రమాణం",
    "Agronomic Status": "వ్యవసాయ స్థితి",
    "Soil pH": "నేల pH",
    "Nitrogen (N)": "నత్రజని (N)",
    "Phosphorus (P)": "భాస్వరం (P)",
    "Potassium (K)": "పొటాషియం (K)",
    "Organic Carbon (OC)": "సేంద్రీయ కర్బనం (OC)",
    "Electrical Conductivity (EC)": "విద్యుత్ వాహకత (EC)",
    "Weather & Meteorological Context": "వాతావరణ & వాతావరణ సందర్భం",
    "Observed Weather": "గమనించిన వాతావరణం",
    "Temperature": "ఉష్ణోగ్రత",
    "Humidity": "తేమ",
    "Rainfall": "వర్షపాతం",
    "Wind Speed": "గాలి వేగం",
    "Condition": "పరిస్థితి",
    "Agronomic Implications": "వ్యవసాయ చిక్కులు",
    "Hyperlocal weather matches expected growing conditions. No immediate alerts.": "స్థానిక వాతావరణం ఆశించిన పెరుగుదల పరిస్థితులతో సరిపోలుతుంది. తక్షణ హెచ్చరికలు లేవు.",
    "Crop Suitability & Yield Optimization": "పంట అనుకూలత & దిగుబడి ఆప్టిమైజేషన్",
    "Rank": "ర్యాంకు",
    "Crop Name": "పంట పేరు",
    "Match Score": "సరిపోలిక స్కోరు",
    "Suitability Index": "అనుకూలత సూచిక",
    "Agronomic Insight": "వ్యవసాయ అంతర్దృష్టి",
    "Fertilizer Advisory & Nutrient Management": "ఎరువుల సలహా & పోషక నిర్వహణ",
    "Nutrient Target": "పోషక లక్ష్యం",
    "Recommended Fertilizer Product": "సిఫార్సు చేసిన ఎరువుల ఉత్పత్తి",
    "Optimal Dosage": "సరైన మోతాదు",
    "Application Method": "అప్లికేషన్ విధానం",
    "General Agronomic Advisory Notes": "సాధారణ వ్యవసాయ సలహా గమనికలు",
    "Disclaimer": "నిరాకరణ: ఈ నివేదిక సలహా ప్రయోజనాల కోసం మాత్రమే ఆగ్రోఏఐ ద్వారా రూపొందించబడింది. ఎల్లప్పుడూ ధృవీకరించబడిన వ్యవసాయ నిపుణుడిని సంప్రదించండి.",
    "Report ready": "నివేదిక సిద్ధంగా ఉంది",
    "Basal Application Note": "విత్తడానికి ముందు బేసల్ డోస్‌గా MOP (ఎకరానికి 50 కిలోలు) మరియు DAP (ఎకరానికి 40 కిలోలు) వేయండి.",
    "Phosphorus, Potassium": "భాస్వరం, పొటాషియం",
    "Infertile / Moderate": "నిస్సారమైన / మధ్యస్థం",
    "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.": "నేలలో బంకమట్టి అధికంగా ఉండటం, ఎక్కువ తేమను నిలుపుకోవడం, ఆదర్శ కాటయాన్-మార్పిడి — లోతైన వేర్లు కలిగిన పంటలకు బాగా సరిపోతుంది.",
    "Cotton": "ప్రత్తి",
    "Soybean": "సోయాబీన్",
    "Maize": "మొక్కజొన్న",
    "Groundnut": "వేరుశనగ",
    "Jowar": "జొన్నలు",
    "Wheat": "గోధుమ",
    "Sugarcane": "చెరకు",
    "Excellent Match": "అద్భుతమైన సరిపోలిక",
    "Very Good Match": "చాలా మంచి సరిపోలిక",
    "Good Match": "మంచి సరిపోలిక",
    "Moderate Match": "మధ్యస్థ సరిపోలిక",
    "Suitable Match": "అనుకూల సరిపోలిక",
    "Urea": "యూరియా",
    "DAP": "DAP ఎరువు",
    "MOP": "MOP ఎరువు",
    "Potassium Supplement": "పొటాషియం సప్లిమెంట్",
    "MOP (Muriate of Potash)": "MOP ఎరువు",
    "Phosphorus Supplement": "భాస్వరం సప్లిమెంట్",
    "DAP (Di-ammonium Phosphate)": "DAP ఎరువు",
    "Nitrogen Supplement": "నత్రజని సప్లిమెంట్",
    "Urea (46% N)": "యూరియా (46% N)",
    "Organic Manure": "సేంద్రీయ ఎరువు",
    "Farm Yard Manure (FYM) / Compost": "పశువుల పెంట / కంపోస్ట్",
    "Basal — at sowing": "విత్తే సమయంలో బేసల్",
    "Top dressing — 2 split doses": "టాప్ డ్రెస్సింగ్ — 2 విడతలుగా",
    "Incorporate 15 days before sowing": "విత్తడానికి 15 రోజుల ముందు కలపండి"
  },
  ta: {
    "Report ID": "அறிக்கை ஐடி",
    "Prepared For": "தயாரிக்கப்பட்டது",
    "Generated On": "உருவாக்கப்பட்ட தேதி",
    "EXECUTIVE AGRONOMIC SUMMARY": "நிர்வாக வேளாண் சுருக்கம்",
    "Soil Classified": "மண் வகைப்பாடு",
    "Soil Health": "மண் ஆரோக்கியம்",
    "Top Recommended Crop": "பரிந்துரைக்கப்படும் சிறந்த பயிர்",
    "Field Location": "வயல் இருப்பிடம்",
    "Nutrient Alert": "ஊட்டச்சத்து எச்சரிக்கை",
    "Immediate Action": "உடனடி நடவடிக்கை",
    "Soil Classification — AI Analysis Result": "மண் வகைப்பாடு — AI பகுப்பாய்வு முடிவு",
    "Predicted Soil Class": "கணிக்கப்பட்ட மண் வகை",
    "Soil Fertility": "மண் வளம்",
    "Characteristics": "பண்புகள்",
    "Soil Classification Probability Distribution:": "மண் வகைப்பாடு நிகழ்தகவு விநியோகம்:",
    "Alluvial Soil": "வண்டல் மண்",
    "Loamy Soil": "வண்டல் கலந்த மண்",
    "Silt Soil": "வண்டல் படிவு மண்",
    "Sandy Soil": "மணல் மண்",
    "Red Soil": "செம்மண்",
    "Black Soil": "கரிசல் மண்",
    "Clay Soil": "களிமண்",
    "Unknown Soil": "அறியப்படாத மண்",
    "Valued Farmer": "மதிப்பிற்குரிய விவசாயி",
    "Optimal": "உகந்தது",
    "Moderate": "மிதமானது",
    "Low": "குறைவானது",
    "Low (Deficient)": "குறைவு (குறைபாடு)",
    "Optimal (Adequate)": "உகந்தது (போதுமானது)",
    "Parameter": "அளவுரு",
    "Measured Value": "அளவிடப்பட்ட மதிப்பு",
    "Unit": "அலகு",
    "Agronomic Status": "வேளாண் நிலை",
    "Soil pH": "மண் pH",
    "Nitrogen (N)": "நைட்ரஜன் (N)",
    "Phosphorus (P)": "பாஸ்பரஸ் (P)",
    "Potassium (K)": "பொட்டாசியம் (K)",
    "Organic Carbon (OC)": "கரிம கார்பன் (OC)",
    "Electrical Conductivity (EC)": "மின் கடத்துத்திறன் (EC)",
    "Weather & Meteorological Context": "வானிலை மற்றும் வானிலையியல் சூழல்",
    "Observed Weather": "அவதானிக்கப்பட்ட வானிலை",
    "Temperature": "வெப்பநிலை",
    "Humidity": "ஈரப்பதம்",
    "Rainfall": "மழைப்பொழிவு",
    "Wind Speed": "காற்றின் வேகம்",
    "Condition": "நிலை",
    "Agronomic Implications": "வேளாண் தாக்கங்கள்",
    "Hyperlocal weather matches expected growing conditions. No immediate alerts.": "உள்ளூர் வானிலை எதிர்பார்த்த வளரும் நிலைமைகளுடன் பொருந்துகிறது. உடனடி விழிப்பூட்டல்கள் இல்லை.",
    "Crop Suitability & Yield Optimization": "பயிர் பொருத்தம் & மகசூல் தேர்வுமுறை",
    "Rank": "தரவரிசை",
    "Crop Name": "பயிரின் பெயர்",
    "Match Score": "பொருத்த மதிப்பெண்",
    "Suitability Index": "பொருத்த குறியீடு",
    "Agronomic Insight": "வேளாண் நுண்ணறிவு",
    "Fertilizer Advisory & Nutrient Management": "உர ஆலோசனை & ஊட்டச்சத்து மேலாண்மை",
    "Nutrient Target": "ஊட்டச்சத்து இலக்கு",
    "Recommended Fertilizer Product": "பரிந்துரைக்கப்படும் உர தயாரிப்பு",
    "Optimal Dosage": "உகந்த அளவு",
    "Application Method": "பயன்படுத்தும் முறை",
    "General Agronomic Advisory Notes": "பொதுவான வேளாண் ஆலோசனை குறிப்புகள்",
    "Disclaimer": "பொறுப்புத் துறப்பு: இந்த அறிக்கை ஆலோசனை நோக்கங்களுக்காக மட்டுமே அக்ரோஏஐ ஆல் உருவாக்கப்பட்டது. எப்போதும் ஒரு சான்றளிக்கப்பட்ட வேளாண் நிபுணரை அணுகவும்.",
    "Report ready": "அறிக்கை தயாராக உள்ளது",
    "Basal Application Note": "விதைப்பதற்கு முன் அடித்தள அளவாக MOP (50 கிலோ/ஏக்கர்) மற்றும் DAP (40 கிலோ/ஏக்கர்) பயன்படுத்தவும்.",
    "Phosphorus, Potassium": "பாஸ்பரஸ், பொட்டாசியம்",
    "Infertile / Moderate": "வளமற்றது / மிதமானது",
    "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.": "களிமண் நிறைந்த அமைப்பு, அதிக ஈரப்பதம் தக்கவைப்பு, சிறந்த கேஷன்-பரிமாற்றம் — ஆழமான வேர்விடும் பயிர்களுக்கு மிகவும் உகந்தது.",
    "Cotton": "பருத்தி",
    "Soybean": "சோயாபீன்ஸ்",
    "Maize": "சோளம்",
    "Groundnut": "நிலக்கடலை",
    "Jowar": "சோளம்",
    "Wheat": "கோதுமை",
    "Sugarcane": "கரும்பு",
    "Excellent Match": "சிறந்த பொருத்தம்",
    "Very Good Match": "மிகச் சிறந்த பொருத்தம்",
    "Good Match": "நல்ல பொருத்தம்",
    "Moderate Match": "மிதமான பொருத்தம்",
    "Suitable Match": "பொருத்தமான மேட்ச்",
    "Urea": "யூரியா",
    "DAP": "டிஏபி உர",
    "MOP": "எம்ஓபி உர",
    "Potassium Supplement": "பொட்டாசியம் சப்ளிமெண்ட்",
    "MOP (Muriate of Potash)": "எம்ஓபி உர",
    "Phosphorus Supplement": "பாஸ்பரஸ் சப்ளிமெண்ட்",
    "DAP (Di-ammonium Phosphate)": "டிஏபி உர",
    "Nitrogen Supplement": "நைட்ரஜன் சப்ளிமெண்ட்",
    "Urea (46% N)": "யூரியா (46% என்)",
    "Organic Manure": "இயற்கை உரம்",
    "Farm Yard Manure (FYM) / Compost": "தொழு உரம் / உரம்",
    "Basal — at sowing": "அடித்தள உரமாக — விதைக்கும் போது",
    "Top dressing — 2 shift doses": "மேல் உரமாக — 2 தவணைகளில்",
    "Incorporate 15 days before sowing": "விதைப்பதற்கு 15 நாட்களுக்கு முன் கலக்கவும்"
  },
  sat: {
    "Report ID": "ᱨᱤᱯᱳᱨᱴ ᱟᱭᱰᱤ",
    "Prepared For": "ᱥᱟᱯᱲᱟᱣ ᱟᱠᱟᱱᱟ",
    "Generated On": "ᱛᱮᱭᱟᱨ ᱟᱠᱟᱱ ᱢᱟᱹᱦᱤᱛ",
    "EXECUTIVE AGRONOMIC SUMMARY": "ᱠᱟᱹᱢᱤᱭᱟᱹ ᱪᱟᱥ ᱠᱟᱛᱷᱟ ᱛᱮᱛᱮᱫ",
    "Soil Classified": "ᱦᱟᱥᱟ ᱦᱟᱹᱴᱤᱧ ᱟᱠᱟᱱ",
    "Soil Health": "ᱦᱟᱥᱟ ᱞᱟᱦᱟᱱᱛᱤ ᱦᱚᱲᱢᳳ",
    "Top Recommended Crop": "ᱥᱚᱨᱮᱥ ᱥᱮᱞᱮᱫ ᱟᱠᱟᱱ ᱪᱟᱥ",
    "Field Location": "ᱵᱟᱹᱫᱽ ᱡᱟᱭᱜᱟ",
    "Nutrient Alert": "ᱥᱟᱨ ᱛᱮᱛᱮᱫ ᱦᱩᱥᱤᱭᱟᱹᱨ",
    "Immediate Action": "ᱛᱚᱛᱠᱟᱞ ᱠᱟᱹᱢᱤ",
    "Soil Classification — AI Analysis Result": "ᱦᱟᱥᱟ ᱦᱟᱹᱴᱤᱧ — ᱮ.ᱟᱭ. ᱵᱤᱰᱟᱹᱣ ᱚᱨᱡᱚ",
    "Predicted Soil Class": "ᱟᱸᱥ ᱟᱠᱟᱱ ᱦᱟᱥᱟ ᱛᱷᱚᱠ",
    "Soil Fertility": "ᱦᱟᱥᱟ ᱨᱮᱱᱟᱜ ᱩᱨᱵᱚᱨᱛᱟ",
    "Characteristics": "ᱜᱩᱱ ᱠᱚ",
    "Soil Classification Probability Distribution:": "ᱦᱟᱥᱟ ᱦᱟᱹᱴᱤᱧ ᱥᱚᱢᱵᱷᱟᱵᱽ ᱦᱟᱹᱴᱤᱧ ᱚᱨᱡᱚ:",
    "Alluvial Soil": "ᱯᱚᱞᱤ ᱦᱟᱥᱟ",
    "Loamy Soil": "ᱵᱟᱹᱞᱤ ᱦᱟᱥᱟ",
    "Silt Soil": "ᱫᱚᱢᱚᱴ ᱦᱟᱥᱟ",
    "Sandy Soil": "ᱜᱤᱛᱤᱞ ᱦᱟᱥᱟ",
    "Red Soil": "ᱟᱨᱟᱜ ᱦᱟᱥᱟ",
    "Black Soil": "ᱦᱮᱸᱫᱮ ᱦᱟᱥᱟ",
    "Clay Soil": "ᱦᱟᱥᱟ ᱪᱤᱠᱦ",
    "Unknown Soil": "ᱵᱟᱝ ᱵᱟᱰᱟᱭ ᱦᱟᱥᱟ",
    "Valued Farmer": "ᱫᱩᱞᱟᱹᱲᱤᱭᱟᱹ ᱪᱟᱹᱥᱤ",
    "Optimal": "ᱥᱚᱨᱮᱥ",
    "Moderate": "ᱛᱟᱞᱟᱢᱟᱞᱟ",
    "Low": "ᱠᱚᱢ",
    "Low (Deficient)": "ᱠᱚᱢ (ᱚᱵᱷᱟᱵᱽ)",
    "Optimal (Adequate)": "ᱥᱚᱨᱮᱥ (ᱡᱚᱛᱷᱟᱛ)",
    "Parameter": "ᱢᱟᱹᱱ ᱛᱮᱛᱮᱫ",
    "Measured Value": "ᱡᱚᱠᱷᱟ ᱟᱠᱟᱱ ᱢᱟᱹᱱ",
    "Unit": "ᱮᱠᱚᱠ",
    "Agronomic Status": "ᱪᱟᱥ ᱨᱮᱱᱟᱜ ᱦᱟᱞᱚᱛ",
    "Soil pH": "ᱦᱟᱥᱟ ᱨᱮᱱᱟᱜ ᱯᱤ.ᱮᱪ.",
    "Nitrogen (N)": "ᱱᱟᱭᱴᱨᱳᱡᱮն (N)",
    "Phosphorus (P)": "ᱯᱷᱚᱥᱯᱷᱚᱨᱟᱥ (P)",
    "Potassium (K)": "ᱯᱳᱴᱟᱥ (K)",
    "Organic Carbon (OC)": "ᱡᱤᱣᱤ ᱠᱟᱨᱵᱚᱱ (OC)",
    "Electrical Conductivity (EC)": "ᱵᱤᱡᱽᱞᱤ ᱪᱟᱞᱟᱣ (EC)",
    "Weather & Meteorological Context": "ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱦᱟᱞᱚᱛ",
    "Observed Weather": "ᱧᱮᱞ ᱟᱠᱟᱱ ᱦᱚᱭ-ᱦᱤᱥᱤᱫ",
    "Temperature": "ᱞᱚᱞᱚᱛᱚ表",
    "Humidity": "ᱦᱚᱭ ᱨᱮ ᱫᱟᱜ ᱛᱮᱛᱮᱫ",
    "Rainfall": "ᱫᱟᱜ ᱡᱟᱹᱲᱤ",
    "Wind Speed": "ᱦᱚᱭ ᱨᱮᱱᱟᱜ ᱛᱟᱹᱯᱤᱥ",
    "Condition": "ᱚᱵᱚᱥᱛᱷᱟ",
    "Agronomic Implications": "ᱪᱟᱥ ᱚᱨᱡᱚ",
    "Hyperlocal weather matches expected growing conditions. No immediate alerts.": "ᱚᱱᱟ ᱡᱟᱭᱜᱟ ᱨᱮᱱาᱜ ᱦᱚᱭ-ᱦᱤᱥᱤᱫ ᱪᱟᱥ ᱞᱟᱹᱜᱤᱫ ᱡᱚᱛᱷᱟᱛ ᱜᱮᱭᱟ ᱾ ᱠᱚᱱᱚ ᱦᱩᱥᱤᱭᱟᱹᱨ ᱵᱟᱹᱱᱩᱜ-ᱟ ᱾",
    "Crop Suitability & Yield Optimization": "ᱪᱟᱥ ᱡᱚᱛᱷᱟᱛ ᱟᱨ ᱡᱚ ᱡᱟᱹᱥᱛᱤ ᱚᱨᱡᱚ",
    "Rank": "ᱛᱷᱚᱠ",
    "Crop Name": "ᱪᱟᱥ ᱧᱩᱛᱩᱢ",
    "Match Score": "ᱢᱮᱞ ᱥᱠᳳᱨ",
    "Suitability Index": "ᱡᱚᱛᱷᱟᱛ ᱢᱟᱹᱱ",
    "Agronomic Insight": "ᱪᱟᱥ ᱜᱽᱭᱟᱱ",
    "Fertilizer Advisory & Nutrient Management": "ᱥᱟᱨ ᱮᱢ ᱟᱨ ᱯᱚᱥᱚᱠ ᱪᱟಚᱞᱟᱣ",
    "Nutrient Target": "ᱥᱟᱨ ᱞᱟᱹᱠᱛᱤ",
    "Recommended Fertilizer Product": "ᱥᱚᱨᱮᱥ ᱥᱟᱨ ᱡᱤᱱᱤᱥ",
    "Optimal Dosage": "ᱡᱚᱛᱷᱟᱛ ᱢᱟᱹᱱ ᱮᱢ",
    "Application Method": "ᱥᱟᱨ ᱮᱢ ᱦᱚᱨᱟ",
    "General Agronomic Advisory Notes": "ᱥᱟᱫᱷᱟᱨᱚᱱ ᱪᱟᱥ ᱥᱚᱞᱦᱟ",
    "Disclaimer": "ᱵᱟᰰᱟᱭ ᱠᱟᱛᱷᱟ: ᱱᱚᱣา ᱨᱤᱯᱳᱨᱴ ᱫᱚ ᱮᱜᱽᱨᱳ.ᱮ.ᱟᱭ ᱦᱚᱛᱮᱛᱮ ᱥᱚᱞᱦᱟ ᱞᱟᱹᱜᱤᱫ ᱜᱮ ᱛᱮᱭᱟᱨ ᱟᱠᱟᱱᱟ ᱾ ᱥᱚᱨᱮᱥ ᱪᱟᱥ ᱜᱽᱭᱟᱱᱤ ᱥᱟᱶ ᱜᱟᱞᱢᱟᱨᱟᱣ ᱢᱮ ᱾",
    "Report ready": "ᱨᱤᱯᱳᱨᱴ ᱥᱟᱯᱲᱟᱣ ᱮᱱᱟ",
    "Basal Application Note": "ᱮᱨ ᱞᱟᱦᱟ ᱨᱮ ᱮᱠᱚᱨ ᱯᱤᱪᱷᱤ MOP (50 ᱠᱤᱞᳳ) ᱟᱨ DAP (40 ᱠᱤᱞᳳ) ᱮᱢ ᱢᱮ ᱾",
    "Phosphorus, Potassium": "ᱯᱷᱚᱥᱯᱷᱚᱨᱟᱥ, ᱯᱳᱴᱟᱥ",
    "Infertile / Moderate": "ᱵᱟᱝ ᱵᱷᱟᱹᱜᱤ / ᱛᱟᱞᱟᱢᱟᱞᱟ",
    "Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.": "ᱪᱤᱠᱦ ᱦᱟᱥᱟ ᱛᱮᱛᱮᱫ, ᱫᱟᱜ ᱟᱹᱰᱤ ᱜᱷᱟᱹᱲᱤᱡ ᱫᱚᱦᱚ ᱫᱟᱲᱮᱭᱟᱜ-ᱟ, ᱥᱚᱨᱮᱥ ᱦᱟᱥᱟ ᱜᱩᱱ — ᱜᱷᱟᱹᱲᱤᱡ ᱨᱮᱦᱮᱫ ᱪᱟᱥ ᱞᱟᱹᱜིᱫ ᱡᱚᱛᱷᱟᱛ ᱜᱮᱭᱟ ᱾",
    "Cotton": "ᱠᱟᱥᱠᱚᱢ",
    "Soybean": "ᱥᱚᱭᱟᱵᱤᱱ",
    "Maize": "ᱡᱚᱱᱰᱨᱟ",
    "Groundnut": "ᱫᱷᱟᱹᱲ ᱜᱩᱸᱡᱤ",
    "Jowar": "ᱡᱚᱣᱟᱨ",
    "Wheat": "ᱜᱩᱦᱩᱢ",
    "Sugarcane": "ᱟᱠ",
    "Excellent Match": "ᱥᱚᱨᱮᱥ ᱢᱮᱞ",
    "Very Good Match": "ᱟᱹᱰᱤ ᱱᱟᱯาᱭ ᱢᱮᱞ",
    "Good Match": "ᱱᱟᱯᱟᱭ ᱢᱮᱞ",
    "Moderate Match": "ᱛᱟᱞᱟᱢᱟᱞᱟ ᱢᱮᱞ",
    "Suitable Match": "ᱡᱚᱛᱷᱟᱛ ᱢᱮᱞ",
    "Urea": "ᱭᱩᱨᱤᱭᱟ",
    "DAP": "ᱰᱤ.ᱮ.ᱯᱤ.",
    "MOP": "ᱮᱢ.ᳳ.ᱯᱤ.",
    "Potassium Supplement": "ᱯᱳᱴᱟᱥ ᱥᱟᱨ",
    "MOP (Muriate of Potash)": "ᱮᱢ.ᳳ.ᱯᱤ. ᱥᱟᱨ",
    "Phosphorus Supplement": "ᱯᱷᱚᱥᱯᱷᱚᱨᱟᱥ ᱥᱟᱨ",
    "DAP (Di-ammonium Phosphate)": "ᱰᱤ.ᱮ.ᱯᱤ. ᱥᱟᱨ",
    "Nitrogen Supplement": "ᱱᱟᱭᱴᱨᱳᱡᱮᱱ ᱥᱟᱨ",
    "Urea (46% N)": "ᱭᱩᱨᱤᱭᱟ (᱔᱖% N)",
    "Organic Manure": "ᱡᱤᱣᱤ ᱥᱟᱨ",
    "Farm Yard Manure (FYM) / Compost": "ᱥᱚᱲᱮ ᱥᱟᱨ / ᱠᱚᱢᱯᱳᱥᱴ",
    "Basal — at sowing": "ᱮᱨ ᱚᱠᱛᱚ ᱨᱮ",
    "Top dressing — 2 split doses": "ᱪᱮᱛᱟᱱ ᱮᱢ — ᱒ ᱵᱟᱨ ᱛᱮ",
    "Incorporate 15 days before sowing": "ᱮᱨ ᱑᱕ ᱢᱟᱦᱟ ᱞᱟᱦᱟ ᱨᱮ ᱢᱮᱥᱟᱭ ᱢᱮ"
  }
}

export function generatePdfReport(data: ReportData) {
  const selectedLang = localStorage.getItem('selected_language') || 'en'
  const t = (key: string): string => {
    if (!key) return ''
    const cleanKey = key.trim()
    const dict = PDF_TRANSLATIONS[selectedLang] || PDF_TRANSLATIONS['en']
    return dict[cleanKey] || PDF_TRANSLATIONS['en'][cleanKey] || cleanKey
  }

  const dateStr = data.generatedOn || new Date().toLocaleString(selectedLang === 'en' ? 'en-US' : selectedLang, { month: 'long', day: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' })
  const reportId = data.reportId || `ANL-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${Math.floor(100000 + Math.random() * 900000)}`
  
  const savedUserName = (() => {
    try {
      const u = localStorage.getItem('user') || localStorage.getItem('user_profile')
      if (u && u.startsWith('{')) {
        const parsed = JSON.parse(u)
        return parsed.username || parsed.name
      }
    } catch {}
    return null
  })()
  const userName = data.userName || savedUserName || t('Valued Farmer')
  
  const soilType = t(data.soilType || 'Unknown Soil')
  const confidence = data.confidence ? (data.confidence > 1 ? data.confidence.toFixed(1) : (data.confidence * 100).toFixed(1)) : '93.2'
  const healthScore = data.soilHealthScore ?? 61.2
  const healthStatus = t(data.soilHealthStatus || (healthScore >= 75 ? 'Optimal' : healthScore >= 50 ? 'Moderate' : 'Low'))
  
  const isDisease = data.soilHealthStatus?.toLowerCase().includes('infection') || data.soilHealthStatus?.toLowerCase().includes('disease') || data.soilType?.toLowerCase().includes('blight') || data.soilType?.toLowerCase().includes('mildew') || data.soilType?.toLowerCase().includes('rust') || data.soilType?.toLowerCase().includes('virus') || data.soilType?.toLowerCase().includes('rot') || data.soilType?.toLowerCase().includes('wilt')
  const reportHeading1 = isDisease ? t('Plant Disease Detection & Analysis') : t('Soil Classification — AI Analysis Result')
  const predictedLabel = isDisease ? t('Detected Disease/Infection') : t('Predicted Soil Class')
  const execLabelSoil = isDisease ? t('Detected Pathology') : t('Soil Classified')
  
  const N = data.nValue || (data.N !== undefined ? `${data.N} mg/kg` : '90 mg/kg')
  const P = data.pValue || (data.P !== undefined ? `${data.P} mg/kg` : '42 mg/kg')
  const K = data.kValue || (data.K !== undefined ? `${data.K} mg/kg` : '43 mg/kg')
  const ph = data.phValue || (data.ph !== undefined ? String(data.ph) : '6.8')
  const oc = data.ocValue || (data.oc !== undefined ? `${data.oc} %` : '0.62 %')
  const ec = data.ecValue || (data.ec !== undefined ? `${data.ec} dS/m` : '0.41 dS/m')
  const ocNum = parseFloat(oc) || 0.62
  const phNum = parseFloat(ph) || 6.8
  
  const savedUserLoc = (() => {
    try {
      const selected = localStorage.getItem('selected_location')
      if (selected) return selected

      const u = localStorage.getItem('user') || localStorage.getItem('user_profile')
      if (u && u.startsWith('{')) {
        const parsed = JSON.parse(u)
        if (parsed.region) return parsed.region
      }
    } catch {}
    return null
  })()

  const location = data.location || savedUserLoc || 'Srikalahasthi, Tirupati District, Andhra Pradesh, India'
  const temp = data.temperature || '33 deg C'
  const humidity = data.humidity || '67 %'
  const rainfall = data.rainfall || '0.0 mm'
  const wind = data.windSpeed || '12 km/h'
  const weatherCond = t(data.weatherCondition || 'Clear')

  const topCrop = t(data.topCrop || 'Cotton')
  const topCropScore = data.topCropScore || 100

  const crops = data.crops || [
    { rank: 'Top #1', name: t('Cotton'), score: 100, match: t('Excellent Match'), insight: t('Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.') },
    { rank: '#2', name: t('Soybean'), score: 94, match: t('Very Good Match'), insight: t('Excellent nitrogen-fixing properties to replenish degraded soil.') },
    { rank: '#3', name: t('Wheat'), score: 79, match: t('Good Match'), insight: t('High rabi yield potential under moderate temperature.') },
    { rank: '#4', name: t('Sugarcane'), score: 73, match: t('Moderate Match'), insight: t('Good choice for loose loamy soil texture. Watch phosphorus levels.') },
    { rank: '#5', name: t('Maize'), score: 55, match: t('Suitable Match'), insight: t('Performs well in high-moisture paddy conditions.') }
  ]

  const fertilizers = data.fertilizers || [
    { category: t('Potassium Supplement'), product: t('MOP (Muriate of Potash)'), dosage: '50 kg / acre', method: t('Basal — at sowing') },
    { category: t('Phosphorus Supplement'), product: t('DAP (Di-ammonium Phosphate)'), dosage: '40 kg / acre', method: t('Basal — at sowing') },
    { category: t('Nitrogen Supplement'), product: t('Urea (46% N)'), dosage: '25 kg / acre', method: t('Top dressing — 2 split doses') },
    { category: t('Organic Manure'), product: t('Farm Yard Manure (FYM) / Compost'), dosage: '3 Tons / acre', method: t('Incorporate 15 days before sowing') }
  ]

  const advisoryNotes = data.advisoryNotes || [
    t('applyNitrogenSplit') || t('Basal Application Note'),
    t('usePhosphateBasal') || t('Maintain soil pH between 6.0 and 7.5 for optimal nutrient availability.'),
    t('applyGypsumSoil') || t('Ensure uniform drainage to prevent waterlogging and root rot issues.')
  ]

  const pdfProbs = data.probabilities && Object.keys(data.probabilities).length > 0
    ? Object.entries(data.probabilities)
        .map(([soil, prob]) => ({ soil: t(soil), prob }))
        .sort((a, b) => b.prob - a.prob)
    : [
        { soil: soilType, prob: parseFloat(confidence) },
        { soil: t('Alluvial Soil'), prob: 16.9 },
        { soil: t('Loamy Soil'), prob: 9.3 },
        { soil: t('Silt Soil'), prob: 6.5 },
        { soil: t('Sandy Soil'), prob: 1.4 }
      ];

  const probsHtml = pdfProbs.map((p, idx) => {
    const fillPercent = Math.min(100, Math.max(0, p.prob));
    const color = idx === 0 ? '#15803d' : idx === 1 ? '#22c55e' : idx === 2 ? '#4ade80' : idx === 3 ? '#a7f3d0' : '#cbd5e1';
    return `
      <div class="bar-row">
        <div class="bar-label">${p.soil}</div>
        <div class="bar-track"><div class="bar-fill" style="width: ${fillPercent}%; background: ${color};"></div></div>
        <div class="bar-val" style="color: ${idx === 0 ? '#15803d' : '#4b5563'}; font-weight: ${idx === 0 ? '700' : 'normal'};">${p.prob.toFixed(1)}%</div>
      </div>
    `;
  }).join('');

  const printWindow = window.open('', '_blank')
  if (!printWindow) {
    alert(t('Please allow popups to download the PDF report.'))
    return
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>AgroAI Agronomic Advisory Report - ${reportId}</title>
      <style>
        @page {
          size: A4;
          margin: 15mm 15mm 15mm 15mm;
        }
        body {
          font-family: 'Helvetica Neue', Arial, sans-serif;
          color: #1f2937;
          line-height: 1.5;
          margin: 0;
          padding: 0;
          font-size: 13px;
        }
        .page {
          page-break-after: always;
          position: relative;
          height: 260mm;
          box-sizing: border-box;
        }
        .page:last-child {
          page-break-after: avoid;
        }
        .header-table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 12px;
        }
        .logo {
          font-size: 26px;
          font-weight: 800;
          color: #166534;
          letter-spacing: -0.5px;
        }
        .logo-sub {
          font-size: 10px;
          color: #6b7280;
          text-transform: uppercase;
          font-weight: 600;
          letter-spacing: 0.5px;
        }
        .header-meta {
          text-align: right;
          font-size: 11.5px;
          color: #4b5563;
        }
        .green-divider {
          height: 4px;
          background: linear-gradient(90deg, #15803d, #3b82f6);
          margin-bottom: 20px;
          border-radius: 2px;
        }
        .exec-summary {
          background-color: #f0fdf4;
          border: 1px solid #bbf7d0;
          border-radius: 12px;
          padding: 16px;
          margin-bottom: 20px;
        }
        .exec-title {
          font-weight: 800;
          font-size: 12px;
          color: #166534;
          margin-bottom: 10px;
          letter-spacing: 0.5px;
        }
        .summary-line {
          margin-bottom: 6px;
          font-size: 12.5px;
        }
        .summary-line:last-child {
          margin-bottom: 0;
        }
        .sec-heading {
          font-size: 16px;
          font-weight: 800;
          color: #111827;
          border-bottom: 1px solid #e5e7eb;
          padding-bottom: 6px;
          margin-top: 24px;
          margin-bottom: 12px;
        }
        .info-card {
          background-color: #f8fafc;
          border: 1px solid #e2e8f0;
          border-radius: 10px;
          padding: 14px;
          margin-bottom: 16px;
        }
        .bar-row {
          display: flex;
          align-items: center;
          margin-bottom: 8px;
        }
        .bar-label {
          width: 140px;
          font-weight: 600;
          font-size: 12px;
        }
        .bar-track {
          flex: 1;
          background: #f1f5f9;
          height: 12px;
          border-radius: 6px;
          overflow: hidden;
          margin: 0 12px;
        }
        .bar-fill {
          height: 100%;
          background: #22c55e;
        }
        .bar-fill-red {
          height: 100%;
          background: #ef4444;
        }
        .bar-val {
          width: 45px;
          font-weight: 700;
          font-size: 12px;
          text-align: right;
        }
        .data-table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 20px;
        }
        .data-table th {
          background: #f8fafc;
          border-bottom: 2px solid #e2e8f0;
          padding: 8px 10px;
          font-weight: 700;
          text-align: left;
          font-size: 11.5px;
          color: #4b5563;
        }
        .data-table td {
          border-bottom: 1px solid #f1f5f9;
          padding: 8px 10px;
          font-size: 12px;
        }
        .green-text {
          color: #166534;
          font-weight: 600;
        }
        .red-text {
          color: #b91c1c;
          font-weight: 600;
        }
        .amber-text {
          color: #b45309;
          font-weight: 600;
        }
        .advisory-box {
          background: #fffbeb;
          border: 1px solid #fef3c7;
          border-radius: 10px;
          padding: 14px;
          margin-top: 16px;
        }
        .footer {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          display: flex;
          justify-content: space-between;
          border-top: 1px solid #e5e7eb;
          padding-top: 8px;
          color: #9ca3af;
          font-size: 10px;
        }
        .disclaimer {
          font-size: 10.5px;
          color: #6b7280;
          line-height: 1.6;
          margin-top: 24px;
          font-style: italic;
        }
      </style>
    </head>
    <body>

      <!-- PAGE 1 -->
      <div class="page">
        <table class="header-table">
          <tr>
            <td>
              <div class="logo">AgroAI</div>
              <div class="logo-sub">${t('AgroAI | AI-Powered Agricultural Decision Support System')}</div>
            </td>
            <td class="header-meta">
              <div>${t('Report ID')}: <strong>${reportId}</strong></div>
              <div>${t('Prepared For')}: <strong>${userName}</strong></div>
              <div>${t('Generated On')}: <strong>${dateStr}</strong></div>
            </td>
          </tr>
        </table>
        <div class="green-divider"></div>

        <div class="exec-summary">
          <div class="exec-title">${t('EXECUTIVE AGRONOMIC SUMMARY')}</div>
          <div class="summary-line">[+] <strong>${execLabelSoil}:</strong> ${soilType} (${t('Confidence')} / ${t('Accuracy')}: <strong>${confidence}%</strong> | ${t('High Confidence') || 'High Confidence'})</div>
          <div class="summary-line">[+] <strong>${t('Soil Health')}:</strong> <span class="amber-text">${healthStatus} (${healthScore} / 100)</span></div>
          <div class="summary-line">[+] <strong>${t('Top Recommended Crop')}:</strong> ${topCrop} — <span class="green-text">${t('Excellent Match')} (${topCropScore}/100)</span></div>
          <div class="summary-line">[+] <strong>${t('Field Location')}:</strong> ${location} | ${temp}, ${humidity} ${t('Humidity')}, ${weatherCond}</div>
          <div class="summary-line">[+] <strong>${t('Nutrient Alert')}:</strong> <span class="amber-text">${t('Phosphorus, Potassium') || 'Phosphorus, Potassium'}</span></div>
          <div class="summary-line">[+] <strong>${t('Immediate Action')}:</strong> ${t('Basal Application Note')}</div>
        </div>

        <div class="sec-heading">1. ${reportHeading1}</div>
        <div class="info-card">
          <table style="width:100%; border-collapse:collapse;">
            <tr>
              ${data.soilImage ? `<td style="width:120px; padding-right:16px; vertical-align:top;"><img src="${data.soilImage}" style="width:120px; height:120px; object-fit:cover; border-radius:8px; border:1px solid #cbd5e1;" /></td>` : ''}
              <td style="vertical-align:top;">
                <div style="font-size: 13.5px; margin-bottom: 6px;">
                  <strong>${predictedLabel}:</strong> <span style="color:#15803d; font-weight:700;">${soilType}</span> (${t('Confidence')} / ${t('Accuracy')}: <strong>${confidence}%</strong> | ${t('High Confidence') || 'High Confidence'})
                </div>
                <div style="font-size: 13px; margin-bottom: 6px;">
                  <strong>${t('Soil Fertility')}:</strong> ${t('Infertile / Moderate')}
                </div>
                <div style="font-size: 13px; color: #4b5563; line-height: 1.4;">
                  <strong>${t('Characteristics')}:</strong> ${t('Clay-rich structure, high moisture retention, ideal cation-exchange — well-suited for deep-rooting cash crops.')}
                </div>
              </td>
            </tr>
          </table>
        </div>

        <div style="font-weight: 700; color: #374151; margin-bottom: 12px; font-size: 12px;">${t('Soil Classification Probability Distribution:')}</div>
        
        ${probsHtml}

        <div class="footer">
          <div>${t('Generated by AgroAI | www.agroai.in | Confidential Agricultural Advisory')}</div>
          <div>${t('Page')} 1 ${t('of')} 4</div>
        </div>
      </div>

      <!-- PAGE 2 -->
      <div class="page">
        <div style="display:flex; justify-content: space-between; color:#6b7280; font-size:11px; margin-bottom:12px;">
          <span>${t('AgroAI | AI-Powered Agricultural Decision Support System')}</span>
          <span>${t('Confidential Agronomic Advisory Report')}</span>
        </div>
        <div class="green-divider" style="margin-bottom:20px;"></div>

        <div class="sec-heading">2. ${t('Soil Chemistry & Agronomic Parameters')}</div>
        <div style="margin-bottom:16px;">
          <div style="font-weight:700; font-size:13px; margin-bottom:6px;">${t('Soil Health Index')}:</div>
          <div style="display:flex; align-items: center; gap:16px;">
            <div style="flex:1; background:#e2e8f0; height:24px; border-radius:6px; overflow:hidden;">
              <div style="width: ${healthScore}%; background:#d97706; height:100%;"></div>
            </div>
            <div style="font-weight:800; font-size:15px; color:#d97706; min-width:140px; text-align:right;">
              ${healthScore} / 100 — ${healthStatus}
            </div>
          </div>
        </div>

        <table class="data-table">
          <thead>
            <tr>
              <th>${t('Parameter')}</th>
              <th>${t('Measured Value')}</th>
              <th>${t('Unit')}</th>
              <th>${t('Agronomic Status')}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>${t('Soil pH')}</strong></td>
              <td>${ph}</td>
              <td>pH Scale</td>
              <td><span class="green-text">${t('Optimal')}</span></td>
            </tr>
            <tr>
              <td><strong>${t('Nitrogen (N)')}</strong></td>
              <td>${N}</td>
              <td>kg/ha</td>
              <td><span class="green-text">${t('Optimal')}</span></td>
            </tr>
            <tr>
              <td><strong>${t('Phosphorus (P)')}</strong></td>
              <td>${P}</td>
              <td>kg/ha</td>
              <td><span class="red-text">${t('Low (Deficient)')}</span></td>
            </tr>
            <tr>
              <td><strong>${t('Potassium (K)')}</strong></td>
              <td>${K}</td>
              <td>kg/ha</td>
              <td><span class="red-text">${t('Low (Deficient)')}</span></td>
            </tr>
            <tr>
              <td><strong>${t('Organic Carbon (OC)')}</strong></td>
              <td>${oc}</td>
              <td>% content</td>
              <td><span class="green-text">${t('Optimal')}</span></td>
            </tr>
            <tr>
              <td><strong>${t('Electrical Conductivity (EC)')}</strong></td>
              <td>${ec}</td>
              <td>dS/m</td>
              <td><span class="green-text">${t('Optimal')}</span></td>
            </tr>
            <tr style="background:#fef3c7;">
              <td><strong>${t('Soil Health Score')}</strong></td>
              <td><strong>${healthScore} / 100</strong></td>
              <td>Index</td>
              <td><strong class="amber-text">${healthStatus.toUpperCase()}</strong></td>
            </tr>
          </tbody>
        </table>

        <div style="font-weight:700; margin-bottom:12px; font-size:12px;">${t('Nutrient Level Status (Visual)')}:</div>
        <div class="bar-row">
          <div class="bar-label">${t('Nitrogen (N)')}</div>
          <div class="bar-track"><div class="bar-fill" style="width: 75%;"></div></div>
          <div class="bar-val" style="width:100px;">${N}.00 kg/ha</div>
        </div>
        <div class="bar-row">
          <div class="bar-label">${t('Phosphorus (P)')}</div>
          <div class="bar-track"><div class="bar-fill-red" style="width: 35%;"></div></div>
          <div class="bar-val" style="width:100px; color:#dc2626;">${P}.00 kg/ha</div>
        </div>
        <div class="bar-row">
          <div class="bar-label">${t('Potassium (K)')}</div>
          <div class="bar-track"><div class="bar-fill-red" style="width: 36%;"></div></div>
          <div class="bar-val" style="width:100px; color:#dc2626;">${K}.00 kg/ha</div>
        </div>
        <div class="bar-row">
          <div class="bar-label">${t('Organic Carbon (OC)')}</div>
          <div class="bar-track"><div class="bar-fill" style="width: 62%;"></div></div>
          <div class="bar-val" style="width:100px;">${(ocNum * 100).toFixed(2)} %</div>
        </div>
        <div class="bar-row">
          <div class="bar-label">pH (x10)</div>
          <div class="bar-track"><div class="bar-fill" style="width: 68%;"></div></div>
          <div class="bar-val" style="width:100px;">${(phNum * 10).toFixed(2)} pH</div>
        </div>

        <div class="sec-heading" style="margin-top:30px;">3. ${t('Weather & Meteorological Context')}</div>
        <table class="data-table">
          <thead>
            <tr>
              <th>${t('Parameter')}</th>
              <th>${t('Measured Value') || 'Value'}</th>
              <th>${t('Parameter')}</th>
              <th>${t('Measured Value') || 'Value'}</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>${t('Temperature')}</strong></td>
              <td>${temp}</td>
              <td><strong>${t('Humidity')}</strong></td>
              <td>${humidity}</td>
            </tr>
            <tr>
              <td><strong>${t('Rainfall')}</strong></td>
              <td>${rainfall}</td>
              <td><strong>${t('Wind Speed')}</strong></td>
              <td>${wind}</td>
            </tr>
            <tr>
              <td><strong>${t('Condition')}</strong></td>
              <td>${weatherCond}</td>
              <td><strong>${t('Record Date') || 'Record Date'}</strong></td>
              <td>${dateStr.split(' at ')[0]}</td>
            </tr>
            <tr>
              <td><strong>${t('location') || 'Location'}</strong></td>
              <td>${location}</td>
              <td><strong>${t('State / District') || 'State / District'}</strong></td>
              <td>${location.includes(',') ? location.split(',')[1] : 'Andhra Pradesh'}</td>
            </tr>
          </tbody>
        </table>

        <div class="footer">
          <div>${t('Generated by AgroAI | www.agroai.in | Confidential Agricultural Advisory')}</div>
          <div>${t('Page')} 2 ${t('of')} 4</div>
        </div>
      </div>

      <!-- PAGE 3 -->
      <div class="page">
        <div style="display:flex; justify-content: space-between; color:#6b7280; font-size:11px; margin-bottom:12px;">
          <span>${t('AgroAI | AI-Powered Agricultural Decision Support System')}</span>
          <span>${t('Confidential Agronomic Advisory Report')}</span>
        </div>
        <div class="green-divider" style="margin-bottom:20px;"></div>

        <div class="sec-heading">4. ${t('top5RecommendedCrops') || 'Top 5 Recommended Crops — AI Suitability Index'}</div>
        <table class="data-table">
          <thead>
            <tr>
              <th>${t('Rank')}</th>
              <th>${t('Crop Name')}</th>
              <th>${t('Suitability Index')}</th>
              <th>${t('Match Score') || 'Match Rating'}</th>
              <th>${t('Agronomic Insight')}</th>
            </tr>
          </thead>
          <tbody>
            ${crops.map(c => `
              <tr>
                <td><strong>${c.rank}</strong></td>
                <td><strong>${c.name}</strong></td>
                <td><strong>${c.score} / 100</strong></td>
                <td><span class="green-text">${c.match}</span></td>
                <td style="font-size:11.5px; color:#4b5563;">${c.insight}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div style="font-weight:700; margin-bottom:12px; font-size:12px;">${t('Crop Suitability Index (Normalised)') || 'Crop Suitability Index (Normalised)'}:</div>
        ${crops.map(c => `
          <div class="bar-row">
            <div class="bar-label">${c.name}</div>
            <div class="bar-track"><div class="bar-fill" style="width: ${c.score}%;"></div></div>
            <div class="bar-val">${c.score}.0</div>
          </div>
        `).join('')}

        <div class="sec-heading" style="margin-top:30px;">5. ${t('Fertilizer Advisory & Nutrient Management') || 'Fertilizer Advisory & Application Schedule'}</div>
        <table class="data-table">
          <thead>
            <tr>
              <th>${t('Fertilizer Category') || 'Fertilizer Category'}</th>
              <th>${t('Product Name') || 'Product Name'}</th>
              <th>${t('Dosage / Rate') || 'Dosage / Rate'}</th>
              <th>${t('Application Method')}</th>
            </tr>
          </thead>
          <tbody>
            ${fertilizers.map(f => `
              <tr>
                <td><strong>${f.category}</strong></td>
                <td>${f.product}</td>
                <td><strong>${f.dosage}</strong></td>
                <td>${f.method}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>

        <div class="advisory-box">
          <div style="font-weight:800; color:#1f2937; margin-bottom:8px;">${t('General Agronomic Advisory Notes') || 'AgroAI Gemini Advisory Notes'}:</div>
          ${advisoryNotes.map(n => `<div style="margin-bottom:4px; color:#4b5563;">- ${n}</div>`).join('')}
        </div>

        <div class="footer">
          <div>${t('Generated by AgroAI | www.agroai.in | Confidential Agricultural Advisory')}</div>
          <div>${t('Page')} 3 ${t('of')} 4</div>
        </div>
      </div>

      <!-- PAGE 4 -->
      <div class="page">
        <div style="display:flex; justify-content: space-between; color:#6b7280; font-size:11px; margin-bottom:12px;">
          <span>${t('AgroAI | AI-Powered Agricultural Decision Support System')}</span>
          <span>${t('Confidential Agronomic Advisory Report')}</span>
        </div>
        <div class="green-divider" style="margin-bottom:20px;"></div>

        <div class="sec-heading">6. ${t('AI Agronomic Assessment & Field Advisory') || 'AI Agronomic Assessment & Field Advisory'}</div>
        <div class="info-card" style="line-height:1.7; font-size:13px; color:#374151;">
          <p style="margin-top:0;">
            ${t('AgroAI integrated the uploaded soil image analysis with soil chemistry measurements and real-time field weather data for') || 'AgroAI integrated the uploaded soil image analysis with soil chemistry measurements and real-time field weather data for'} <strong>${location}</strong>. ${t('The system identified the soil class as') || 'The system identified the soil class as'} <strong>${soilType}</strong> ${t('with') || 'with'} <strong>${confidence}% AI confidence</strong>. ${t('Based on this multi-parameter assessment,') || 'Based on this multi-parameter assessment,'} <strong>${topCrop}</strong> ${t('is recommended as the primary crop for this field season, rated an') || 'is recommended as the primary crop for this field season, rated an'} <strong>${t('Excellent Match') || 'Excellent Match'} (${topCropScore}/100)</strong> ${t('under current soil and climate conditions.') || 'under current soil and climate conditions.'}
          </p>
          <p style="margin-bottom:0;">
            ${t('The field profile shows adequate Nitrogen reserves') || 'The field profile shows adequate Nitrogen reserves'} (${N} kg/ha) ${t('but highlights below-optimal Phosphorus') || 'but highlights below-optimal Phosphorus'} (${P} kg/ha) ${t('and Potassium') || 'and Potassium'} (${K} kg/ha) ${t('levels. Applying the prescribed basal doses of MOP and DAP before sowing will correct these deficiencies, improve root establishment, and maximise climate resilience under prevailing conditions') || 'levels. Applying the prescribed basal doses of MOP and DAP before sowing will correct these deficiencies, improve root establishment, and maximise climate resilience under prevailing conditions'} (${temp}, ${humidity} ${t('Humidity') || 'humidity'}, ${weatherCond}).
          </p>
        </div>

        <div class="sec-heading" style="margin-top:20px;">7. ${t('Crop Disease Analysis & Pathology Screening')}</div>
        <div class="info-card" style="line-height:1.6; font-size:12.5px; color:#374151;">
          <strong>${t('Disease Screening Status')}:</strong> <span class="${isDisease ? 'red-text' : 'green-text'}">${isDisease ? t('Leaf Infection Detected') : t('Healthy / No Active Infection')}</span><br/>
          ${isDisease ? `
            <strong>${t('Detected Pathology')}:</strong> ${soilType}<br/>
            <strong>${t('AI Detection Confidence')}:</strong> ${confidence}%<br/>
            <strong>${t('Recommended Treatment')}:</strong> ${data.fertilizers?.[0]?.product || 'Apply copper-based fungicides.'}
          ` : `
            ${t('A convolutional neural network scanned the field crop leaf samples. No symptoms of Leaf Blight, Powdery Mildew, Rust Disease, Bacterial Wilt, Mosaic Virus, or Root Rot were identified. Leaf texture and chlorophyll indices are within the normal range.')}
          `}
        </div>

        <div class="disclaimer">
          ${t('Disclaimer')}: ${t('This report is generated by AgroAI for advisory purposes only. Always consult a certified agronomist.') || 'Disclaimer: This report is generated by AgroAI for advisory purposes only. Always consult a certified agronomist.'}
        </div>

        <div class="footer">
          <div>${t('Generated by AgroAI | www.agroai.in | Confidential Agricultural Advisory')}</div>
          <div>${t('Page')} 4 ${t('of')} 4</div>
        </div>
      </div>

      <script>
        window.onload = function() {
          window.print();
        };
      </script>
    </body>
    </html>
  `)
  printWindow.document.close()
}
