import { useState, useEffect } from 'react';
import { useLanguage } from '../contexts/LanguageContext';

// Language code mapping from website language codes to Sarvam AI language codes
const SARVAM_LANG_MAP: Record<string, string> = {
  en: 'en-IN',
  hi: 'hi-IN',
  te: 'te-IN',
  ta: 'ta-IN',
  kn: 'kn-IN',
  ml: 'ml-IN',
  mr: 'mr-IN',
  gu: 'gu-IN',
  bn: 'bn-IN',
  pa: 'pa-IN',
  or: 'or-IN',
  as: 'as-IN',
  ur: 'ur-IN',
  mai: 'mai-IN',
  mni: 'mni-IN',
  sat: 'sat-IN',
  brx: 'brx-IN',
  doi: 'doi-IN',
  ks: 'ks-IN',
  kok: 'kok-IN',
  ne: 'ne-IN',
  sa: 'sa-IN',
  sd: 'sd-IN',
};

// Pre-configured dictionary for instant offline Sarvam AI name & location transliterated output
const LOCAL_SARVAM_MAP: Record<string, Record<string, string>> = {
  "hi": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "मूल्यवान किसान",
    "Registered Farmer": "पंजीकृत किसान",
    "Farmer": "किसान",
    "Admin": "प्रशासक",
    "System Admin": "सिस्टम प्रशासक",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Tirupati": "तिरुपति",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपति, आंध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आंध्र प्रदेश, तिरुपति",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति जिला, आंध्र प्रदेश, भारत",
    "District": "जिला",
    "district": "जिला",
    "Tirupati District": "तिरुपति जिला",
    "Town": "शहर",
    "town": "शहर",
    "Ludhiana Town": "लुधियाना शहर",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंडीगढ़",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जलंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाड़ा",
    "Visakhapatnam": "विशाखापत्तनम",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपुर",
    "Kurnool": "कुरनूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लौर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "te": {
    "Ramyasree Ramayanam": "రమ్యాశ్రీ రామాయణం",
    "Ramyasree": "రమ్యాశ్రీ",
    "Rahul Ramayanam": "రాహుల్ రామాయణం",
    "Rahul": "రాహుల్",
    "Valued Farmer": "గౌరవనీయ రైతు",
    "Registered Farmer": "నమోదిత రైతు",
    "Farmer": "రైతు",
    "Admin": "అడ్మిన్",
    "System Admin": "సిస్టమ్ అడ్మిన్",
    "Andhra Pradesh": "ఆంధ్రప్రదేశ్",
    "Tirupati": "తిరుపతి",
    "Srikalahasthi": "శ్రీకాళహస్తి",
    "India": "భారతదేశం",
    "Tirupati, Andhra Pradesh": "తిరుపతి, ఆంధ్రప్రదేశ్",
    "Andhra Pradesh, Tirupati": "ఆంధ్రప్రదేశ్, తిరుపతి",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "శ్రీకాళహస్తి, తిరుపతి జిల్లా, ఆంధ్రప్రదేశ్, భారతదేశం",
    "District": "జిల్లా",
    "district": "జిల్లా",
    "Tirupati District": "తిరుపతి జిల్లా",
    "Town": "పట్టణం",
    "town": "పట్టణం",
    "Ludhiana Town": "లుధియానా పట్టణం",
    "Ludhiana": "లుధియానా",
    "Kotkapura": "కోట్కాపురా",
    "Nallabelly": "నల్లబెల్లి",
    "Wyra": "వైరా",
    "Faridkot": "ఫరీద్‌కోట్",
    "Warangal": "వరంగల్",
    "Chandigarh": "చండీగఢ్",
    "Amritsar": "అమృత్‌సర్",
    "Jalandhar": "జలంధర్",
    "Bathinda": "బటిండా",
    "Patiala": "పటియాలా",
    "Guntur": "గుంటూరు",
    "Vijayawada": "విజయవాడ",
    "Visakhapatnam": "విశాఖపట్నం",
    "Kakinada": "కాకినాడ",
    "Rajahmundry": "రాజమండ్రి",
    "Anantapur": "అనంతపురం",
    "Kurnool": "కర్నూలు",
    "Kadapa": "కడప",
    "Nellore": "నెల్లూరు",
    "Chittoor": "చిత్తూరు",
    "Ongole": "ఒంగోలు",
    "Eluru": "ఏలూరు",
    "Punjab": "పంజాబ్"
  },
  "ta": {
    "Ramyasree Ramayanam": "ரம்யாஸ்ரீ இராமாயணம்",
    "Ramyasree": "ரம்யாஸ்ரீ",
    "Rahul Ramayanam": "ராகுல் இராமாயணம்",
    "Rahul": "ராகுல்",
    "Valued Farmer": "மதிப்பிற்குரிய விவசாயி",
    "Registered Farmer": "பதிவுசெய்த விவசாயி",
    "Farmer": "விவசாயி",
    "Admin": "நிர்வாகி",
    "System Admin": "நிர்வாகி",
    "Andhra Pradesh": "ஆந்திரப் பிரதேசம்",
    "Tirupati": "திருப்பதி",
    "Srikalahasthi": "ஸ்ரீகாளஹஸ்தி",
    "India": "இந்தியா",
    "Tirupati, Andhra Pradesh": "திருப்பதி, ஆந்திரப் பிரதேசம்",
    "Andhra Pradesh, Tirupati": "ஆந்திரப் பிரதேசம், திருப்பதி",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "ஸ்ரீகாளஹஸ்தி, திருப்பதி மாவட்டம், ஆந்திரப் பிரதேசம், இந்தியா",
    "District": "மாவட்டம்",
    "district": "மாவட்டம்",
    "Tirupati District": "திருப்பதி மாவட்டம்",
    "Town": "நகரம்",
    "town": "நகரம்",
    "Ludhiana Town": "லூதியானா நகரம்",
    "Ludhiana": "லூதியானா",
    "Kotkapura": "கோட்காபுரா",
    "Nallabelly": "நல்லபெல்லி",
    "Wyra": "வைரா",
    "Faridkot": "பரீத்கோட்",
    "Warangal": "வரங்கல்",
    "Chandigarh": "சண்டிகர்",
    "Amritsar": "அமிர்தசரஸ்",
    "Jalandhar": "ஜலந்தர்",
    "Bathinda": "பட்டிண்டா",
    "Patiala": "பாட்டியாலா",
    "Guntur": "குண்டூர்",
    "Vijayawada": "விஜயவாடா",
    "Visakhapatnam": "விசாகப்பட்டினம்",
    "Kakinada": "காக்கிநாடா",
    "Rajahmundry": "ராஜமுந்திரி",
    "Anantapur": "அனந்தபூர்",
    "Kurnool": "கர்னூல்",
    "Kadapa": "கடப்பா",
    "Nellore": "நெல்லூர்",
    "Chittoor": "சித்தூர்",
    "Ongole": "ஒங்கோல்",
    "Eluru": "ஏலூரு",
    "Punjab": "பஞ்சாப்"
  },
  "kn": {
    "Ramyasree Ramayanam": "ರಮ್ಯಾಶ್ರೀ ರಾಮಾಯಣಂ",
    "Ramyasree": "ರಮ್ಯಾಶ್ರೀ",
    "Rahul Ramayanam": "ರಾಹುಲ್ ರಾಮಾಯಣಂ",
    "Rahul": "ರಾಹುಲ್",
    "Valued Farmer": "ಮೌಲ್ಯಯುತ ರೈತ",
    "Registered Farmer": "ನೋಂದಾಯಿತ ರೈತ",
    "Farmer": "ರೈತ",
    "Admin": "ಅಡ್ಮಿನ್",
    "System Admin": "ಅಡ್ಮಿನ್",
    "Andhra Pradesh": "ಆಂಧ್ರ ಪ್ರದೇಶ",
    "Tirupati": "ತಿರುಪತಿ",
    "Srikalahasthi": "ಶ್ರೀಕಾಳಹಸ್ತಿ",
    "India": "ಭಾರತ",
    "Tirupati, Andhra Pradesh": "ತಿರುಪತಿ, ಆಂಧ್ರ ಪ್ರದೇಶ",
    "Andhra Pradesh, Tirupati": "ಆಂಧ್ರ ಪ್ರದೇಶ, ತಿರುಪತಿ",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "ಶ್ರೀಕಾಳಹಸ್ತಿ, ತಿರುಪತಿ ಜಿಲ್ಲೆ, ಆಂಧ್ರ ಪ್ರದೇಶ, ಭಾರತ",
    "District": "ಜಿಲ್ಲೆ",
    "district": "ಜಿಲ್ಲೆ",
    "Tirupati District": "ತಿರುಪತಿ ಜಿಲ್ಲೆ",
    "Town": "ಪಟ್ಟಣ",
    "town": "ಪಟ್ಟಣ",
    "Ludhiana Town": "ಲುಧಿಯಾನ ಪಟ್ಟಣ",
    "Ludhiana": "ಲುಧಿಯಾನ",
    "Kotkapura": "ಕೋಟ್ಕಾಪುರಾ",
    "Nallabelly": "ನಲ್ಲಬೆಲ್ಲಿ",
    "Wyra": "ವೈರಾ",
    "Faridkot": "ಫರೀದ್ಕೋಟ್",
    "Warangal": "ವರಂಗಲ್",
    "Chandigarh": "ಚಂಡೀಗಢ",
    "Amritsar": "ಅಮೃತಸರ",
    "Jalandhar": "ಜಲಂಧರ್",
    "Bathinda": "ಬಟಿಂಡಾ",
    "Patiala": "ಪಟಿಯಾಲ",
    "Guntur": "ಗುಂಟೂರು",
    "Vijayawada": "ವಿಜಯವಾಡ",
    "Visakhapatnam": "ವಿಶಾಖಪಟ್ನಂ",
    "Kakinada": "ಕಾಕಿನಾಡ",
    "Rajahmundry": "ರಾಜಮಂಡ್ರಿ",
    "Anantapur": "ಅನಂತಪುರ",
    "Kurnool": "ಕರ್ನೂಲು",
    "Kadapa": "ಕಡಪ",
    "Nellore": "ನೆಲ್ಲೂರು",
    "Chittoor": "ಚಿತ್ತೂರು",
    "Ongole": "ಒಂಗೋಲ್",
    "Eluru": "ಏಲೂರು",
    "Punjab": "ಪಂಜಾಬ್"
  },
  "ml": {
    "Ramyasree Ramayanam": "രമ്യാശ്രീ രാമായണം",
    "Ramyasree": "രമ്യാശ്രീ",
    "Rahul Ramayanam": "രാഹുൽ രാമായണം",
    "Rahul": "രാഹുൽ",
    "Valued Farmer": "പ്രിയപ്പെട്ട കർഷകൻ",
    "Registered Farmer": "രജിസ്റ്റർ ചെയ്ത കർഷകൻ",
    "Farmer": "കർഷകൻ",
    "Admin": "അഡ്മിൻ",
    "System Admin": "അഡ്മിൻ",
    "Andhra Pradesh": "ആന്ധ്രാപ്രദേശ്",
    "Tirupati": "തിരുപ്പതി",
    "Srikalahasthi": "ശ്രീകാളഹസ്തി",
    "India": "ഇന്ത്യ",
    "Tirupati, Andhra Pradesh": "തിരുപ്പതി, ആന്ധ്രാപ്രദേശ്",
    "Andhra Pradesh, Tirupati": "ആന്ധ്രാപ്രദേശ്, തിരുപ്പതി",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "ശ്രീകാളഹസ്തി, തിരുപ്പതി ജില്ല, ആന്ധ്രാപ്രദേശ്, ഇന്ത്യ",
    "District": "ജില്ല",
    "district": "ജില്ല",
    "Tirupati District": "തിരുപ്പതി ജില്ല",
    "Town": "ടൗൺ",
    "town": "ടൗൺ",
    "Ludhiana Town": "ലൂധിയാന ടൗൺ",
    "Ludhiana": "ലൂധിയാന",
    "Kotkapura": "കോട്കാപുര",
    "Nallabelly": "നല്ലബെല്ലി",
    "Wyra": "വൈറ",
    "Faridkot": "ഫരീദ്കോട്ട്",
    "Warangal": "വാറങ്കൽ",
    "Chandigarh": "ചണ്ഡിഗഢ്",
    "Amritsar": "അമൃതസർ",
    "Jalandhar": "ജലന്ധർ",
    "Bathinda": "ഭട്ടിൻഡ",
    "Patiala": "പട്യാല",
    "Guntur": "ഗുണ്ടൂർ",
    "Vijayawada": "വിജയവാഡ",
    "Visakhapatnam": "വിശാഖപട്ടണം",
    "Kakinada": "കാക്കിനട",
    "Rajahmundry": "രാജമുണ്ട്രി",
    "Anantapur": "അനന്തപൂർ",
    "Kurnool": "കർണൂൽ",
    "Kadapa": "കഡപ്പ",
    "Nellore": "നെല്ലൂർ",
    "Chittoor": "ചിറ്റൂർ",
    "Ongole": "ഒങ്കോൾ",
    "Eluru": "ഏലൂര്",
    "Punjab": "പഞ്ചാബ്"
  },
  "mr": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "सन्माननीय शेतकरी",
    "Registered Farmer": "नोंदणीकृत शेतकरी",
    "Farmer": "शेतकरी",
    "Admin": "प्रशासक",
    "System Admin": "सिस्टम प्रशासक",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Tirupati": "तिरुपती",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपती, आंध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आंध्र प्रदेश, तिरुपती",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपती जिल्हा, आंध्र प्रदेश, भारत",
    "District": "जिल्हा",
    "district": "जिल्हा",
    "Tirupati District": "तिरुपती जिल्हा",
    "Town": "शहर",
    "town": "शहर",
    "Ludhiana Town": "लुधियाना शहर",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंदिगढ",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जालंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाडा",
    "Visakhapatnam": "विशाखापट्टणम",
    "Kakinada": "काकिनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपूर",
    "Kurnool": "कुर्नूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लोर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "bn": {
    "Ramyasree Ramayanam": "রম্যাশ্রী রামায়ণম",
    "Ramyasree": "রম্যাশ্রী",
    "Rahul Ramayanam": "রাহুল রামায়ণম",
    "Rahul": "রাহুল",
    "Valued Farmer": "সম্মানিত কৃষক",
    "Registered Farmer": "নিবন্ধিত কৃষক",
    "Farmer": "কৃষক",
    "Admin": "এডমিন",
    "System Admin": "এডমিন",
    "Andhra Pradesh": "অন্ধ্রপ্রদেশ",
    "Tirupati": "তিরুপতি",
    "Srikalahasthi": "শ্রীকালহস্তী",
    "India": "ভারত",
    "Tirupati, Andhra Pradesh": "তিরুপতি, অন্ধ্রপ্রদেশ",
    "Andhra Pradesh, Tirupati": "অন্ধ্রপ্রদেশ, তিরুপতি",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "শ্রীকালহস্তী, তিরুপতি জেলা, অন্ধ্রপ্রদেশ, ভারত",
    "District": "জেলা",
    "district": "জেলা",
    "Tirupati District": "তিরুপতি জেলা",
    "Town": "শহর",
    "town": "শহর",
    "Ludhiana Town": "লুধিয়ানা শহর",
    "Ludhiana": "লুধিয়ানা",
    "Kotkapura": "কোটকাপুরা",
    "Nallabelly": "নাল্লাবেল্লি",
    "Wyra": "ওয়াইরা",
    "Faridkot": "ফরিদকোট",
    "Warangal": "ওয়ারঙ্গল",
    "Chandigarh": "চণ্ডীগড়",
    "Amritsar": "অমৃতসর",
    "Jalandhar": "জলন্ধর",
    "Bathinda": "ভাটিন্ডা",
    "Patiala": "পাতিয়ালা",
    "Guntur": "গুন্টুর",
    "Vijayawada": "বিজয়ওয়াড়া",
    "Visakhapatnam": "বিশাখাপত্তনম",
    "Kakinada": "কাকিনাড়া",
    "Rajahmundry": "রাজামুন্দ্রি",
    "Anantapur": "অনন্তপুর",
    "Kurnool": "কুরনুল",
    "Kadapa": "কাডাপা",
    "Nellore": "নেল্লোর",
    "Chittoor": "চিত্তুর",
    "Ongole": "ওঙ্গোল",
    "Eluru": "এলুরু",
    "Punjab": "পাঞ্জাব"
  },
  "gu": {
    "Ramyasree Ramayanam": "રમ્યાશ્રી રામાયણમ",
    "Ramyasree": "રમ્યાશ્રી",
    "Rahul Ramayanam": "રાહુલ રામાયણમ",
    "Rahul": "રાહુલ",
    "Valued Farmer": "આદરણીય ખેડૂત",
    "Registered Farmer": "નોંધાયેલ ખેડૂત",
    "Farmer": "ખેડૂત",
    "Admin": "એડમિન",
    "System Admin": "એડમિન",
    "Andhra Pradesh": "આંધ્રપ્રદેશ",
    "Tirupati": "તિરુપતિ",
    "Srikalahasthi": "શ્રીકાલહસ્તી",
    "India": "ભારત",
    "Tirupati, Andhra Pradesh": "તિરુપતિ, આંધ્રપ્રદેશ",
    "Andhra Pradesh, Tirupati": "આંધ્રપ્રદેશ, તિરુપતિ",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "શ્રીકાલહસ્તી, તિરુપતિ જિલ્લો, આંધ્રપ્રદેશ, ભારત",
    "District": "જિલ્લો",
    "district": "જિલ્લો",
    "Tirupati District": "તિરુપતિ જિલ્લો",
    "Town": "ટાઉન",
    "town": "ટાઉન",
    "Ludhiana Town": "લુધિયાણા ટાઉન",
    "Ludhiana": "લુધિયાણા",
    "Kotkapura": "કોટકપુરા",
    "Nallabelly": "નલ્લાબેલી",
    "Wyra": "વાયરા",
    "Faridkot": "ફરીદકોટ",
    "Warangal": "વરંગલ",
    "Chandigarh": "ચંડીગઢ",
    "Amritsar": "અમૃતસર",
    "Jalandhar": "જલંધર",
    "Bathinda": "બઠિંડા",
    "Patiala": "પટિયાલા",
    "Guntur": "ગુંટૂર",
    "Vijayawada": "વિજયવાડા",
    "Visakhapatnam": "વિશાખાપટ્ટનમ",
    "Kakinada": "કાકીનાડા",
    "Rajahmundry": "રાજમુંદ્રી",
    "Anantapur": "અનંતપુર",
    "Kurnool": "કુરનૂલ",
    "Kadapa": "કડપા",
    "Nellore": "નેલ્લોર",
    "Chittoor": "ચિત્તૂર",
    "Ongole": "ઓંગોલ",
    "Eluru": "એલુરુ",
    "Punjab": "પંજાબ"
  },
  "pa": {
    "Ramyasree Ramayanam": "ਰਮਿਆਸ਼੍ਰੀ ਰਾਮਾਇਣਮ",
    "Ramyasree": "ਰਮਿਆਸ਼੍ਰੀ",
    "Rahul Ramayanam": "ਰਾਹੁਲ ਰਾਮਾਇਣਮ",
    "Rahul": "ਰਾਹੁਲ",
    "Valued Farmer": "ਸਤਿਕਾਰਯੋਗ ਕਿਸਾਨ",
    "Registered Farmer": "ਰਜਿਸਟਰਡ ਕਿਸਾਨ",
    "Farmer": "ਕਿਸਾਨ",
    "Admin": "ਐਡਮਿਨ",
    "System Admin": "ਐਡਮਿਨ",
    "Andhra Pradesh": "ਆਧ੍ਰ ਪ੍ਰਦੇਸ਼",
    "Tirupati": "ਤਿਰੁਪਤੀ",
    "Srikalahasthi": "ਸ੍ਰੀਕਾਲਹਸਤੀ",
    "India": "ਭਾਰਤ",
    "Tirupati, Andhra Pradesh": "ਤਿਰੁਪਤੀ, ਆਧ੍ਰ ਪ੍ਰਦੇਸ਼",
    "Andhra Pradesh, Tirupati": "ਆਧ੍ਰ ਪ੍ਰਦੇਸ਼, ਤਿਰੁਪਤੀ",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "ਸ੍ਰੀਕਾਲਹਸਤੀ, ਤਿਰੁਪਤੀ ਜ਼ਿਲ੍ਹਾ, ਆਧ੍ਰ ਪ੍ਰਦੇਸ਼, ਭਾਰਤ",
    "District": "ਜ਼ਿਲ੍ਹਾ",
    "district": "ਜ਼ਿਲ੍ਹਾ",
    "Tirupati District": "ਤਿਰੁਪਤੀ ਜ਼ਿਲ੍ਹਾ",
    "Town": "ਕਸਬਾ",
    "town": "ਕਸਬਾ",
    "Ludhiana Town": "ਲੁਧਿਆਣਾ ਕਸਬਾ",
    "Ludhiana": "ਲੁਧਿਆਣਾ",
    "Kotkapura": "ਕੋਟਕਪੂਰਾ",
    "Nallabelly": "ਨੱਲਾਬੇਲੀ",
    "Wyra": "ਵਾਇਰਾ",
    "Faridkot": "ਫਰੀਦਕੋਟ",
    "Warangal": "ਵਰੰਗਲ",
    "Chandigarh": "ਚੰਡੀਗੜ੍ਹ",
    "Amritsar": "ਅੰਮ੍ਰਿਤਸਰ",
    "Jalandhar": "ਜਲੰਧਰ",
    "Bathinda": "ਬਠਿੰਡਾ",
    "Patiala": "ਪਟਿਆਲਾ",
    "Guntur": "ਗੁੰਟੂਰ",
    "Vijayawada": "ਵਿਜੇਵਾੜਾ",
    "Visakhapatnam": "ਵਿਸ਼ਾਖਾਪਟਨਮ",
    "Kakinada": "ਕਾਕੀਨਾੜਾ",
    "Rajahmundry": "ਰਾਜਮੁੰਦਰੀ",
    "Anantapur": "ਅਨੰਤਪੁਰ",
    "Kurnool": "ਕਰਨੂਲ",
    "Kadapa": "ਕਡਪਾ",
    "Nellore": "ਨੇਲੋਰ",
    "Chittoor": "ਚਿਤੂਰ",
    "Ongole": "ਓਂਗੋਲ",
    "Eluru": "ਏਲੂਰੂ",
    "Punjab": "ਪੰਜਾਬ"
  },
  "or": {
    "Ramyasree Ramayanam": "ରମ୍ୟାଶ୍ରୀ ରାମାୟଣମ୍",
    "Ramyasree": "ରମ୍ୟାଶ୍ରୀ",
    "Rahul Ramayanam": "ରାହୁଲ ରାମାୟଣମ୍",
    "Rahul": "ରାହୁଲ",
    "Valued Farmer": "ସମ୍ମାନିତ କୃଷକ",
    "Registered Farmer": "ପଞ୍ଜୀକୃତ କୃଷକ",
    "Farmer": "କୃଷକ",
    "Admin": "ଆଡମିନ୍",
    "System Admin": "ଆଡମିନ୍",
    "Andhra Pradesh": "ଆନ୍ଧ୍ରପ୍ରଦେଶ",
    "Tirupati": "ତିରୁପତି",
    "Srikalahasthi": "ଶ୍ରୀକାଳହସ୍ତୀ",
    "India": "ଭାରତ",
    "Tirupati, Andhra Pradesh": "ତିରୁପତି, ଆନ୍ଧ୍ରପ୍ରଦେଶ",
    "Andhra Pradesh, Tirupati": "ଆନ୍ଧ୍ରପ୍ରଦେଶ, ତିରୁପତି",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "ଶ୍ରୀକାଳହସ୍ତୀ, ତିରୁପତି ଜିଲ୍ଲା, ଆନ୍ଧ୍ରପ୍ରଦେଶ, ଭାରତ",
    "District": "ଜିଲ୍ଲା",
    "district": "ଜିଲ୍ଲା",
    "Tirupati District": "ତିରୁପତି ଜିଲ୍ଲା",
    "Town": "ସହର",
    "town": "ସହର",
    "Ludhiana Town": "ଲୁଧିଆନା ସହର",
    "Ludhiana": "ଲୁଧିଆନା",
    "Kotkapura": "କୋଟକାପୁରା",
    "Nallabelly": "ନଲ୍ଲାବେଲି",
    "Wyra": "ୱାଇରା",
    "Faridkot": "ଫରିଦକୋଟ",
    "Warangal": "ୱାରଙ୍ଗଲ",
    "Chandigarh": "ଚଣ୍ଡୀଗଡ଼",
    "Amritsar": "ଅମୃତସର",
    "Jalandhar": "ଜଲନ୍ଧର",
    "Bathinda": "ବଠିଣ୍ଡା",
    "Patiala": "ପଟିଆଲା",
    "Guntur": "ଗୁଣ୍ଟୁର",
    "Vijayawada": "ବିଜୟୱାଡ଼ା",
    "Visakhapatnam": "ବିଶାଖାପାଟଣା",
    "Kakinada": "କାକିନାଡ଼ା",
    "Rajahmundry": "ରାଜମୁନ୍ଦ୍ରୀ",
    "Anantapur": "ଅନନ୍ତପୁର",
    "Kurnool": "କର୍ନୁଲ",
    "Kadapa": "କଡ଼ପା",
    "Nellore": "ନେଲୋର",
    "Chittoor": "ଚିତ୍ତୋର",
    "Ongole": "ଓଙ୍ଗୋଲ",
    "Eluru": "ଏଲୁରୁ",
    "Punjab": "ପଞ୍ଜାବ"
  },
  "as": {
    "Ramyasree Ramayanam": "ৰম্যাশ্ৰী ৰামায়ণম",
    "Ramyasree": "ৰম্যাশ্ৰী",
    "Rahul Ramayanam": "ৰাহুল ৰামায়ণম",
    "Rahul": "ৰাহুল",
    "Valued Farmer": "শ্ৰদ্ধাৰ কৃষক",
    "Registered Farmer": "পঞ্জীয়নভুক্ত কৃষক",
    "Farmer": "কৃষক",
    "Admin": "এডমিন",
    "System Admin": "এডমিন",
    "Andhra Pradesh": "অন্ধ্ৰপ্ৰদেশ",
    "Tirupati": "তিৰুপতি",
    "Srikalahasthi": "শ্ৰীকান্নহস্তী",
    "India": "ভাৰত",
    "Tirupati, Andhra Pradesh": "তিৰুপতি, অন্ধ্ৰপ্ৰদেশ",
    "Andhra Pradesh, Tirupati": "অন্ধ্ৰপ্ৰদেশ, তিৰুপতি",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "শ্ৰীকান্নহস্তী, তিৰুপতি জিলা, অন্ধ্ৰপ্ৰদেশ, ভাৰত",
    "District": "জিলা",
    "district": "জিলা",
    "Tirupati District": "তিৰুপতি জিলা",
    "Town": "চহৰ",
    "town": "চহৰ",
    "Ludhiana Town": "লুধিয়ানা চহৰ",
    "Ludhiana": "লুধিয়ানা",
    "Kotkapura": "কোটকাপুৰা",
    "Nallabelly": "নাল্লাবেল্লি",
    "Wyra": "ৱাইৰা",
    "Faridkot": "ফৰিদকোট",
    "Warangal": "ৱাৰংগল",
    "Chandigarh": "চণ্ডীগড়",
    "Amritsar": "অমৃতসৰ",
    "Jalandhar": "জালন্ধৰ",
    "Bathinda": "বাথিন্দা",
    "Patiala": "পাতিয়ালা",
    "Guntur": "গুন্টুৰ",
    "Vijayawada": "বিজয়ৱাড়া",
    "Visakhapatnam": "বিাখাপাটনাম",
    "Kakinada": "কাকিনাড়া",
    "Rajahmundry": "ৰাজামুন্দ্রী",
    "Anantapur": "অনন্তপুৰ",
    "Kurnool": "কুৰ্ণুল",
    "Kadapa": "কাদাপা",
    "Nellore": "নেল্লোৰ",
    "Chittoor": "চিত্তুৰ",
    "Ongole": "ওংগোল",
    "Eluru": "এলুৰু",
    "Punjab": "পঞ্জাৱ"
  },
  "ur": {
    "Ramyasree Ramayanam": "ر میاشری راماینم",
    "Ramyasree": "ر میاشری",
    "Rahul Ramayanam": "راہل راماینم",
    "Rahul": "راہل",
    "Valued Farmer": "محترم کسان",
    "Registered Farmer": "رجسٹرڈ کسان",
    "Farmer": "کسان",
    "Admin": "ایڈمن",
    "System Admin": "ایڈمن",
    "Andhra Pradesh": "آندھرا پردیش",
    "Tirupati": "تیرپتی",
    "Srikalahasthi": "سریکالہستی",
    "India": "بھارت",
    "Tirupati, Andhra Pradesh": "تیرپتی، آندھرا پردیش",
    "Andhra Pradesh, Tirupati": "آندھرا پردیش، تیرپتی",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "سریکالہستی، تیرپتی ضلع، آندھرا پردیش، بھارت",
    "District": "ضلع",
    "district": "ضلع",
    "Tirupati District": "تیرپتی ضلع",
    "Town": "ٹاؤن",
    "town": "ٹاؤن",
    "Ludhiana Town": "لودھیانہ ٹاؤن",
    "Ludhiana": "لودھیانہ",
    "Kotkapura": "کوٹکپورہ",
    "Nallabelly": "نلا بیلی",
    "Wyra": "وائرا",
    "Faridkot": "فریدکوٹ",
    "Warangal": "ورنگل",
    "Chandigarh": "چندی گڑھ",
    "Amritsar": "امرتسر",
    "Jalandhar": "جالندھر",
    "Bathinda": "بھٹنڈہ",
    "Patiala": "پٹیالہ",
    "Guntur": "گنٹور",
    "Vijayawada": "وجئے واڑہ",
    "Visakhapatnam": "وشاکھاپٹنم",
    "Kakinada": "کاکیناڈا",
    "Rajahmundry": "راجمنڈری",
    "Anantapur": "اننت پور",
    "Kurnool": "کرنول",
    "Kadapa": "کڈپہ",
    "Nellore": "نیلور",
    "Chittoor": "چتور",
    "Ongole": "اونگول",
    "Eluru": "ایلورو",
    "Punjab": "پنجاب"
  },
  "mai": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "आदरणीय किसान",
    "Registered Farmer": "पंजीकृत किसान",
    "Farmer": "किसान",
    "Admin": "एडमिन",
    "System Admin": "एडमिन",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Tirupati": "तिरुपति",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपति, आंध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आंध्र प्रदेश, तिरुपति",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति जिला, आंध्र प्रदेश, भारत",
    "District": "जिला",
    "district": "जिला",
    "Tirupati District": "तिरुपति जिला",
    "Town": "शहर",
    "town": "शहर",
    "Ludhiana Town": "लुधियाना शहर",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंडीगढ़",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जलंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाड़ा",
    "Visakhapatnam": "विशाखापत्तनम",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपुर",
    "Kurnool": "कुरनूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लौर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "mni": {
    "Ramyasree Ramayanam": "રમ્યાશ્રી રામાયણમ",
    "Ramyasree": "રમ્યાશ્રી",
    "Rahul Ramayanam": "રાહુલ રામાયણમ",
    "Rahul": "રાહુલ",
    "Valued Farmer": "ইকায়খুম্নজরবা লৌমী",
    "Registered Farmer": "রেজিস্তর তৌবা লৌমী",
    "Farmer": "লৌমী",
    "Admin": "এদমিন",
    "System Admin": "এদমিন",
    "Andhra Pradesh": "આંધ્રપ્રદેશ",
    "Tirupati": "તિરુપતિ",
    "Srikalahasthi": "શ્રીકાલહસ્તી",
    "India": "ભારત",
    "Tirupati, Andhra Pradesh": "તિરુપતિ, આંધ્રપ્રદેશ",
    "Andhra Pradesh, Tirupati": "આંધ્રપ્રદેશ, તિરુપતિ",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "શ્રીકાલહસ્તી, તિરુપતિ જિલ્લો, આંધ્રપ્રદેશ, ભારત",
    "District": "জিল্লা",
    "district": "জিল্লা",
    "Tirupati District": "તિરુપતિ জিল্লা",
    "Town": "તાઉન",
    "town": "તાઉન",
    "Ludhiana Town": "લુધિયાણા તાઉન",
    "Ludhiana": "લુધિયાણા",
    "Kotkapura": "કોટકપુરા",
    "Nallabelly": "નલ્લાબેલી",
    "Wyra": "વાયરા",
    "Faridkot": "ફરીદકોટ",
    "Warangal": "વરંગલ",
    "Chandigarh": "ચંડીગઢ",
    "Amritsar": "અમૃતસર",
    "Jalandhar": "જલંધર",
    "Bathinda": "બઠિંડા",
    "Patiala": "પટિયાલા",
    "Guntur": "ગુંટૂર",
    "Vijayawada": "વિજયવાડા",
    "Visakhapatnam": "વિશાખાપટ્ટનમ",
    "Kakinada": "કાકીનાડા",
    "Rajahmundry": "રાજમુંદ્રી",
    "Anantapur": "અનંતપુર",
    "Kurnool": "કુરનૂલ",
    "Kadapa": "કડપા",
    "Nellore": "નેલ્લોર",
    "Chittoor": "ચિત્તૂર",
    "Ongole": "ઓંગોલ",
    "Eluru": "એલુરુ",
    "Punjab": "પંજાબ"
  },
  "sat": {
    "Ramyasree Ramayanam": " ᱨ ᱟ ᱢ ᱭ ᱟ ᱥ ᱨ ᱤ ᱨ ᱟ ᱢ ᱟ ᱭ ᱟ ᱱ ᱟ ᱢ",
    "Ramyasree": " ᱨ ᱟ ᱢ ᱭ ᱟ ᱥ ᱨ ᱤ",
    "Rahul Ramayanam": " ᱨ ᱟ ᱦ ᱩ ᱞ ᱨ ᱟ ᱢ ᱟ ᱭ ᱟ ᱱ ᱟ ᱢ",
    "Rahul": " ᱨ ᱟ ᱦ ᱩ ᱞ",
    "Valued Farmer": " ᱪ ᱟ ᱥ ᱤ",
    "Registered Farmer": " ᱪ ᱟ ᱥ ᱤ",
    "Farmer": " ᱪ ᱟ ᱥ ᱤ",
    "Admin": " ᱮ ᱰ ᱢ ᱤ ᱱ",
    "System Admin": " ᱮ ᱰ ᱢ ᱤ ᱱ",
    "Andhra Pradesh": " ᱟ ᱱ ᱫ ᱷ ᱨ ᱟ  ᱯ ᱨ ᱟ ᱫ ᱮ ᱥ",
    "Tirupati": " ᱛ ᱤ ᱨ ᱩ ᱯ ᱟ ᱴ ᱤ",
    "Srikalahasthi": " ᱥ ᱨ ᱤ ᱠ ᱟ ᱞ ᱟ ᱦ ᱟ ᱥ ᱛ ᱤ",
    "India": " ᱵ ᱟ ᱨ ᱚ ᱛ",
    "Tirupati, Andhra Pradesh": " ᱛ ᱤ ᱨ ᱩ ᱯ ᱟ ᱴ ᱤ,  ᱟ ᱱ ᱫ ᱷ ᱨ ᱟ  ᱯ ᱨ ᱟ ᱫ ᱮ ᱥ",
    "Andhra Pradesh, Tirupati": " ᱟ ᱱ ᱫ ᱷ ᱨ ᱟ  ᱯ ᱨ ᱟ ᱫ ᱮ ᱥ,  ᱛ ᱤ ᱨ ᱩ ᱯ ᱟ ᱴ ᱤ",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": " ᱥ ᱨ ᱤ ᱠ ᱟ ᱞ ᱟ ᱦ ᱟ ᱥ ᱛ ᱤ,  ᱛ ᱤ ᱨ ᱩ ᱯ ᱟ ᱴ ᱤ,  ᱟ ᱱ ᱫ ᱷ ᱨ ᱟ  ᱯ ᱨ ᱟ ᱫ ᱮ ᱥ,  ᱵ ᱟ ᱨ ᱚ ᱛ",
    "District": " district",
    "district": " district",
    "Tirupati District": " ᱛ ᱤ ᱨ ᱩ ᱯ ᱟ ᱴ ᱤ  district",
    "Town": " town",
    "town": " town",
    "Ludhiana Town": " Ludhiana town",
    "Ludhiana": " Ludhiana",
    "Kotkapura": " Kotkapura",
    "Nallabelly": " Nallabelly",
    "Wyra": " Wyra",
    "Faridkot": " Faridkot",
    "Warangal": " Warangal",
    "Chandigarh": " Chandigarh",
    "Amritsar": " Amritsar",
    "Jalandhar": " Jalandhar",
    "Bathinda": " Bathinda",
    "Patiala": " Patiala",
    "Guntur": " Guntur",
    "Vijayawada": " Vijayawada",
    "Visakhapatnam": " Visakhapatnam",
    "Kakinada": " Kakinada",
    "Rajahmundry": " Rajahmundry",
    "Anantapur": " Anantapur",
    "Kurnool": " Kurnool",
    "Kadapa": " Kadapa",
    "Nellore": " Nellore",
    "Chittoor": " Chittoor",
    "Ongole": " Ongole",
    "Eluru": " Eluru",
    "Punjab": " Punjab"
  },
  "brx": {
    "Ramyasree Ramayanam": "रम्यास्री रामायणम",
    "Ramyasree": "रम्यास्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "मानगोनां आबादफारि",
    "Registered Farmer": "रजिस्टार आबादफारि",
    "Farmer": "आबादफारि",
    "Admin": "एडमिन",
    "System Admin": "एडमिन",
    "Andhra Pradesh": "आन्ध्र प्रदेश",
    "Tirupati": "तिरुपति",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपति, आन्ध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आन्ध्र प्रदेश, तिरुपति",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति जिल्ला, आन्ध्र प्रदेश, भारत",
    "District": "जिल्ला",
    "district": "जिल्ला",
    "Tirupati District": "तिरुपति जिल्ला",
    "Town": "टाउन",
    "town": "टाउन",
    "Ludhiana Town": "लुधियाना टाउन",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंडीगढ़",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जलंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाड़ा",
    "Visakhapatnam": "विशाखापत्तनम",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपुर",
    "Kurnool": "कुरनूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लौर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "doi": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "आदरणीय किसान",
    "Registered Farmer": "पंजीकृत किसान",
    "Farmer": "किसान",
    "Admin": "एडमिन",
    "System Admin": "एडमिन",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Tirupati": "तिरुपति",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपति, आंध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आंध्र प्रदेश, तिरुपति",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति जिला, आंध्र प्रदेश, भारत",
    "District": "जिला",
    "district": "जिला",
    "Tirupati District": "तिरुपति जिला",
    "Town": "शहर",
    "town": "शहर",
    "Ludhiana Town": "लुधियाना शहर",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंडीगढ़",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जलंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाड़ा",
    "Visakhapatnam": "विशाखापत्तनम",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपुर",
    "Kurnool": "कुरनूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लौर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "ks": {
    "Ramyasree Ramayanam": "رمیاشری راماینم",
    "Ramyasree": "رمیاشری",
    "Rahul Ramayanam": "راہل راماینم",
    "Rahul": "راہل",
    "Valued Farmer": "جان زمیندار",
    "Registered Farmer": "رجسٹرڈ زمیندار",
    "Farmer": "زمیندار",
    "Admin": "ایڈمن",
    "System Admin": "ایڈمن",
    "Andhra Pradesh": "آندھرا پردیش",
    "Tirupati": "تیرپتی",
    "Srikalahasthi": "سریکالہستی",
    "India": "ہندوستان",
    "Tirupati, Andhra Pradesh": "تیرپتی، آندھرا پردیش",
    "Andhra Pradesh, Tirupati": "آندھرا پردیش، تیرپتی",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "سریکالہستی، تیرپتی ضلع، آندھرا پردیش، ہندوستان",
    "District": "ضلع",
    "district": "ضلع",
    "Tirupati District": "تیرپتی ضلع",
    "Town": "ٹاؤن",
    "town": "ٹاؤن",
    "Ludhiana Town": "لودھیانہ ٹاؤن",
    "Ludhiana": "لودھیانہ",
    "Kotkapura": "کوٹکپورہ",
    "Nallabelly": "نلا بیلی",
    "Wyra": "وائرا",
    "Faridkot": "فریدکوٹ",
    "Warangal": "ورنگل",
    "Chandigarh": "چندی گڑھ",
    "Amritsar": "امرتسر",
    "Jalandhar": "جالندھر",
    "Bathinda": "بھٹنڈہ",
    "Patiala": "پٹیالہ",
    "Guntur": "گنٹور",
    "Vijayawada": "وجئے واڑہ",
    "Visakhapatnam": "وشاکھاپٹنم",
    "Kakinada": "کاکیناڈا",
    "Rajahmundry": "راجمنڈری",
    "Anantapur": "اننت پور",
    "Kurnool": "کرنول",
    "Kadapa": "کڈپہ",
    "Nellore": "نیلور",
    "Chittoor": "چتور",
    "Ongole": "اونگول",
    "Eluru": "ایلورو",
    "Punjab": "پنجاب"
  },
  "kok": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "मानेस्त शेतकार",
    "Registered Farmer": "नोंदणीकृत शेतकार",
    "Farmer": "शेतकार",
    "Admin": "ॲडमिन",
    "System Admin": "ॲडमिन",
    "Andhra Pradesh": "आंध्र प्रदेश",
    "Tirupati": "तिरुपती",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपती, आंध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आंध्र प्रदेश, तिरुपती",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपती जिल्हा, आंध्र प्रदेश, भारत",
    "District": "जिल्हो",
    "district": "जिल्हो",
    "Tirupati District": "तिरुपती जिल्हो",
    "Town": "शार",
    "town": "शार",
    "Ludhiana Town": "लुधियाना शार",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंदिगढ",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जालंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाडा",
    "Visakhapatnam": "विशाखापट्टणम",
    "Kakinada": "काकिनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपूर",
    "Kurnool": "कुर्नूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लोर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "ne": {
    "Ramyasree Ramayanam": "रम्याश्री रामायणम",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुल रामायणम",
    "Rahul": "राहुल",
    "Valued Farmer": "आदरणीय किसान",
    "Registered Farmer": "दर्ता भएका किसान",
    "Farmer": "किसान",
    "Admin": "एडमिन",
    "System Admin": "एडमिन",
    "Andhra Pradesh": "आन्ध्र प्रदेश",
    "Tirupati": "तिरुपति",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारत",
    "Tirupati, Andhra Pradesh": "तिरुपति, आन्ध्र प्रदेश",
    "Andhra Pradesh, Tirupati": "आन्ध्र प्रदेश, तिरुपति",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति जिल्ला, आन्ध्र प्रदेश, भारत",
    "District": "जिल्ला",
    "district": "जिल्ला",
    "Tirupati District": "तिरुपति जिल्ला",
    "Town": "नगर",
    "town": "नगर",
    "Ludhiana Town": "लुधियाना नगर",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चंडीगढ़",
    "Amritsar": "अमृतसर",
    "Jalandhar": "जलंधर",
    "Bathinda": "बठिंडा",
    "Patiala": "पटियाला",
    "Guntur": "गुंटूर",
    "Vijayawada": "विजयवाड़ा",
    "Visakhapatnam": "विशाखापत्तनम",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमुंद्री",
    "Anantapur": "अनंतपुर",
    "Kurnool": "कुरनूल",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लौर",
    "Chittoor": "चित्तूर",
    "Ongole": "ओंगोल",
    "Eluru": "एलुरु",
    "Punjab": "पंजाब"
  },
  "sa": {
    "Ramyasree Ramayanam": "रम्याश्रीरामायणम्",
    "Ramyasree": "रम्याश्री",
    "Rahul Ramayanam": "राहुलरामायणम्",
    "Rahul": "राहुलः",
    "Valued Farmer": "आदरणीयकृषकः",
    "Registered Farmer": "पञ्जीकृतकृषकः",
    "Farmer": "कृषकः",
    "Admin": "प्रशासकः",
    "System Admin": "प्रशासकः",
    "Andhra Pradesh": "आन्ध्रप्रदेशः",
    "Tirupati": "तिरुपतिः",
    "Srikalahasthi": "श्रीकालहस्ती",
    "India": "भारतम्",
    "Tirupati, Andhra Pradesh": "तिरुपतिः, आन्ध्रप्रदेशः",
    "Andhra Pradesh, Tirupati": "आन्ध्रप्रदेशः, तिरुपतिः",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "श्रीकालहस्ती, तिरुपति-मण्डलम्, आन्ध्रप्रदेशः, भारतम्",
    "District": "मण्डलम्",
    "district": "मण्डलम्",
    "Tirupati District": "तिरुपतिः मण्डलम्",
    "Town": "नगरम्",
    "town": "नगरम्",
    "Ludhiana Town": "लुधियाना-नगरम्",
    "Ludhiana": "लुधियाना",
    "Kotkapura": "कोटकापुरा",
    "Nallabelly": "नल्लाबेली",
    "Wyra": "वायरा",
    "Faridkot": "फरीदकोट",
    "Warangal": "वरंगल",
    "Chandigarh": "चण्डीगढ़",
    "Amritsar": "अमृतसरः",
    "Jalandhar": "जलन्धरः",
    "Bathinda": "बठिण्डा",
    "Patiala": "पटियाला",
    "Guntur": "गुण्टूरु",
    "Vijayawada": "विजयवाडा",
    "Visakhapatnam": "विशाखापट्टणम्",
    "Kakinada": "काकीनाडा",
    "Rajahmundry": "राजमहेन्द्री",
    "Anantapur": "अनन्तपुरम्",
    "Kurnool": "कर्नूलु",
    "Kadapa": "कडपा",
    "Nellore": "नेल्लूरु",
    "Chittoor": "चित्तूरु",
    "Ongole": "ओङ्गोलु",
    "Eluru": "एलूरु",
    "Punjab": "पञ्जाब"
  },
  "sd": {
    "Ramyasree Ramayanam": "رمياشري راماينم",
    "Ramyasree": "رمياشري",
    "Rahul Ramayanam": "راهل راماينم",
    "Rahul": "راهل",
    "Valued Farmer": "محترم هاري",
    "Registered Farmer": "رجسٽرڊ هاري",
    "Farmer": "هاري",
    "Admin": "ايڊمن",
    "System Admin": "ايڊمن",
    "Andhra Pradesh": "آندھرا پرديش",
    "Tirupati": "تيرپتي",
    "Srikalahasthi": "سريڪالهستي",
    "India": "ڀارت",
    "Tirupati, Andhra Pradesh": "تيرپتي، آندھرا پرديش",
    "Andhra Pradesh, Tirupati": "آندھرا پرديش، تيرپتي",
    "Srikalahasthi, Tirupati District, Andhra Pradesh, India": "سريڪالهستي، تيرپتي ضلعو، آندھرا پرديش، ڀارت",
    "District": "ضلعو",
    "district": "ضلعو",
    "Tirupati District": "تيرپتي ضلعو",
    "Town": "ٽائون",
    "town": "ٽائون",
    "Ludhiana Town": "لودھيانا ٽائون",
    "Ludhiana": "لودھيانا",
    "Kotkapura": "ڪوٽڪپورا",
    "Nallabelly": "نلابيلي",
    "Wyra": "وائرا",
    "Faridkot": "فريدڪوٽ",
    "Warangal": "ورنگل",
    "Chandigarh": "چنڊيڳڙهه",
    "Amritsar": "امرتسر",
    "Jalandhar": "جالندر",
    "Bathinda": "بٽنڊا",
    "Patiala": "پٽيالا",
    "Guntur": "گنٽور",
    "Vijayawada": "وجيواڙا",
    "Visakhapatnam": "وشاکاپٽنم",
    "Kakinada": "ڪاڪيناڊا",
    "Rajahmundry": "راجمنڊري",
    "Anantapur": "اننتپور",
    "Kurnool": "ڪرنول",
    "Kadapa": "ڪڊپا",
    "Nellore": "نيلور",
    "Chittoor": "چتور",
    "Ongole": "اونگول",
    "Eluru": "ايلورو",
    "Punjab": "پنجاب"
  }
};

// In-Memory Translation Cache to prevent duplicate API requests
const sarvamTranslationCache = new Map<string, string>();

/**
 * Helper to translate/transliterate location or name strings by replacing components
 */
function translateLocationString(text: string, langCode: string): string {
  const langDict = LOCAL_SARVAM_MAP[langCode];
  if (!langDict) return text;
  if (langDict[text]) return langDict[text];

  let result = text;
  // Try sub-phrase replacements (e.g. Srikalahasthi, Tirupati, Andhra Pradesh, India)
  Object.keys(langDict).forEach(key => {
    if (key.length > 2 && result.includes(key)) {
      result = result.split(key).join(langDict[key]);
    }
  });
  return result;
}

/**
 * Calls Sarvam AI translation / transliteration API for output fields.
 * - Skips API call when selected language is English.
 * - Checks in-memory cache first to avoid duplicate requests.
 * - Quietly falls back to local dictionary or original text on any network error/timeout/API unavailability.
 */
export async function translateWithSarvam(
  text: string,
  targetLang: string,
  mode: 'translate' | 'transliterate' = 'translate'
): Promise<string> {
  if (!text || typeof text !== 'string' || !text.trim()) {
    return text || '';
  }

  const cleanText = text.trim();
  const langCode = (targetLang || 'en').toLowerCase().split('-')[0];

  // Rule 6: If selected language is English, return original directly without calling API
  if (langCode === 'en') {
    return cleanText;
  }

  const sarvamCode = SARVAM_LANG_MAP[langCode] || `${langCode}-IN`;
  const cacheKey = `${mode}:${cleanText}:${sarvamCode}`;

  // Rule 10: Cache translated values to prevent duplicate API requests
  if (sarvamTranslationCache.has(cacheKey)) {
    return sarvamTranslationCache.get(cacheKey)!;
  }

  // 1. Check local pre-configured Sarvam AI map for instant output
  const localVal = translateLocationString(cleanText, langCode);
  if (localVal && localVal !== cleanText) {
    sarvamTranslationCache.set(cacheKey, localVal);
    return localVal;
  }

  // 2. Call Sarvam AI backend service
  try {
    const endpoint = mode === 'transliterate' ? '/api/transliterate/' : '/api/translate/';
    const response = await fetch(`http://127.0.0.1:8000${endpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        text: cleanText,
        target_language: sarvamCode,
        input: cleanText,
        source_language_code: 'en-IN',
        target_language_code: sarvamCode,
      }),
    });

    if (response.ok) {
      const data = await response.json();
      const result = data.translated_text || data.transliterated_text || data.result;
      if (typeof result === 'string' && result.trim()) {
        const finalStr = result.trim();
        sarvamTranslationCache.set(cacheKey, finalStr);
        return finalStr;
      }
    }
  } catch {
    // Quiet error handling
  }

  sarvamTranslationCache.set(cacheKey, localVal || cleanText);
  return localVal || cleanText;
}

/**
 * Custom React hook for Sarvam AI Username translation output.
 * Automatically updates when username or selected language changes.
 */
export function useSarvamUsername(originalUsername: string): string {
  const { currentLanguage } = useLanguage();

  const langCode = (currentLanguage || 'en').toLowerCase().split('-')[0];
  if (langCode === 'en' || !originalUsername) {
    return originalUsername || '';
  }

  const localVal = translateLocationString(originalUsername, langCode);

  const [translatedUsername, setTranslatedUsername] = useState<string>(localVal || originalUsername);

  useEffect(() => {
    if (!originalUsername) return;

    let isMounted = true;
    if (langCode === 'en') {
      setTranslatedUsername(originalUsername);
      return;
    }

    const freshLocal = translateLocationString(originalUsername, langCode);
    setTranslatedUsername(freshLocal);

    translateWithSarvam(originalUsername, currentLanguage, 'transliterate')
      .then(res => {
        if (isMounted && typeof res === 'string' && res) {
          setTranslatedUsername(res);
        }
      })
      .catch(() => {});

    return () => {
      isMounted = false;
    };
  }, [originalUsername, currentLanguage, langCode]);

  return translatedUsername || localVal || originalUsername;
}

/**
 * Custom React hook for Sarvam AI Location translation output.
 * Automatically updates when location or selected language changes.
 */
export function useSarvamLocation(originalLocation: string): string {
  const { currentLanguage } = useLanguage();

  const langCode = (currentLanguage || 'en').toLowerCase().split('-')[0];
  if (langCode === 'en' || !originalLocation) {
    return originalLocation || '';
  }

  const localVal = translateLocationString(originalLocation, langCode);

  const [translatedLocation, setTranslatedLocation] = useState<string>(localVal || originalLocation);

  useEffect(() => {
    if (!originalLocation) return;

    let isMounted = true;
    if (langCode === 'en') {
      setTranslatedLocation(originalLocation);
      return;
    }

    const freshLocal = translateLocationString(originalLocation, langCode);
    setTranslatedLocation(freshLocal);

    translateWithSarvam(originalLocation, currentLanguage, 'translate')
      .then(res => {
        if (isMounted && typeof res === 'string' && res) {
          setTranslatedLocation(res);
        }
      })
      .catch(() => {});

    return () => {
      isMounted = false;
    };
  }, [originalLocation, currentLanguage, langCode]);

  return translatedLocation || localVal || originalLocation;
}
