"""Multilingual PDF Report Generator Service supporting 23 Indian/regional languages."""

import io
from typing import Dict, Any, Optional
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from app.services.sarvam_service import translate_text_by_code, transliterate_text

def generate_multilingual_pdf(
    report_data: Dict[str, Any],
    language_code: str = "en"
) -> bytes:
    """Generate a complete PDF report translated into the user's selected language."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#2E7D32'),
        spaceAfter=12
    )

    heading_style = ParagraphStyle(
        'DocHeading',
        parent=styles['Heading2'],
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#1565C0'),
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#212121')
    )

    # Translate Section Headers
    doc_title = translate_text_by_code("AI Soil Health & Crop Recommendation Report", language_code)
    farmer_section = translate_text_by_code("Farmer & Field Details", language_code)
    soil_section = translate_text_by_code("Soil Test Parameters & Score", language_code)
    crop_section = translate_text_by_code("Recommended Crops & Fertilizers", language_code)
    footer_text = translate_text_by_code("Generated by AgroAI - Dynamic Multilingual System", language_code)

    # 1. Header Title
    story.append(Paragraph(doc_title, title_style))
    story.append(Spacer(1, 10))

    # 2. Farmer Details Table
    story.append(Paragraph(farmer_section, heading_style))
    raw_name = report_data.get("farmer_name", "Rahul Ramayanam")
    trans_name = transliterate_text(raw_name, language_code)

    farmer_info = [
        [translate_text_by_code("Farmer Name", language_code), trans_name],
        [translate_text_by_code("Location", language_code), transliterate_text(report_data.get("location", "Punjab, India"), language_code)],
        [translate_text_by_code("Report Date", language_code), report_data.get("date", "2026-08-03")],
    ]

    t_farmer = Table(farmer_info, colWidths=[200, 300])
    t_farmer.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F1F8E9')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#C8E6C9')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_farmer)
    story.append(Spacer(1, 12))

    # 3. Soil Analysis & Score
    story.append(Paragraph(soil_section, heading_style))
    soil_type = translate_text_by_code(report_data.get("soil_type", "Clay Soil"), language_code)
    soil_health = translate_text_by_code(report_data.get("soil_health", "Optimal"), language_code)

    soil_info = [
        [translate_text_by_code("Soil Type", language_code), soil_type],
        [translate_text_by_code("Soil Health Status", language_code), soil_health],
        [translate_text_by_code("Health Score", language_code), f"{report_data.get('health_score', 88.5)} / 100"],
        [translate_text_by_code("Nitrogen (N)", language_code), f"{report_data.get('n', 75)} mg/kg"],
        [translate_text_by_code("Phosphorus (P)", language_code), f"{report_data.get('p', 45)} mg/kg"],
        [translate_text_by_code("Potassium (K)", language_code), f"{report_data.get('k', 30)} mg/kg"],
    ]

    t_soil = Table(soil_info, colWidths=[200, 300])
    t_soil.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#E3F2FD')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#BBDEFB')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_soil)
    story.append(Spacer(1, 12))

    # 4. Crop Recommendations
    story.append(Paragraph(crop_section, heading_style))
    crops = report_data.get("recommended_crops", ["Wheat", "Rice", "Maize"])
    translated_crops = [translate_text_by_code(c, language_code) for c in crops]

    crop_info = [
        [translate_text_by_code("Top Recommended Crops", language_code), ", ".join(translated_crops)],
        [translate_text_by_code("Fertilizer Schedule", language_code), translate_text_by_code("Apply Urea at Vegetative Stage and NPK Basal Dose", language_code)]
    ]

    t_crop = Table(crop_info, colWidths=[200, 300])
    t_crop.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#FFF8E1')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#FFE082')),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t_crop)
    story.append(Spacer(1, 20))

    # Footer
    story.append(Paragraph(footer_text, body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
